- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1beta1/gitconfig.go
This makes the description consistent with v1alpha1
> fix v1beta1 CACertSecretRef description

- cmd/helm-sync/main.go
- e2e/testcases/csr_auth_test.go
- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/helmconfig.go
- pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
- pkg/api/configsync/v1beta1/helmconfig.go
- pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
- pkg/helm/helm.go
- pkg/reconcilermanager/controllers/util.go
> Remove spec.helm.valuesFiles field and update spec.helm.period field

- scripts/tag-release-candidate.sh
Determine the correct branch based on the patch version and
tag the latest commit on that branch for release candidates. Minor
releases are cut from main and patch releases are cut from release
branches. This is intended to minimize user error and make it easier
to tag release candidates without worrying about the local repo state.
> ensure branch is correct and up to date for RC tag

- cmd/nomos/status/client.go
This PR fixes nomos status to prevent it from panicing by ensuring the slice it references is of the right length.
> fix: Fix index out of bounds error in nomos status command

- e2e/testcases/reconciler_manager_test.go
Changed generation validation to be more dynamic instead of hardcoding the expected number. While individual test runs always starts from 1, CI runs use shared environment and generation numbers may have been changed by other test runs
> Change VPA e2e test to use dynamic generation validation

- build/e2e-tests/Dockerfile
- e2e/nomostest/nt.go
- e2e/testcases/apiservice.bats
- e2e/testcases/apiservice_test.go
- pkg/importer/filesystem/reconcile.go
- pkg/util/discovery/server_resourcer.go
This change applies to the recent CI failures in mono repo test under GKE environment.
Also updates the Gcloud CLI used in test containers and installs gke-gcloud-auth-plugin.
> Fix apiservice bats test

- e2e/testcases/apiservice_test.go
The mentioned RBAC includes necessary ClusterRole and ClusterRoleBindings
for the backend deployment to work in GKE environment. In Config Sync CI
after each test it will try to reset the test git repo to default in the sharedTestEnv.
Removing this RBAC from git directly is blocked by importer as it detects the 
commit will reduce the count of cluster resource from more than 1 down
to 0.
Thus manually deploying RBAC when test is running in mono repo mode.
> Use kubectl to deploy necessary RBAC in mono repo apiservice_test

- e2e/testcases/helm_sync_test.go
Change the RepoSync to sync from original git source at the end of test to make test works in the shared test environment.
> Update TestHelmNamespaceRepo to make it works in shared test environment

- e2e/nomostest/nt.go
- e2e/testcases/gatekeeper_test.go
- e2e/testcases/resource_conditions_test.go
> Fix cleanup for Gatekeeper tests

- e2e/testcases/helm_sync_test.go
Add more e2e tests to verify `gcenode` and `gcpserviceaccount` auth types work with Artifact Registry.
> Add e2e tests for Helm support

- Makefile
- Makefile.build
- Makefile.e2e
This change updates the make targets associated with retagging images to make them more generic/reusable.
> make retagging functionality generic

- pkg/parse/namespace.go
- pkg/parse/root.go
This reduces redundant metrics and allows us to wait until the sync metric is received to confirm that sync has occurred.
> Don't send sync metrics unless status has changed

- pkg/parse/namespace.go
- pkg/parse/root.go
- Update source and reconciling status updates to match existing sync statups update dedupe behavior.
- Log source, reconciling, and status errors when they change.
- Only send status metrics when there's a change, and then record them even if there's no errors. This should help reset reconciler_errors back to zero when the errors have been fixed.
> Avoid unnecessary status updates

- e2e/testcases/apiservice_test.go
The mentioned RBAC includes necessary ClusterRole and ClusterRoleBindings for the backend deployment to work in GKE environment. In Config Sync CI after each test it will try to reset the test git repo to default. Removing this RBAC from git directly is blocked by importer as it detects the commit of removal will reduce the count of cluster resource from more than 1 down to 0.
Thus manually deploying RBAC when test is running in mono repo mode.
> Use kubectl to deploy necessary RBAC in mono repo apiservice_test (#73)

- e2e/testcases/helm_sync_test.go
Change the RepoSync to sync from original git source at the end of test to make test works in the shared test environment.
> Update TestHelmNamespaceRepo to make it works in shared test environment (#75)

- pkg/metrics/metrics.go
- pkg/metrics/views.go
Fix pipeline_error_observed description to match the description in the resource-group controller.
> Fix pipeline_error_observed description to match

- e2e/nomostest/nt.go
- e2e/testcases/gatekeeper_test.go
- e2e/testcases/resource_conditions_test.go
b/240334486
Change-Id: I11a5e58e9c4b5653be80d5dad59f93c22de273bd
> Fix cleanup for Gatekeeper tests (#84)

- Makefile
- Makefile.build
- Makefile.e2e
This change updates the make targets associated with retagging images to make them more generic/reusable.
> make retagging functionality generic #99

- e2e/testcases/resource_conditions_test.go
This is to stabilize one flaky mono-repo test.
> Increase the wait timeout and add retries to a mono-repo test (#170)

- e2e/testcases/reconciler_manager_test.go
The gcenode-askpass-sidecar container's resource requirements will be adjusted on the autopilot cluster, so the generation should bumpt by 2.
> Fix a test failure on autopilot cluster

- e2e/nomostest/config-sync.go
- e2e/nomostest/nt.go
- e2e/testcases/invalid_git_branch_test.go
- e2e/testcases/root_sync_test.go
This reverts commit e91d5555afe2f33c0cf495bb76807d522f816cb2.
> Revert "Fix e2e test cleanup to reset git branch (#187)"

- e2e/testcases/helm_sync_test.go
The autopilot cluster adjusts the cpu/memory request of one managed resource. We need to update the expected values accordingly.
> Fix the test failure on the autopilot cluster

- manifests/templates/git-importer.yaml
- manifests/templates/reconciler-manager-configmap.yaml
> Update the git-sync image tag to fix the vulnerabilities

- manifests/templates/git-importer.yaml
- manifests/templates/reconciler-manager-configmap.yaml
> Update the git-sync image tag to fix the vulnerabilities (#204)

- e2e/testcases/root_sync_test.go
This is to fix the flakiness in https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/multi-repo-kind/1584975174380294144.
> Increase the retry timeout and aggregate the validation errors in a multierr

- docs/installation.md
this provides a bit more of a convenient UX to users to install the release manifests.
> update installation docs to install from url

- e2e/nomostest/nt.go
some of the cleanup functions check for Failed() when determining cleanup behavior. an example of this is the kind cluster cleanup, where the cluster is preserved if Failed() is true and the debug flag is provided. this change makes it so that such cleanup blocks can honor the --debug flag for shared kind environments.
> set fake shared env as failed when a test fails

- e2e/nomostest/wait.go
- e2e/testcases/cluster_selectors_test.go
- e2e/testcases/helm_sync_test.go
This patches multiple tests that wait for syncing after a non-commit change. They all now wait for their desired state, instead of assuming it already exists. This compensates for an API gap that doesn't track the generation of the RSync that was synced nor any changes to the reconciler config (namely cluster name). To fix this correctly, we will need to modify the API. So each case has a TODO and comment.
> Wait for non-commit changes to sync

- e2e/nomostest/metrics.go
- e2e/nomostest/metrics/validate.go
- e2e/testcases/no_ssl_verify_test.go
- e2e/testcases/override_git_sync_depth_test.go
- e2e/testcases/override_resource_limits_test.go
- pkg/metrics/metrics.go
- pkg/metrics/record.go
- pkg/metrics/register.go
- pkg/metrics/views.go
- pkg/parse/namespace.go
- pkg/parse/root.go
- pkg/reconcilermanager/controllers/gitsync_env.go
- pkg/reconcilermanager/controllers/reconciler_base.go
1. rendering_count
2. skip_rendering_count
3. resource_override_count
4. git_sync_depth_override_count
5. no_ssl_verify_count
> Remove five metrics for tracking feature adoption

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_base_test.go
Remove resources.limits field from reconciler manager allowList:
Previous reconciler manager allowList related logic added resources.limits to allowList to ignore the differences between declared and current deployments on this field when the declared deployment does not have resources.limits defined. However, this did not consider the case when user want to reset the resources.limits override, the declared deployment will also not have resources.limits fields defined.
Rename some functions in reconciler_base
> Make sure users can reset the resources.limits override

- pkg/applier/applier_err.go
Add some clarification to the largeResourceGroupError and a link to the doc for how to mitigate it.
> Improve largeResourceGroupError error message

- manifests/templates/reconciler-manager-configmap.yaml
> Update git-sync version to 3.6.2 to clear vulnerabilities (#343)

- e2e/testcases/lifecycle_directives_test.go
- e2e/testcases/namespaces_test.go
This avoids leaving the namespace modified (e.g. test label) in shared test environments.
> Checkpoint & revert protected namespaces in e2e

- e2e/nomostest/validate.go
This should help determine why the object still exists when debugging failed tests. Often it wasn't actually deleted, was re-created, or is stuck finalizing.
> Log object JSON when ValidateNotFound errors

- e2e/testcases/reconciler_finalizer_test.go
- Combine cleanup functions and use lists and for loops
- Skip cleanup on failure if debug is enabled
- Delete orphened safety namespaces
> Simplify TestReconcilerFinalizer cleanup

- e2e/nomostest/metrics/validate.go
> Re-enable the validation for the resource_conflicts metric

- e2e/nomostest/clean.go
- e2e/nomostest/config_sync.go
- e2e/nomostest/git.go
- e2e/nomostest/metrics.go
- e2e/nomostest/new.go
- e2e/nomostest/watch.go
- Log clean and reset time elapsed
- Log whether the test is cleaned or reset
- Log all git commands, if debug is enabled
- Avoid spamming git commands when waiting for sync
- Add a few misc clarifying comments
> Add more e2e test logs to help debug setup/cleanup

- e2e/nomostest/config_sync.go
- e2e/nomostest/nt.go
- e2e/nomostest/webhook.go
Use Apply instead of Create when ignoring IsAlreadyExists
> Add a nomostest field-manager

- e2e/nomostest/watch.go
This issue was causing the wrong error message in cases where no events ae received after the initial GET.
> Fix WatchObject to test predicates on initial GET

- build/all/Dockerfile
Bullseye image update for vulnerability fix
> Bullseye image update for vulnerability fix

- e2e/nomostest/git-server.go
This should restart the container if git stops responding to new connections and delay availability until ready.
> Add liveness & readiness probes to e2e git-server

- e2e/testcases/composition_test.go
The validateStatusCurrent function is called after waitForSync in the test. This assumes that all managed objects are reconciled after waitForSync, which may not be true.
> use WatchForCurrentStatus for composition_test

- e2e/nomostest/predicates.go
- e2e/testcases/sync_ordering_test.go
- Add validation for deletion ordering
- Enhance apply ordering validtion by using asynchronous watches
- Increase reconcile timeout to avoid needing to retry all the reconciliation validations. This should fix general flakiness when using cluster autoscaling, like on GKE Autopilot.
- Use multierr to perform multiple validations before failing the test.
> Fix TestDependencyWithReconciliation

- e2e/nomostest/clean.go
- e2e/nomostest/reset.go
- Use server-side filter to avoid deleting shared namespaces.
- Make it more clear which namespaces are protected and which are
shared between tests.
- Use client-go to delete namespaces in clean, instead fo kubectl
> Improve clean/reset of namespaces

- cmd/nomos/status/client.go
- e2e/testcases/cli_test.go
* Enable nomos status in OSS
* Fix presubmit formatting
> Enable nomos status command in OSS (#414)

- build/all/Dockerfile
https://security-tracker.debian.org/tracker/CVE-2023-0361
> Update the debina-base image to fix CVE-2023-0361

- build/all/Dockerfile
https://security-tracker.debian.org/tracker/CVE-2023-0361
> Update the debina-base image to fix CVE-2023-0361 (#424)

- manifests/templates/reconciler-manager-configmap.yaml
CVE-2022-4450    High
CVE-2023-0286    High
CVE-2023-0215    High
CVE-2023-0361    High
CVE-2023-23946   High
CVE-2022-2097    Medium
CVE-2023-22490   Medium
CVE-2022-4304    Medium
> Update the git-sync image to fix 8 vulnerabilities

- manifests/templates/reconciler-manager-configmap.yaml
CVE-2022-4450    High
CVE-2023-0286    High
CVE-2023-0215    High
CVE-2023-0361    High
CVE-2023-23946   High
CVE-2022-2097    Medium
CVE-2023-22490   Medium
CVE-2022-4304    Medium
> Update the git-sync image to fix 8 vulnerabilities (#429)

- cmd/nomos/status/client.go
- cmd/nomos/util/configmanagement.go
- cmd/nomos/util/write.go
- cmd/nomos/version/version.go
- e2e/testcases/cli_test.go
> Enable nomos version in OSS (#421)

- pkg/parse/state.go
Don't update the source status just because the sync status is newer. 
Do update the source status if the rendering status is newer.
> Avoid unnecessary source status update

- e2e/nomostest/watch.go
- e2e/testcases/composition_test.go
Use watch to log the diff when debugging and exit early when one of the watched objects is updated after syncing.
> Make TestComposition exit early on failure

- e2e/testcases/apiservice_test.go
The test failed on Autopilot cluster with a reconcile timeout:
```
Apply Reconciles (Total: 16):
Skipped (0),
Succeeded (15): [/Namespace/custom-metrics, /Namespace/safety-config-management-system-root-sync, /namespaces/custom-metrics/Service/custom-metrics-stackdriver-adapter, /namespaces/custom-metrics/ServiceAccount/custom-metrics-stackdriver-adapter, apiregistration.k8s.io/APIService/v1beta1.custom.metrics.k8s.io, apiregistration.k8s.io/APIService/v1beta1.external.metrics.k8s.io, apiregistration.k8s.io/APIService/v1beta2.custom.metrics.k8s.io, rbac.authorization.k8s.io/ClusterRole/external-metrics-reader, rbac.authorization.k8s.io/ClusterRole/metrics-reader, rbac.authorization.k8s.io/ClusterRole/safety-config-management-system-root-sync, …
```
> Increase the reconcileTimeout for the apiservice test (#445)

- pkg/syncer/syncertest/fake/dynamic_client.go
- Log diff with godebug/diff, instead of cmp.Diff, to get the full diff without trunation.
- Add Create handler
- Add Check method similar to fake.Client, for validating objects
- Add Put & PutAll methods similar to the fake.Client constructor,
for initializing the cluster state.
> Improve fake.DynamicClient

- e2e/nomostest/sync.go
- Tollerate nil status fields without panicing
- Add kind and yaml in parent predicates
- Remove unused monorepo sync predicates
> Fix e2e status checks

- e2e/nomostest/nt.go
Previously the OCI tests were using the latestSyncedCommit from the RootSync/RepoSync as the expected commit in the other status fields, which is circular logic.
This change uses git ls-remote to get the latest commit from the remote repo, without needing to clone it.
This unblocks an optimization for WaitForSync to avoid retrying the Sha1Fn.
> Fix OCI tests to read latest commit from git

- e2e/nomostest/config_sync.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
This reverts commit f45968c9623848bc185f2f9c489994784ef166d8.
> Revert "Fix e2e to avoid double setup (#457)"

- e2e/nomostest/nt.go
Tests in CI run the ls-remote step against CSR repos, but these repos require authentication to access. This change adds a step to first clone such repos using gcloud, which can authenticate using workload identity and set up the git credentials.
> test: fix ls-remote for CSR repos

- Makefile
These targets are not associated with a file artifact, and thus should be defined as phony targets. This impacted targets like vendor, for which an actual file/directory exists with the same name.
> fix: flag make targets as phony

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_base_test.go
- pkg/util/autopilot.go
> Handle the empty value of the Autopilot annotation

- e2e/testcases/csr_auth_test.go
There're different error messages returned from the fleet. This commit updates the check to include all possible messages.
Examples:
$ gcloud container fleet memberships describe kpt-config-sync-ci-r-multi-repo-8-standard-regular --project kpt-config-sync-ci-release ERROR: (gcloud.container.fleet.memberships.describe) No memberships available in the fleet.
$ gcloud container fleet memberships describe kpt-config-sync-ci-r-multi-repo-8-standard-regular --project cs-dev-hub ERROR: (gcloud.container.fleet.memberships.describe) Membership kpt-config-sync-ci-r-multi-repo-8-standard-regular not found in the fleet.
$ gcloud container fleet memberships describe kpt-config-sync-ci-r-multi-repo-8-standard-regular --project kpt-config-sync-ci-release ERROR: …
> Fix the check for the membership existence message

- e2e/testcases/csr_auth_test.go
In the original cleanup code, it checks the membership object on the cluster. Sometimes, the membership object is deleted successfully, while the membership resource still exists in the GCP project.
This commit updates the cleanup function to check the membership resource using gcloud.
> Fix the cleanup for fleet memberships (#484)

- pkg/util/autopilot.go
Before GKE 1.26, we determine an Autopilot cluster based on the presence of the `workload-defaulter.config.common-webhooks.networking.gke.io` MutatingWebhookConfiguration.
On GKE 1.26+, an Autopilot cluster replaces
`workload-defaulter.config.common-webhooks.networking.gke.io` with `sasecret-redacter.config.common-webhooks.networking.gke.io`.
> Detect the new autopilot webhook used on GKE 1.26+ (#501)

- .editorconfig
- Makefile
- scripts/build-junitreport-cli.sh
- scripts/build.sh
- scripts/debug-reconciler.sh
- scripts/docker-registry.sh
- scripts/e2e-kind.sh
- scripts/fail-if-dirty-repo.sh
- scripts/fmt-bash.sh
- scripts/generate-clientset.sh
- scripts/get-branch-or-sha.sh
- scripts/license-headers.sh
- scripts/lint-go.sh
- scripts/lint-license.sh
- scripts/lint-yaml.sh
- scripts/mirror-foo-corp-to-gh.sh
- scripts/multi-repo.sh
- scripts/prepare-licenses.sh
- scripts/publish-test-oci-images.sh
- scripts/push-test-helm-charts-to-ar.sh
- scripts/set-up-kcc-configs.sh
- scripts/set-up-workload-identity-configs.sh
- scripts/tag-promotion.sh
- scripts/tag-release-candidate.sh
- Add make fmt-sh that calls scripts/fmt-bash.sh
- Add EditorConfig with Google-standard shell style config
- Format the existing shell scripts
> Add shell formatting with shfmt

- build/all/Dockerfile
- build/test-e2e-go/gke/Dockerfile
- build/test-e2e-go/kind/Dockerfile
> Update render-helm-chart function to v0.3.0

- e2e/nomostest/portforwarder/port_forwarder.go
- e2e/nomostest/testwatcher/watch.go
- Update Watch to allow no timeout (WatchTimeout(0))
- Update ListWatch to take a context for cancellation/timeout
- Log PortForwarder command exit
Replaces https://github.com/GoogleContainerTools/kpt-config-sync/pull/528
> Update PortForwarder to watch with no timeout

- scripts/vulnerabilities.sh
- Auto-detect images from the manifest yaml
- Auto-detect current gcenode-askpass-image tag from Go constant
- Report non-GCR images with UNKNOWN fixable vulnerabilities
- Fix copyright header (Google's code, not Kubernetes)
> Update vulnerabilities script

- cmd/nomos/migrate/migrate.go
context: http://b/277592735#comment15
> Make `nomos migrate` output message clear when errors occur

- e2e/nomostest/nt.go
RemoteRepositories contains Repositories for all testcases, including previous tests which have finished. The local repo is stored in a temporary directory which is deleted at the end of the test, which caused this to fail when there was a leftover Repository in RemoteRepositories which was not defined in the current test. This switches the logic to only reset repositories used by the test.
> test: use RootRepos/NonRootRepos in init

- pkg/notifications/expressions/strings/strings.go
This snuck in while trying to debug an issue. Removing the extra debug logging.
> remove notification debug log

- e2e/nomostest/notification_config.go
- e2e/testcases/notification_test.go
Template and e2e test for created notification
> Template and e2e test for created notification

- build/all/Dockerfile
> Update base image to fix the vulnerability for CVE-2022-4415

- build/all/Dockerfile
> Update base image to fix the vulnerability for CVE-2022-4415 (#570)

- e2e/nomostest/notification_config.go
- e2e/testcases/notification_test.go
Template and e2e test for deleted notification
> Template and e2e test for deleted notification

- Makefile
- build/all/Dockerfile
- build/test-e2e-go/gke/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- pkg/hydrate/tool_util.go
CVE-2023-24538
CVE-2023-24536
CVE-2023-24534
CVE-2023-24537
> Bump the Kustomize CLI version to fix the vulnerabilities

- Makefile
- build/all/Dockerfile
- build/test-e2e-go/gke/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- pkg/hydrate/tool_util.go
CVE-2023-24538
CVE-2023-24536
CVE-2023-24534
CVE-2023-24537
> Bump the Kustomize CLI version to fix the vulnerabilities (#574)

- manifests/templates/reconciler-manager-configmap.yaml
CVE-2023-24538
CVE-2022-41723
CVE-2022-41724
CVE-2022-41725
CVE-2023-24536
CVE-2023-24534
CVE-2023-24537
CVE-2023-24532
> Update git-sync version for vulnerability fixes

- manifests/templates/reconciler-manager-configmap.yaml
CVE-2023-24538
CVE-2022-41723
CVE-2022-41724
CVE-2022-41725
CVE-2023-24536
CVE-2023-24534
CVE-2023-24537
CVE-2023-24532
> Update git-sync version for vulnerability fixes (#577)

- e2e/nomostest/notification_config.go
- e2e/testcases/notification_test.go
Template and e2e test for stalled notification
> Template and e2e test for stalled notification

- e2e/nomostest/nt.go
- e2e/testdata/prometheus/prometheus.yaml
b/281576844
b/281508753
b/281432500
> Empty Prometheus cache before each test case

- e2e/nomostest/nt.go
- e2e/testdata/prometheus/prometheus.yaml
b/281576844
b/281508753
b/281432500
> Empty Prometheus cache before each test case (#579)

- e2e/nomostest/testpredicates/predicates.go
- pkg/kinds/lookup.go
- Fix lookup.go license header
> Use Lookup instead of GVKForObject for nicer error

- pkg/reconciler/finalizer/reposync_finalizer_test.go
- pkg/reconciler/finalizer/rootsync_finalizer_test.go
- pkg/syncer/syncertest/fake/client.go
- Add Watch impl
- Add Finalizer & deletionTimestamp impl
- Ignore Limit requests, instead of erroring. This allows informers to work. They just get all the objects in the first request, instead of paginating. We can add pagination support later, if needed.
- Treat both DeletePropagationForeground and DeletePropagationBackground requests as Foreground, instead of erroing. We can add background support later, if needed.
> Fake client enhancements

- e2e/testcases/oci_sync_test.go
The original cleanup for TestSwitchFromGitToOci was disabling the webhook and deleting the implicit namespace, but this Cleanup was executing before the RootSync was deleted, so the RootSync reconciler was still owning the implicit namespace and might revert the delete, causing a race condition.
The change from https://github.com/GoogleContainerTools/kpt-config-sync/pull/583 was supposed to fix this, by adding the implicit namespace to the RootSync Git repo, to allow the reconciler finalizer to delete it. But this caused a deadlock, in that deleting the namespace triggered k8s garbage collection to delete the RepoSync. While the RepoSync was initially also managed by the RootSync, it gets removed and manually managed half way through the test. Then the RepoSync finalizer blocked deletion …
> Fix TestSwitchFromGitToOci test cleanup

- e2e/testcases/oci_sync_test.go
The cleanup of this test had a few issues:
- Not adding the deletion propagation annotation to the RepoSync
- Not properly resetting the spec when switching between field managers
This change sets the deletion propagation annotation and ensures that the fields get properly reset when switching field managers.
> test: fix test cleanup for TestSwitchFromGitToOci

- e2e/nomostest/clean.go
- e2e/nomostest/crds.go
- e2e/nomostest/prometheus.go
- e2e/nomostest/reset.go
- Use DeleteObjectsAndWait whenever possible, to ensure the object is fully deleted before continuing.
- Always allow NotFound from delete calls
> Delete more carefully in e2e cleanup/reset

- pkg/reconcilermanager/controllers/secret.go
- Fix upsertSecret by using the controller-runtime CreateOrUpdate function, which uses semantic.DeepEquals to prevent unnecessary updates.
- Simplify logging to be more consistent with other upsert methods
- Ensure managed label values are reverted on update if changed.
> Fix reconciler-manager upsertSecret

- pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
> Use gcenode v1.0.1 in config sync to fix CVE

- pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
> Use gcenode v1.0.1 in config sync to fix CVE (#630)

- e2e/nomostest/clean.go
- pkg/kinds/lists.go
- Makes it easier to delete objects after listing
> Add DeleteObjectListItemsAndWait e2e func

- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- Error if reconciler deployment status is invalid/unknown
- RecordReconcileDuration in a few extra failure cases
> Report Stalled condition if reconciler Terminating

- pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
- pkg/syncer/syncertest/fake/watcher.go
- Add a filter to Watcher.handleEvents to drop "old" events if newer events have already been received, based on ResourceVersion.
- Change DriftProtection tests to tolerate missed events by checking that the ResourceVersion is newer and the value is reverted, instead of checking that all expected values states were observed.
> Fix flakey DriftProtection tests

- build/all/Dockerfile
CVE-2023-2650 CVE-2023-0464 CVE-2023-0466
b/284324683
> Update base image to fix vulnerability

- manifests/templates/reconciler-manager-configmap.yaml
> Update git-sync image to fix vulnerability

- e2e/testcases/helm_sync_test.go
We have a targeted test for verifying token auth with the helm-sync container. For other tests, it is preferred to use workload identity auth as it is simpler to manage.
> test: use WI for helm-sync tests

- e2e/testdata/root-sync-helm-chart-cr.yaml
Test to see if this fixes the CI issues
> Bump helm sync resource limits

- e2e/nomostest/reset.go
The existence of managed namespaces can cause issues in subsequent tests when they are not cleaned up. Make the reset code fail upon the existence of managed namespaces so that we can quickly discover tests which do not clean up after themselves.
Include implicit namespaces in the namespaces list for the reset code. This ensures implicit namespaces are either deleted if they do not have a manager or error if they do have a manager.
> test: stricter namespace cleanup

- cmd/helm-sync/main.go
- e2e/testdata/root-sync-helm-chart-cr.yaml
- e2e/testdata/root-sync-helm-chart-version-range-cr.yaml
- pkg/helm/helm.go
still experimenting for the CI failures
a note that this is still likely only addressing symptoms rather than a root cause, but I am curious to see what happens
> add retries around helm templating step

- Makefile.oss.prow
> fix: positional arg for docker build

- e2e/nomostest/clusters/gke.go
It is possible an operation is in progress on the cluster at the time that the deletion request is sent. This causes the deletion request to error. Retry for a brief period to increase the likelihood that the cluster can be deleted.
> test: retry deletion of gke clusters

- e2e/nomostest/testwatcher/watch.go
Switch from Until to UntilWithSync, which uses an informer to handle recovery from "Resource version too old" errors. This has the key side-effect that you're no longer guaranteed to see every event. So tests should not try to record events and compare to an expected set. Instead, validate the expected result and that the ResourceVersion has advanced.
> Fix e2e tests failing on recoverable watch error

- manifests/base/kustomization.yaml
- manifests/oss/kustomization.yaml
Bundle the resource-group manifest into the Config Sync manifest for the ACM operator
> Bundle the resource-group manifest into the Config Sync manifest

- e2e/nomostest/clusters/gke.go
Cluster creation via gcloud waits for the operation but has been occasionally timing out in CI. This change uses --async with a manual wait for the operation with our own timeout.
> test: longer timeout for gke cluster creation

- e2e/nomostest/clusters/gke.go
Some GKE operations are timing out, which causes the job to fail. Extend
the timeout, particularly for cluster creation. Also, wait for cluster
delete operations to complete at the end of the job so that the next job
can start after the previous job is cleaned up.
> ci: extend gke operation timeouts

- e2e/nomostest/clusters/gke.go
GKE operation timeouts can take a long time, especially on autopilot. Instances in CI were observed where RESIZE_CLUSTER operations took approximately 20 minutes to complete. This change updates the waits to use a consistent/longer timeout to account for these longer operations.
> test: consolidate/extend gke operation timeout

- e2e/nomostest/reset.go
- e2e/testcases/reconciler_finalizer_test.go
This change makes a few enhancements to the reconciler-finalizer tests to help with debugging, namely:
- Wrap the logging of reconciler logs in a cleanup. This ensures that the logs get printed in the case of a failure, even if kubectl returns before the test fails (e.g. Pod eviction)
- Replace usages of Wait with taskgroup/watch. This provides more useful logging as each watch event gets logged.
> test: enhancements to reconciler finalizer tests

- e2e/testcases/reconciler_manager_test.go
This test is flaky on autopilot due to the strict check on the generation of the root-reconciler Deployment. Mutations on autopilot sometimes cause the generation to be greater than the expected generation (e.g. off by one). This updates the test to use HasGenerationAtLeast to tolerate these scenarios. Also updates the Wait code to use the newer Watch code.
> test: fixes for TestManagingReconciler

- e2e/nomostest/clusters/gke.go
The e2e clusters which are used for gcenode auth must have oauth scopes specified to enable auth to CSR/GAR.
> test: set oauth scopes for gcenode e2e clusters

- test/docker/http-git-server/Dockerfile
Patch the OS-level packages and remove unneeded dependencies to minimize the vulnerabilities
> Patch the OS-level packages and remove unneeded dependencies

- pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
This is to pick up the vulnerability fix in http://tg/1958866.
> Bump askpass image

- pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
This is to pick up the vulnerability fix in http://tg/1958866.
b/291841151
> Bump askpass image (#755)

- manifests/templates/reconciler-manager-configmap.yaml
https://security-tracker.debian.org/tracker/CVE-2023-29406
> Update git-sync to address one vulnerability

- manifests/templates/reconciler-manager-configmap.yaml
https://security-tracker.debian.org/tracker/CVE-2023-29406
> Update git-sync to address one vulnerability (#754)

- scripts/vulnerabilities.sh
> Update the vulnerabitility scan script to check all fixable CVEs

- manifests/templates/reconciler-manager-configmap.yaml
- Expose errors from credential fetch via askpass
- Update base image to mitigate CVEs
> Update git-sync to v3.6.9

- e2e/testcases/reconciler_manager_test.go
Using an exact generation predicate is very flaky on Autopilot, because the generation can often change due to resource adjustments. HasGenerationAtLeast is a less precise assertion, but passes more reliably on Autopilot.
Also replaces usage of nomostest.Wait with the more current Watcher.
> test: use HasGenerationAtLeast for autopilot

- e2e/testcases/override_reconcile_timeout_test.go
This test has been relatively flaky, particularly on autopilot. The condition of the flake appears to frequently coincide with a node replacement that causes Pod eviction. This presumably causes the reconciler Pod to get evicted and restarted, and by the time it comes back up the goproxy Pod is ready.
This extends the delay of the goproxy readinessProbe in order to reduce the chance of encountering this scenario on autopilot.
[Example flake](https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-autopilot-rapid/1688646113445285888):
```
override_reconcile_timeout_test.go:106: ERROR: WatchObject(ResourceGroup config-management-system/root-sync): predicates not satisfied: object "pod-1" does not have expected actuation and reconcile status, actual actuation status …
```
> test: reduce flakiness of reconcile timeout e2e

- e2e/testcases/stress_test.go
We've found OOMKills in ACM 1.16.0 on Autopilot clusters with 100+ CRDs. This commit adds a stress test to make sure Config Sync can still work with those CRDs.
> Add a stress test with 100 CRDs

- e2e/testcases/helm_sync_test.go
- pkg/core/decorate.go
- pkg/reconcilermanager/controllers/helm_value_files.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/secret.go
- Add AddAnnotations and AddLabels funcs to core
- Fix TestHelmConfigMapNamespaceRepo to change to a new ConfigMap instead of re-creating an immutable one.
> fix: nil pointer in upsertHelmConfigMap

- manifests/templates/reconciler-manager-configmap.yaml
Set default resource requests for askpass container
> Set default resource requests for askpass container

- e2e/testcases/override_reconcile_timeout_test.go
This test has been relatively flaky, particularly on autopilot. The condition of the flake appears to frequently coincide with a node replacement that causes Pod eviction. This presumably causes the reconciler Pod to get evicted and restarted, and by the time it comes back up the goproxy Pod is ready.
This extends the delay of the goproxy readinessProbe in order to reduce the chance of encountering this scenario on autopilot.
> test: reduce flakiness of reconcile timeout e2e (#791)

- manifests/templates/reconciler-manager-configmap.yaml
After discussing with @janetkuo , we will reduce the askpass container default memory
> Reduce askpass container default memory

- e2e/testcases/helm_sync_test.go
- e2e/testcases/reconciler_manager_test.go
- pkg/core/decorate.go
- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/helm_value_files.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
- pkg/reconcilermanager/controllers/secret.go
- pkg/validate/raw/validate/source_spec_validator.go
/label tide/merge-method-rebase
> Cherrypick #803, #813 and #802 to v1.16 branch 

- manifests/templates/reconciler-manager-configmap.yaml
Reverts GoogleContainerTools/kpt-config-sync#842
> Revert "Set default resource requests for askpass container"

- manifests/third_party/resourcegroup-manifest.yaml
> [vulnerability] Bump resource group controller to v1.0.16

- manifests/third_party/resourcegroup-manifest.yaml
> [vulnerability] Bump resource group controller to v1.0.16 (#849)

- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
Use max for timestamp to get the latest;
Use max for duration distribution to get the longest;
Use max for count to get the latest.
> Change label aggregation in Moanrch to MAX

- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
Use max for timestamp to get the latest;
Use max for duration distribution to get the longest;
Use sum for count to get the total of one time serie.
/hold
> Change label aggregation in Moanrch to MAX (#845)

- e2e/testcases/multi_sync_test.go
The subsequent Pod checks are flaky because the Deployments may still be reconciling. When the Deployment is still reconciling, there may be more than the expected number of Pods - because the old replicas may not have been garbage collected yet.
> test: wait for deployments before checking pods

- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
It also updates the unit test to validate the injection.
> Inject GSA email to root-reconciler when using FWI

- Makefile
- pkg/hydrate/tool_util.go
CVE: https://github.com/advisories/GHSA-6xv5-86q9-7xr8
> Update helm binary to fix CVE

- Makefile
- pkg/hydrate/tool_util.go
CVE: https://github.com/advisories/GHSA-6xv5-86q9-7xr8
> Update helm binary to fix CVE (#858)

- e2e/testcases/multi_sync_test.go
Increase timeout to tollerate reconciler eviction/OOMKill. This should make the test less flakey on autopilot, where the node pools are frequently replaced.
> text: Fix TestConflictingDefinitions_RootToRoot

- e2e/testcases/custom_resources_test.go
Validate management conflict metric separately from source error. The conflict should be recorded with the first commit, and then not recorded with the second commit, because the remediator will be paused until the source error is resolved.
> fix: TestCRDDeleteBeforeRemoveCustomResourceV1

- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
This should help distinguish between code paths when triaging ambiguous errors from the reconciler-manager.
> Add context to setup/teardown error messages

- manifests/templates/reconciler-manager-configmap.yaml
- manifests/third_party/resourcegroup-manifest.yaml
- update git-sync from v3.6.9-gke.1__linux_amd64 to v3.6.9-gke.2__linux_amd64
- update askapss sidecar from v1.0.5 to v1.0.5
- upadte resource group from v1.0.16 to v1.0.17
> Update Config Sync component versions to fix CVEs

- build/all/Dockerfile
- build/prow/vulnerability-scanner/Dockerfile
- go.mod
> Update Go to 1.20.8 to fix CVEs

- e2e/nomostest/testpredicates/predicates.go
- e2e/testcases/reconciler_manager_test.go
Fix Autopilot resource math:
- Set limits to requsts
- Round CPU up to 250m
- Round Memory up to 512Mi
Change DeploymentContainerResourcesAllEqual to return a multierr, not just the first error.
Remove total validation, now that all the container resources are validated explicitly.
> test: Fix TestAutopilotReconcilerAdjustment

- cmd/nomoserrors/examples/examples.go
- e2e/testcases/cli_test.go
- pkg/vet/api_resources.go
- pkg/vet/api_resources_test.go
Nomos CLI: replace APIGROUP with APIVERSION
> Nomos CLI: replace APIGROUP with APIVERSION (#868)

- e2e/testcases/stress_test.go
We've found OOMKills in ACM 1.16.0 on Autopilot clusters with 100+ CRDs. This commit adds a stress test to make sure Config Sync can still work with those CRDs.
`TestStress100CRDs` is needed to cherry-pick nomos CLI client side throttling fix (https://github.com/GoogleContainerTools/kpt-config-sync/pull/853)
> Add a stress test with 100 CRDs (#804)

- cmd/reconciler/main.go
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/resource_override.go
- pkg/api/configsync/v1beta1/resource_override.go
This addresses some PR feedback from the original commit.
> feat: update API docs for namespaceStrategy

- docs/installation.md
PSP has been removed since K8s 1.25
> Remove PSP from installation guide

- e2e/testcases/reconciler_manager_test.go
Extract the math to a simulation method.
> fix: TestAutopilotReconcilerAdjustment math

- pkg/importer/reader/parse_file.go
- pkg/importer/reader/parse_file_test.go
Add tests to cover additional edge cases.
> fix: Ignore empty yaml documents

- Makefile
- Makefile.gen
- Makefile.reconcilermanager
- build/buildenv/Dockerfile
- Add gcloud & gsutil to buildenv
- Add make targets to generate CRDs & clients in buildenv container
> Update buildenv to v0.3.0

- scripts/vulnerabilities.sh
Some images may fail to be scanned for various reasons. At the moment this leads to a silent failure where the fixable_total is reported as zero. This change checks the analysisStatus and treats any non-success status as a failure.
> ci: check analysis status in vuln scan script

- scripts/vulnerabilities.sh
Some images may fail to be scanned for various reasons. At the moment this leads to a silent failure where the fixable_total is reported as zero. This change checks the analysisStatus and treats any non-success status as a failure.
> [cherry-pick] ci: check analysis status in vuln scan script (#960)

- cmd/nomos/status/client.go
- pkg/client/restconfig/config.go
Add logging to help debug nomos commands run in various environments.
> Log config contexts from nomos commands at -v=4

- pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
> test: Retry updates in reconciler-manager tests

- docs/design-docs/02-custom-root-reconciler-clusterrole.md
After further discussion, extending this API for RepoSync would be a breaking change to the delegated control pattern. This change updates the design doc to reduce the scope of the API to RootSync objects.
> docs: update RSync RBAC design doc for RootSync

- e2e/nomostest/config_sync.go
- e2e/nomostest/git-server.go
- e2e/nomostest/new.go
- e2e/nomostest/ssh.go
- e2e/testcases/composition_test.go
This should help speed up test setup.
> test: Deploy git-server async in e2e test setup

- e2e/testcases/override_log_level_test.go
Add RepoSync e2e test for log level override that validate overriding one and all containers and clearing all override value
> Add RepoSync e2e test for log level override

- e2e/testcases/override_log_level_test.go
Add hydration-controller log level validation to Root and Repo sync test by configuring Kustomize.
> Add hydration-controller validation to logging test

- pkg/vet/api_resources_test.go
Add more APIVERSION failing test scenario for invalid scope and missing data, and add more valid entry for standard scenario.
> Add unit test scenario for APIVERSION

- e2e/nomostest/wait_for_sync.go
- e2e/testcases/multi_sync_test.go
The previous fix resolved half of the problem with pushing the initial commit, but InitGitRepos also needs to create the repository on the server before the commit can be pushed. This change registers the RootRepos/NonRootRepos at the beginning of the test, so that if the auto-repair needs to run it will properly call InitGitRepos on all of the expected repositories. A new WatchForAllSyncs predicate is added which makes it easier to wait for a subset of RSyncs.
> test: fix multi sync flake with InitGitRepos

- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
> Update otel image to fix CVE

- manifests/templates/reconciler-manager-configmap.yaml
Update git-sync version to fix CVEs
> Update git-sync version to fix CVEs

- Makefile
> Update debian bookworm image

- Makefile
- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
- pkg/hydrate/tool_util.go
Bug fixes in separate PR: https://github.com/GoogleContainerTools/kpt-config-sync/pull/1095
> v1.17 cherry-pick: CVE fixes

- e2e/testcases/reconciler_finalizer_test.go
The fake finalizer should be removed even if the test failed in the middle. Otherwise, the namespace would be stuck in a terminating state. Example: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-regular-bitbucket/1747668032626364416
> test: move the fake test finalizer removal function into a cleanup block

- dashboard/cloud_monitoring_dashboard.json
> Fix sample dashboard metric resource type

- pkg/validate/raw/validate/source_spec_validator.go
Some error messages apply to all source types, but these messages are specific to the git source. This commit updates the messages by passing in the source type.
> fix: update the incorrect error messages

- cmd/oci-sync/main.go
- pkg/oci/fetcher.go
The AR authenticator was configured outside of the for loop. If the IAM
policy bindings are changed, the authenticator would NOT be refreshed.
Then it requires to restart the reconciler Pod.
This commit moves the AR authenticator inside the for loop.
> fix: get AR authenticator with retries

- e2e/testcases/helm_sync_test.go
Suppressing the user output also disabled output for the happy path where a version exists. This reverts the behavior back to how it was before with an error check on the output.
> fix: enable user output for version list (#1084)

- e2e/testcases/reconciler_finalizer_test.go
The fake finalizer should be removed even if the test failed in the middle. Otherwise, the namespace would be stuck in a terminating state. Example: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-regular-bitbucket/1747668032626364416
> test: move the fake test finalizer removal function into a cleanup b lock (#1106)

- pkg/reconcilermanager/controllers/rootsync_controller.go
Config Sync doesn't generate a copy of root Secret, so no need to validate the generated secret name length.
b/326430718
> fix: stop validating root secrets

- Makefile
- e2e/nomostest/git-server.go
- e2e/testcases/git_sync_test.go
- manifests/templates/reconciler-manager-configmap.yaml
/label tide/merge-method-rebase
> Cherrypick the git sync fix to the v1.17 branch

- e2e/testcases/namespace_repo_test.go
The test used a short timeout to wait for the Deployment to become current, which can be flaky on autopilot. The test does not really care whether the Deployment reconciles, so the assertion is changed to a simple existence check. Additionally, if the test fails in the middle it may not have permission to manage/delete the Deployment. A cleanup block is added to ensure the Deployment can be deleted in cleanup.
> test: fix flake with TestNamespaceRepo

- cmd/admission-webhook/main.go
- cmd/reconciler-manager/main.go
- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
- pkg/resourcegroup/controllers/root/suite_test.go
- pkg/resourcegroup/controllers/runner/run.go
old techdebt (b/264312480) to remove the ctrl.Log
> removed ctrl.Log

- scripts/install-helm.sh
This PR makes sure that helm is executable within the helm-sync container
> Fix issue with helm not being executable

- e2e/nomostest/ssh.go
It seems like keygen is failing, but not erroring. Log the output if the file wasn't created, to help debug.
> Log ssh-keygen output on failure

- cmd/helm-sync/main.go
- e2e/nomostest/config_sync.go
> Add retry with backoff on error to helm-sync

- Makefile.oss.prow
- e2e/nomostest/config_sync.go
- e2e/nomostest/kustomizecomponents/validate.go
- e2e/testcases/cli_test.go
- e2e/testcases/gcenode_test.go
- e2e/testcases/oci_sync_test.go
- e2e/testcases/workload_identity_test.go
- e2e/testdata/helm-charts/simple-ns-chart/Chart.yaml
- e2e/testdata/helm-charts/simple-ns-chart/templates/deployment.yaml
- e2e/testdata/helm-charts/simple-ns-chart/values.yaml
- e2e/testdata/hydration/namespace-repo/kustomization.yml
- e2e/testdata/hydration/namespace-repo/test-ns/kustomization.yaml
- e2e/testinfra/terraform/common/service_accounts.tf
- e2e/testinfra/terraform/prow/service_accounts.tf
> Add test coverage for RepoSync auth types

- e2e/testinfra/terraform/prow/service_accounts.tf
The cross-project Fleet WI tests in workload_identity_test.go require the R*Sync's KSA to impersonate the corresponding GSA.
> test: add missing IAM bindings for the cross-project Fleet WI

- pkg/reconciler/reconciler.go
When instantiating the ValueConverter, it also calls the Refresh function to pull fresh schemas from the OpenAPI discovery endpoint, which is very memory-intensive. This commit changes it to only instantiate the converter when webhook is enabled, so it will reduce memory usage when the webhook is not used.
b/295389452
> fix: only instantiate ValueConverter when webhook is enabled

- e2e/nomostest/testpredicates/predicates.go
- e2e/nomostest/wait_for_sync.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/namespace_repo_test.go
- e2e/testcases/namespace_strategy_test.go
- e2e/testcases/remediator_test.go
- e2e/testcases/sync_ordering_test.go
- pkg/applier/applier.go
- pkg/applier/applier_err.go
- pkg/applier/applier_test.go
This adds the resource that the applier failed to apply to the returned applier error
b/302605005
b/301925049
> Add resource to apply failed events

- Makefile
- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1200
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1197
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1201 
go/cs-cherrypicks
> Cherry-pick CVE fixes for 1.18.1

- e2e/nomostest/clean.go
- e2e/nomostest/testpredicates/predicates.go
If uninstall fails or times out, continue with existing more aggressive cleanup. This may take longer, but should give Config Sync a chance to clean up objects following reverse dependency ordering. Hopefully, this will help avoid race conditions and deadlocks.
> e2e: attempt to uninstall packages in cleanup

- e2e/nomostest/client.go
- e2e/nomostest/clusters/gke.go
- e2e/nomostest/clusters/kind.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/new.go
> test: log cluster hash and version along with the cluster name

- manifests/templates/reconciler-manager-configmap.yaml
> Mount empty volume for hydration-controller's service account

- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
> Bump otelcontrolcol to 0.102.0-gke.2

- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
> Bump otelcontrolcol to 0.102.0-gke.2 (#1248)

- e2e/nomostest/gitproviders/bitbucket.go
http://shortn/_Bd3xcgBlEG Repo deletion error.
> Update Bitbucket workspace

- pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
- Test was flakey because the update retry wasn't getting the latest object version before retrying. Just use mutate.Spec instead.
> Fix TestReconcileRepoSyncLifecycleValidToInvalid

- e2e/nomostest/gitproviders/bitbucket.go
http://shortn/_Bd3xcgBlEG Repo deletion error.
> test: Update Bitbucket workspace (#1250)

- scripts/install-kustomize.sh
* Modifies `install-kustomize.sh` to make sure Kustomize is executable
* This is similar to what was done in https://github.com/GoogleContainerTools/kpt-config-sync/pull/1170
> Modify install-kustomize script

- e2e/testcases/otel_collector_test.go
This adds the actual value in addition to the expected value, in order to help with debugging.
> test: add actual value to metrics validation errs

- e2e/nomostest/clean.go
The fake finalizer should usually be cleaned up by the test which adds it, but sometimes the finalizer fails to be removed (e.g. crash). If the finalizer fails to be removed by the test, the cluster becomes wedged and requires manual intervention to fix. This adds logic to Clean which removes the finalizer so that manual intervention is not required.
Also removes the early returns so that goroutines are not leaked by this function.
> test: adds cleanup logic to remove fake finalizer

- e2e/testcases/cli_test.go
If either of the migrate tests fail early, the ConfigManagement object may be left lingering on the cluster. This will cause the Create call to fail for subsequent executions of these tests on the cluster, because the config-management object already exists.
> test: clean up ConfigManagement in e2e test

- e2e/nomostest/testpredicates/predicates.go
- e2e/testcases/hydration_test.go
- Refactor nomos status validation as Predicate
- Move nomos status validation into existing watches to ensure both conditions are true at the same time. This works around a race condition caused by retries removing errors from the Syncing condition.
- Use NT.Must where possible
- Use TaskGroup to parallelize validations
This PR changes the expectations for rendering tests to account for the possibility that the rendering errors may or may not always show up in the Syncing condition after the error. This allows us to later update the code to update the `status.source.commit` & Syncing condition after fetching but before rendering.
> e2e: cleanup hydration tests

- e2e/nomostest/clean.go
If a finalizer is force removed during cleanup, it is possible that root reconciler ClusterRoleBindings may be orphaned on the cluster. This has caused some test failures due to the lingering resources.
Example test failure: https://oss.gprow.dev/view/gcs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-regular/1805843581710110720
> test: clean up root reconciler ClusterRoleBindings

- Makefile
- e2e/flags.go
- e2e/nomostest/clusters/kind.go
- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/types.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/kubeadminit/init.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeadm/config.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/common/getport.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provision.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/nerdctl/OWNERS
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/nerdctl/constants.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/nerdctl/images.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/nerdctl/network.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/nerdctl/node.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/nerdctl/provider.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/nerdctl/provision.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/nerdctl/util.go
- vendor/sigs.k8s.io/kind/pkg/cluster/provider.go
- vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go
- vendor/sigs.k8s.io/kind/pkg/fs/fs.go
- vendor/sigs.k8s.io/kind/pkg/internal/apis/config/types.go
- vendor/sigs.k8s.io/kind/pkg/internal/apis/config/validate.go
This bumps the kind version to latest and the default k8s version used for kind clusters.
> test: bump kind and default k8s version

- e2e/nomostest/testpredicates/predicates.go
- e2e/testcases/multi_sync_test.go
Add a background watch to TestConflictingDefinitions_RootToRoot to make it faster to detect conflict and easier to debug when it's not working, with diffs logged for the Role as well as both RootSyncs.
> e2e: watch Role during RootToRoot conflict test

- e2e/testcases/cli_test.go
- pkg/bugreport/bugreport.go
Previously nomos bugreport output duplicate JSON and YAML files for all of the k8s objects. This is redundant, and YAML is generally more readable/useful for the purpose of the bugreport. The JSON increased the bugreport size unnecessarily and is therefore removed.
Also updates the test to perform a stricter file existence check, so that it will report an error for any unexpected files in the bugreport.
> feat: only output yaml in bugreport

- pkg/parse/run.go
- pkg/parse/sync_status_cache.go
- pkg/parse/updater.go
- pkg/remediator/conflict/handler.go
- pkg/remediator/reconcile/reconciler.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/status/error_builder.go
- pkg/status/management_conflict_error.go
Depends on https://github.com/GoogleContainerTools/kpt-config-sync/pull/1342
> fix: applier not recording conflict metric

- e2e/testcases/stress_test.go
Return an error so the caller can decide whether to error or fail the test.
> e2e: refactor validateNumberOfObjectsEquals

- e2e/nomostest/config_sync.go
Move the test defaults into one function, as much as possible.
> e2e: Add SetRSyncTestDefaults

- e2e/testcases/workload_identity_test.go
This was broken by a previous change which refactored the logic for setting the expected git commit and image digest.
Fixes a breaking change introduced by https://github.com/GoogleContainerTools/kpt-config-sync/pull/1410
Example failure: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-regular/1831391944727597056
> fix: set expected oci digest for wi tests

- e2e/testcases/workload_identity_test.go
These tests were broken by a previous refactor.
This fixes a breaking change introduced by https://github.com/GoogleContainerTools/kpt-config-sync/pull/1410
Example failure: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-regular/1831724137190526976
> test: fix gcr workload identity tests

- e2e/testcases/cli_test.go
- pkg/bugreport/bugreport.go
> Include ConfigMaps from all controller namespaces in bugreport

- e2e/nomostest/gitproviders/bitbucket.go
> ci fix: updated to the new bitbucket ws

- installation/kustomization.yaml
This adds additional information to the description of the admission webhook in the kustomization file.
> Update description of admission-webhook in install

- e2e/nomostest/oci-image-verification-server.go
> e2e: Only create registry secret when using local registry provider

- pkg/parse/events/funnel_test.go
The e2e tests use a short sync period to speed up tests. So this change adds tests that confirm that the retry backoff still works as intended when its shorter and longer than the sync period.
The SyncEvent only calls ParseAndUpdate if a source change was detected, so it's safe to still send SyncEvents when the retry backoff is longer than the SyncPeriod, because what we really want to delay is the ParseAndupdate calls, which cause a lot of API server requests.
> chore: test retry with long and short sync periods

- go.mod
- go.sum
- vendor/golang.org/x/oauth2/LICENSE
- vendor/golang.org/x/oauth2/README.md
- vendor/golang.org/x/oauth2/google/google.go
- vendor/golang.org/x/oauth2/token.go
- vendor/modules.txt
> chore: updated the golang.org/x/oauth2 to v0.24.0

- pkg/parse/run.go
- Wait for the async status updates to complete before continuing after updating.
> fix: out-of-order status updates

- pkg/parse/root_sync_client.go
- pkg/parse/run_test.go
- Fix a bug where errorCountAfterTruncation was not being set for rendering errors when truncated=false.
b/379720690
> fix: errorCountAfterTruncation=0 not set

- e2e/nomostest/nt.go
Autopilot clusters with zero nodes were causing the version check to fail with an empty string in the split result. So I added a check to tolerate zero nodes if the control plane is new enough, assuming new nodes will use the control plane version.
> e2e: fix version check failing when zero nodes

- Makefile
- pkg/hydrate/tool_util.go
> Bump helm version

- Makefile
Fix CVE CVE-2024-45338
b/385026752
> [chore] Bump otelcontribcol version

- Makefile
This resolves some CVEs in the previous image
> chore: bump git-sync to v4.3.0-gke.7

- test/docker/presync-webhook-server/oci-signature-verification-server.go
The OCI signature verification server currently always uses the google authenticator, even when running on KinD clusters. After upgrading the k8s libraries, the webhook response changes to a message reporting the unavailability of the GCE metadata server.
This change makes the authenticator configurable so that google auth only needs to be used when running against GAR. This will enable the test assertions to pass after upgrading the k8s libraries.
After this is submitted, the image will be built/published and the test scaffolding will be updated to set the environment variable.
> test: configurable google auth for oci sig server

- e2e/testcases/basic_test.go
Reverts GoogleContainerTools/kpt-config-sync#1545
New tests failing in CI: https://testgrid.corp.google.com/googleoss-kpt-config-sync-main#standard-regular-csr
Confusingly, it's just on that suite. Not sure why. Needs debugging.
```
repository.go:534: 2025-02-13 18:17:14.294351206 +0000 UTC [repo root-sync] committing: create RootSync with too long name
repository.go:542: 2025-02-13 18:17:14.301726586 +0000 UTC [repo root-sync] pushing commit: 74fe8989efdf5a950adca18b4ffe740645ccf245
repository.go:569: 2025-02-13 18:17:17.612034148 +0000 UTC took 3.310270302s to push
basic_test.go:262: 2025-02-13 18:23:35.008940504 +0000 UTC failed after 6m0s to wait for RootSync nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn sync error code 2009
basic_test.go:262: 2025-02-13 18:23:35.009001254 +0000 UTC ERROR: …
```
> Revert "test: add e2e tests to verify the max RSync NN length"

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
Depends on https://github.com/GoogleContainerTools/kpt-config-sync/pull/1564
> chore: minor cleanup to reconilcer controllers

- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
- pkg/resourcegroup/controllers/root/root_controller.go
Let the controller-manager handle reconcile retries with shared backoff, instead of trying to handle retrying in the ResourceGroup reconciler.
This should also help avoid some conflicts from updating with stale inputs.
> fix: ResourceGroup controller stuck retrying

- pkg/reconcilermanager/controllers/gitsync_env.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
> chore: return error from gitSyncEnvs instead of logging the error

- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
- Deprecate the `Reconciling` condition on the ResourceGroup, because it doesn't actually reflect the aggregate reconcile status of the objects synced by Config Sync from the source of truth. This condition will now always have a `status` of  `False` and a `reason` of `FinishReconciling` to avoid breaking any clients that were waiting for that state. This change reduces churn on the ResourceGroup objects, which had been frequently flipping back and forth between a `status` of `True` and `False`. To learn how to wait for all the managed objects to be synced and reconciled, see https://cloud.google.com/kubernetes-engine/enterprise/config-sync/docs/how-to/monitor-rootsync-reposync#confirm_resources_in_the_commit_are_reconciled
- This change also removes the case that was setting the …
> fix: ResourceGroup unnecessary condition updates

- internal/third_party/github.com/GoogleContainerTools/kpt/pkg/live/inventoryrg.go
- vendor/github.com/GoogleContainerTools/kpt/pkg/live/inventoryrg.go
The ResourceGroup inventory client currently uses the output of the GetObject method to Update the ResourceGroup, but this makes it fight with the ResourceGroup controller, because it erases the status fields set by the RGC, mainly status.conditions.
This fix isn't quite as good as using server-side apply, but that would require the inventory client and RGC to use different field manager names.
This does not fix removal of conditions under status.resourceStatuses, only removal of status.conditions.
Fixes: b/401304237
> fix: inventory client deleting unmanaged fields

- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
- Fixed a bug that caused the ResourceGroup
`status.resourceStatuses[*].reconcile` field to become stale
between apply attempts and no longer reflect the current
reconciliation status of the managed objects.
For example, when actuation and reconcile succeed, but then the
object is rescheduled or becomes unhealthy, the reconcile status
should be changed to reflect that by the RGC, but it wasn't, until
the applier updated all the resource statuses in the next apply
attempt.
Dependencies: 
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1571
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1573
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1576
> fix: ResourceGroup resource reconcile status

- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
Add a comments for explaination of the decision.
> chore: Remove TODOs in ResourceGroup controller

- e2e/testcases/stress_test.go
Simulate the applier setting status.observedGeneration to unblock the ResourceGroup controller.
> test: fix TestStressResourceGroup

- e2e/nomostest/testkubeclient/client.go
- e2e/testcases/kcc_test.go
- e2e/testcases/resource_group_controller_test.go
- e2e/testcases/stress_test.go
- Update status.observedGeneration to unblock the ResourceGroup controller.
- Use nt.Must
- Add log messages for each test step
- Replace kubeDeleteIgnoreNotFound with nt.KubeClient.DeleteIfExists
- use nt.T.Cleanup to delete the test ResourceGroups
> test: Fix TestKCCResourceGroup

- Makefile
- pkg/hydrate/tool_util.go
> chore: update base image, Helm and Otelcontribcol

- pkg/applier/applier.go
- Return status error to get added context for certain errors
- Use core.SetAnnotation to simplify code
- Log at level 3 like other updates
Depends on https://github.com/GoogleContainerTools/kpt-config-sync/pull/1620
> refactor: cleanup UpdateStatusMode

- pkg/applier/inventory/inventory_converter.go
- pkg/applier/inventory/inventory_converter_test.go
Although UpdateStatus is not called and therefore the status is not updated, the Update call is larger due to the status being populated on the subresource. This causes the payload to be larger due to the status even when status is disabled.
This change fixes the issue by omitted the status subresource when status is disabled.
> fix: omit resource statuses when status is disabled

- cmd/nomos/nomos.go
This pull request includes an old request to output a success message (http://b/182464654).  Added a call to `util.MustFprintf` to print "Done!" upon execution of all the commands given that there are no errors.
> feat: add completion message to main command execution

- pkg/validate/raw/validate/management_annotation.go
This small change refactors the boolean logic in the ManagementAnnotation function to improve readability.
> refactor: ManagementAnnotation readability

- e2e/testcases/basic_test.go
The namespace was deleted before the RepoSync, causing a cleanup race condition where the Namespace garbage collector may run before the RepoSync has a chance to finalize. This can cause the RepoSync finalizer to fail because its secret is deleted before it can prune objects.
This fixes the issue by managing the Namespace and RepoSync in the same RootSync.
> test: fix TestMaxRepoSyncNameLength test flake

- e2e/testcases/adopt_client_side_applied_test.go
This change adds some additional assertions to verify the behavior of merging annotations/labels when adopting an already existing object with Config Sync. This is not a behavioral change but rather documents the current behavior.
> test: add assertions to adoption test case

- pkg/reconciler/finalizer/base_finalizer.go
This updates the reconciler finalizer to print more detailed stats on the objects it unmanages. This is accomplished by re-using the status logger of the applier for a consistent format.
> feat: print applier stats in reconciler finalizer

- docs/development.md
> chore: add Makefile rule to clean up unused images

- e2e/nomostest/gitproviders/bitbucket.go
https://oss.gprow.dev/view/gcs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-regular-bitbucket/1921928515163262976#1:build-log.txt%3A603
> test: Update Bitbucket workspace

- e2e/testcases/otel_collector_test.go
This pull request refactors and enhances the validation logic for Google Cloud Monitoring (GCM) metrics in the `otel_collector_test.go` file. The changes focus on improving test readability, reducing redundancy, and adding new validation capabilities for metrics. The most significant updates include introducing reusable validation functions, replacing inline retry logic with a dedicated function, and adding new functionality to validate metric labels and values.
* Added `metricHasLabels` function to validate the presence and correctness of specific labels on metrics.
* Enhanced `metricHasLatestValue` to handle cases where no data points exist, improving error reporting.
* Introduced `ReconcilerMetricTypes` and `syncLabels` variables to validate sync-related metrics and their labels, …
> test: add checks for Config Sync _sync labels on reconciler metrics

- Makefile
updating go version while I am onduty.  CI and Louhi updates forthcoming.
> chore: update Go version to 1.24.3 in Makefile and go.mod

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/enhancement.yaml
- .github/ISSUE_TEMPLATE/question.yaml
Adds github issue templates to streamline the experience of creating issues on GitHub.
> chore: add issue templates

- cmd/nomos/initialize/init.go
- cmd/nomos/nomos.go
> fix: add completion message to nomos init command only

- e2e/testcases/lifecycle_directives_test.go
This change adds a testcase which documents/validates the behavior of adopting a Namespace by one RootSync after it has been created by another RootSync as an implicit Namespace.
> test: add e2e test for adopting implicit namespace

- e2e/testcases/declared_fields_test.go
This was an old nginx image that does not support current media types.
When trying to upgrade kind the following error was observed: media type application/vnd.docker.distribution.manifest.v1+prettyjws is no longer supported since containerd v2.1
This moves the image definition to the constant so it gets updated consistently.
> [cherry-pick]: bump nginx image used by TestDeclaredFieldsPod

- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/constants.go
- pkg/reconcilermanager/controllers/validate_secret.go
- pkg/reconcilermanager/controllers/validate_secret_test.go
- pkg/validate/rsync/validate/source_spec_validator.go
- reuse constants
- distinguish between auth and secret configuration
> chore: clean up new source spec secret errors

- e2e/nomostest/testkubeclient/client.go
Sometimes a single replica Deployment can have multiple Pods when an older Pod is failed and the new Pod is running. This change updates GetDeploymentPod when in this intermediate state to return the running Pod and ignore the failed Pod(s).
This is a fix for some test flakes which have been observed
> test: fix GetDeploymentPod for failed Pods

- e2e/nomostest/config_sync.go
- e2e/testcases/proxy_test.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/validate/rsync/validate/source_spec_validator.go
- pkg/validate/rsync/validate/source_spec_validator_test.go
This PR updates the validation logic for RootSyncs where GitHub App Authentication is set with a Proxy
Issue - https://github.com/GoogleContainerTools/kpt-config-sync/issues/1797
> feat: Add support for proxy with githubapp auth

- e2e/testcases/remediator_test.go
The previous change fixed the flakiness with the RootSync status validation, but now the metrics validation is still flaky because the async status updates may stop before the expected number of fight metrics are emitted. This change validates the RootSync status and metric in parallel and only stops the async status updates once both conditions succeed/timeout.
Also adds an initial assertion to verify there are no fight errors at the beginning.
> test: fix metrics flake in TestSurfaceFightError

- cmd/reconciler/main.go
- e2e/testcases/remediator_test.go
- pkg/api/configsync/register.go
- pkg/reconciler/reconciler.go
- pkg/syncer/reconcile/apply.go
- pkg/syncer/reconcile/fight/detector.go
- pkg/syncer/reconcile/fight/detector_test.go
* Adds DefaultFightThreshold to register.go
* Adds fightThreshold member to the Detector struct
> refactor: fightThreshold global variable

- e2e/nomostest/gitproviders/bitbucket.go
The Bitbucket backend occasionally has issues creating or removing repos,
leaving them stuck in pending/starting state, causing CI to hang on failed
cleanup operations. Before the root cause is figured out, we make this change
to improve reliability:
- Add retry logic with 30s timeout for repository deletion
- Skip deletion of repositories that are "currently not available" 
- Add 1000 repo limit check to indicate workspace overflow
- Add TODO linking to known issue
> test: Add retry / skip logic and limit check for Bitbucket repository deletion

- Makefile
- e2e/nomostest/gitproviders/bitbucket.go
- e2e/nomostest/gitproviders/gitlab.go
- pkg/hydrate/tool_util.go
- update helm and otelcontribcol for CVE
- enhance bitbucket test error handling
- enhance gitlab test error handling
ref: https://github.com/GoogleContainerTools/kpt-config-sync/compare/v1.22...main
> v1.22.1 - essential cherrypick for CI on release

- e2e/testcases/gcenode_test.go
This change fixes the failing test TestGCENodeOCI by setting the correct expected image digest
> test: update expected image digest
