GoogleContainerTools/config-sync

- e2e/testcases/apply_scoped_resource_test.go
- examples/kubevirt-compiled/clusterrole_kubevirt.io-operator.yaml
- examples/kubevirt/cluster/kubevirt.io-operator-clusterrole.yaml
The presence of colons in the file names made it so that the project was
not importable by other go projects.
GoogleContainerTools/kpt-config-sync#4
> rename kubevirt operator files in examples

- e2e/nomostest/ssh.go
- e2e/testcases/private_cert_secret_test.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/secret.go
- pkg/reconcilermanager/controllers/secret_test.go
This follows the pattern of the user-provided secrets for git
credentials, where the user is expected to create the RepoSync secret in
the same namespace as the RepoSync. The secrets are then upserted to the
config-management-system namespace by the Reconciler. This is to support
use cases where the RepoSync user does not have access to the c-m-s
namespace.
> upsert privateCertSecret from RepoSync

- pkg/reconcilermanager/controllers/deployment_conditions.go
- pkg/reconcilermanager/controllers/deployment_conditions_test.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/secret_test.go
- pkg/util/env.go
- pkg/util/log/error.go
- This reduces duplicate code in CS and makes the messages more
consistent.
> Use kstatus for reconciler deployment status

- docs/contributing.md
- docs/design-docs/00-template.md
Created a design document template similar to the one that is used in kpt.  I suggest that we start using the design document process in the public repo instead of internal Google docs.
> added a design doc template

- e2e/nomostest/predicates.go
- e2e/testcases/private_cert_secret_test.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/secret.go
This updates the watch function to map changes to the user-managed
secret in the RepoSync namespace to the upserted secret in the
config-management-system namespace. This ensures the secret is kept up
to date if the user updates the secret.
Change is based on https://github.com/GoogleContainerTools/kpt-config-sync/pull/11
> add watch for privateCertSecret

- e2e/nomostest/ssh.go
The CA certificate is only created for the local git provider type, and
not created for nonlocal git providers. This could cause an error for
nonlocal git provider types when trying to create the namespace secret,
since the cert file does not exist.
> skip creating of namespace cert secret on nonlocal

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ssh.go
Shared test environments create the secret files once and then store the
path in the nt object to share the path between tests. This change
updates the test scaffolding to properly handle this for the CA cert
secret.
> fix caCertPath for shared test envs

- e2e/nomostest/new.go
This fixes a failure we are seeing in shared test environments where the
once created caCertPath was not being properly passed to the shared test
NT.
> pass caCertPath to shared test envs

- e2e/nomostest/nt.go
```
Usage:
kubectl logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER] [options]
```
Removed unnecessary "pod" argument that was causing this error:
```
nt.go:914: error running `kubectl logs pod ns-reconciler-bookinfo-6cfc9bff98-wn5gc -n config-management-system -c otel-agent`: exit status 1
Error from server (NotFound): pods "pod" not found}
```
> Fix printing not ready pod logs

- e2e/nomostest/ntopts/kind.go
There is a flaky condition in the kind e2e tests where the nodes are not
yet available when the git server pod is created. This may be a race
condition where the nodes are not ready yet, so this change attempts to
address it by adding a wait for ready step to the cluster creation.
> add wait for ready to kind cluster creation

- e2e/testcases/apiservice_test.go
- e2e/testdata/apiservice/namespace-custom-metrics.yaml
- e2e/testdata/apiservice/namespace.yaml
- e2e/testdata/apiservice/rbac.yaml
- pkg/util/discovery/server_resourcer.go
This change modifies the GetResource to only tolerate NotFound,
any other error is treated blocking and will be returned to
prevent resource pruning when backend is temporarily unavailable.
> Return blocking discover error to prevent resource pruning

- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/secret.go
- pkg/reconcilermanager/controllers/secret_test.go
- pkg/reconcilermanager/controllers/validate_secret.go
- Make managed object and sync object log messages more consistent
- Use ObjectKeys/NamespacedNames where possible to avoid making
assumptions about which namespace to use, and make it easier to
log the namespace & name together.
- Seperate auth secret and ca cert secret upserts to make the code
easier to read, and have distinct error messages, that explain
what the secret is for, since the user needs to supply it.
> Cleanup logs & errors in reconciler-manager

- Makefile
- e2e/testcases/helm_sync_test.go
- scripts/lint-license-headers.sh
the exit code was being lost in the previous make target due to the
pipe. This change moves the command to a bash script with pipefail
enabled so that the exit code is not lost.
> fix lint-license-headers make target

- Makefile.release
- scripts/tag-release-candidate.sh
These make targets are intended to be used for tagging, building, and
publishing release candidates. Make targets for promoting release
candidates will be added in a subsequent change.
> add make targets for building release candidates

- Makefile
- Makefile.build
This change adds a step to the building of config sync manifests which
produces the subset of manifests for multirepo/oss from the already
generated ACM manifests.
> add OSS manifest staging dir to make target

- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/secret.go
- pkg/reconcilermanager/controllers/secret_test.go
- Make logs a little more consistent
- Add a few missing logs to catch all managed object upserts
- Log namespace/name instead of the raw NamespacedName object
- Use -Ref for ObjectKey and NamespacedName variable names
- Reduce number of pointers to types objects, where possible.
> reconciler-manager cleanup

- Makefile.build
- build/docker-buildenv/Dockerfile
Add a dockerfile that can be used for running the make targets for
building Config Sync artifacts, such as make config-sync-manifest. This
is intended for use in CI to build Config Sync artifacts.
> add dockerfile for docker-buildenv image

- e2e/testcases/oci_sync_test.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/validate/raw/validate/repo_sync_validator.go
- pkg/validate/raw/validate/root_sync_validator.go
- pkg/validate/raw/validate/source_spec_validator.go
- pkg/validate/raw/validate/source_spec_validator_test.go
Add the validation logic for Helm spec, and remove the redundant source spec validation. User will be able to keep
different source specs in one Rsync, and we can use the spec.sourceType field as reference
to ignore the source specs that do not needed.
> Validate the Helm spec when sourceType is helm

- pkg/core/structured.go
- pkg/core/structured_test.go
- pkg/validate/raw/hydrate/declared_field_hydrator.go
- pkg/validate/raw/hydrate/declared_field_hydrator_raw_test.go
When describing a pod, we can have the initContainers field to be null.
This causes an error when we use unstructured.NestedSlice to access this
field as the unstructured library tries to assert nil to []interface{},
but fails, since we can't assert a nil value to be of []interface{}.
This PR ignores empty initContainers since it can still be a valid
resource yaml. It also ignores an empty port field gracefully.
This PR also uses the official conversion library function to convert an
unstructured object to its concrete type for validation purposes.
Tested by running reconciler-manager on a live cluster.
> fix: Handle empty initContainers in pod resources

- Makefile.build
This ensures CS works on clusters with PSP enabled. Although PSP is
deprecated, there might still be users for it until we stop supporting
GKE versions older than 1.25.
> remove exclusion of acm-psp from oss manifest

- e2e/testcases/csr_auth_test.go
- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/helmconfig.go
- pkg/api/configsync/v1beta1/helmconfig.go
- pkg/reconcilermanager/controllers/util.go
This change is to resolve the issue that kubebuilder does not work with
map[string]interface{} and consider unstructured type as Object.
apiextentionsv1.JSON represents any valid JSON value, it supports
map[string]interface{}. After change the field type, user will be able to set the values in this format:
values: {key : val}
> Change helm.values field type from unstructured to JSON

- Makefile.release
- scripts/tag-release-candidate.sh
This change separates the creation of RC tagging from the building of
the RC artifacts. This makes the targets a bit for flexible and enables
the use of tag-based triggers to run the RC build step.
A prompt is added to the RC tagging target with the intent of making it
an interactive step.
> rc tag creation separate from rc build

- e2e/nomostest/config-sync.go
- e2e/nomostest/git-server.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/webhook.go
- manifests/test-resources/resourcegroup-manifest.yaml
- pkg/api/configmanagement/register.go
- pkg/bugreport/bugreport.go
- pkg/bugreport/constants.go
- pkg/reconcilermanager/controllers/deployment_conditions.go
- pkg/reconcilermanager/controllers/deployment_conditions_test.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
The resource-group-controller's default memory request is increased from 50Mi to 200Mi to address the crashlooping issue on the autopilot cluster.
> Increase the test resource-group-controller memory request to 200Mi

- pkg/kinds/kinds.go
- pkg/testing/fake/objects.go
- pkg/util/autopilot.go
- pkg/util/autopilot_test.go
We use the policycontrollerv2.config.common-webhooks.networking.gke.io webhook to detect if a cluster is an Autopilot cluster. However, the webhook was renamed to gkepolicy.config.common-webhooks.networking.gke.io`.
This commit updates the function to return true if the new webhook is found.
b/243938243
> Update the IsGKEAutopilotCluster to understand the new autopilot webhook

- cmd/reconciler-manager/main.go
- e2e/testcases/reconciler_manager_test.go
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
Load --allow-vertical-scale flag from reconcilerManager deployment, keep current container resources when flag is enabled, and add e2e test.
--allow-vertical-scale flag is declared in the reconcilerManager deployment when allowVerticalScale is set to true in the ConfigManagement API. When the flag is enabled, the reconciler should load the flag, and copy over all containers' resources from the current reconciler Deployment to the declared manifest, so that the discrepancy will not cause any Deployment update. That implies any resource override applied to the declared Deployment will be ignored. Changes to anything other than the resource will not be maintained and will be reverted back
The e2e test will simulate the scenario by adding the --allow-vertical-scale flag to the …
> Load allow vertical scale flag in reconciler manager

- cmd/nomoserrors/examples/examples.go
- e2e/testcases/acme_test.go
- e2e/testdata/object-in-cms-namespace/cmsconfigmap.yaml
- e2e/testdata/object-in-cms-namespace/cmsrole.yaml
- pkg/importer/analyzer/validation/nonhierarchical/illegal_namespace_validator.go
- pkg/validate/raw/validate/namespace_validator.go
- pkg/validate/raw/validate/namespace_validator_test.go
To vertically scale ACM pods, we want to manage autoscaler resource in the root repository. Right now, only RootSync object can be declared in the config-management-namespace, therefore we want to loosen the restriction in Config Sync by removing ObjectInIllegalNamespace error. This will allow user to sync other resource type in config-management-namespace using unstructured repo config
> Allow other declared resources in the config-management-system namespace

- docs/custom-metric-filter.md
This doc is a playbook for
- adjusting the custom metrics to be exported to backends, especially Cloud Monitoring
- disabling custom monitoring
> Create a playbook for tuning custom monitoring

- pkg/validate/raw/validate/source_spec_validator.go
Add "helm" to error message: must specify spec.sourceType to be one of
"git", "oci", "helm"
> Fix InvalidSourceType error message

- pkg/importer/differ/differ.go
- pkg/parse/namespace.go
- pkg/parse/root.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/syncer/crd/reconcile.go
- pkg/syncer/reconcile/apply.go
- pkg/syncer/reconcile/repostatus.go
- pkg/syncer/reconcile/util.go
- pkg/syncer/sync/reconciler.go
- pkg/util/compare/compare.go
- pkg/util/compare/comparer.go
- pkg/util/compare/comparer_test.go
- pkg/util/repo/client.go
- pkg/util/watch/manager.go
- This avoids generation & resourceVersion bloat, which can cause
unnecessary watch updates and ectd memory leaks.
`equality.Semantic.DeepEqual` is used by `CreateOrUpdate` in controller-runtime:  
https://github.com/kubernetes-sigs/controller-runtime/blob/v0.12.3/pkg/controller/controllerutil/controllerutil.go#L215
> Avoid object updates if semantically equal

- e2e/nomostest/gitproviders/gitlab.go
The gitlab CI tests are failing because of `remote: GitLab: You are not allowed to force push code to a protected branch on this project.`
This commit creates the testing git projects to a specific gitlab group (configsync), which defines no protected branch.
> Create the testing git projects to a specific gitlab group

- e2e/nomostest/nt.go
- e2e/testcases/custom_resource_definitions_test.go
- e2e/testcases/custom_resources_test.go
- e2e/testcases/multiversion_test.go
- e2e/testcases/resource_conditions_test.go
TestResourceConditionAnnotations failed on clusters with K8s 1.22+ because the v1beta1 API for the RBAC resources are deprecated and the k8s-api-server only returns one copy of the RBAC resource.
b/240334486
> Fix the test failure for TestResourceConditionAnnotations

- README.md
- docs/contributing.md
Update the contributor guide with better guidance for anyone who wants to contribute to Config Sync.
Fixes: https://github.com/GoogleContainerTools/kpt-config-sync/issues/18
> Update contributor guide

- e2e/testcases/resource_conditions_test.go
Use semantic equality to allow the empty array to equal a nil array
> Fix TestResourceConditionAnnotations

- pkg/importer/differ/differ.go
- pkg/syncer/client/client.go
- pkg/syncer/client/client_test.go
- pkg/syncer/reconcile/apply.go
- pkg/syncer/reconcile/namespaceconfig.go
- pkg/syncer/reconcile/util.go
- pkg/syncer/sync/reconciler.go
- pkg/util/repo/client.go
- Rename Update to Apply to reflect existing client-side apply behavior
- Add an Update method to update directly (and send metrics) when the Get has already been performed
- Fix "failed to create object" error in the mono-repo finalizer by switching from Upsert to Apply
- Remove unused Upsert function
- Add additional equivelency checks to avoid updates when using Apply and ApplyStatus
> Fix mono-repo "failed to create object" error

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/sync.go
- e2e/testcases/namespaces_test.go
- e2e/testcases/resource_conditions_test.go
- pkg/testing/fake/repo.go
- pkg/util/repo/default.go
This should prevent mono-repo test suite timeout when a test wedges the syncer, causing all subsequent tests to fail.
> Fail test during reset if sync still in-progress

- e2e/nomostest/ntopts/multi_repo.go
- e2e/testcases/resource_group_controller_test.go
The ResourceGroup option is not used anywhere. The option is supposed to be used to determine whether to install the resource-group-controller. However, in the installation function, it uses nt.MultiRepo to determine whether to install the resource-group-controller:
https://github.com/GoogleContainerTools/kpt-config-sync/blob/v1.13.0-rc.7/e2e/nomostest/config-sync.go#L184.
> Remove the ResourceGroup option that is not used

- e2e/testdata/reconciler-manager-configmap-updated.yaml
- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
When we upgraded to otel v0.58, we introduced a regression in the metrics being exported with a `generic_node` type instead of `k8s_pod`. This happened as our codebase uses opencensus semantic conventions for resource attributes instead of opentelemetry semantic conventions.
This workaround runs our collector with a flag to disable the newer exporter logic until we can upgrade our codebase to use opentelemetry conventions.
See https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/breaking-changes.md for more details about the rewritten exporter.
> Use opencensus based exporter for monitoring

- pkg/parse/root_test.go
- pkg/syncer/syncertest/fake/discovery_client.go
This test is intended to validate the fix in https://github.com/GoogleContainerTools/kpt-config-sync/pull/28.
When discovery call fails due to any possible reason and some objects in the inventory are with scope Unknown, the parser previously would ignore the error and skip sending these objects to the applier, causing the objects to be pruned in later process. 
The above mentioned fix makes the discovery failure a blocking error so no object with scope Unknown will be skipped, as error will be early returned instead of moving on.
> Add unit test for parseAndUpdate

- scripts/tag-promotion.sh
- scripts/tag-release-candidate.sh
There is no longer a use case for using a github access token with the tagging scripts/targets, so the functionality is removed.
> remove GH_TOKEN functionality from tagging scripts

- e2e/testcases/helm_sync_test.go
- pkg/helm/helm.go
- pkg/reconcilermanager/controllers/util.go
helm.values field type used to be map[string]interface{}. Looping through the map to generate a env variable leads to a inconsistent env variable issue. Since we change the helm.values field type to JSON already, we can pass it through env variable directly, and process it later in helm-sync.
> Fix helm.values field to support mutiple values

- e2e/testcases/helm_sync_test.go
- pkg/helm/helm.go
- pkg/reconcilermanager/controllers/util.go
helm.values field type used to be map[string]interface{}. Looping through the map to generate a env variable leads to a inconsistent env variable issue. Since we change the helm.values field type to JSON already, we can pass it through env variable directly, and process it later in helm-sync.
> Fix helm.values field to support mutiple values (#109)

- e2e/nomostest/metrics/parse.go
- e2e/nomostest/metrics/validate.go
- e2e/nomostest/nt.go
- e2e/testcases/override_resource_limits_test.go
- pkg/kmetrics/record.go
- pkg/metrics/record.go
- Enable recorded metric logging with -v=5 (component binary)
- Enable received metric logging with --debug (nomostest)
- Fix existing Tag printout in test validation failure by using a custom Tag struct which is serializable with fmt %v (no private fields)
> Log metrics recorded and received for debugging

- docs/metric-resource-attributes.md
- manifests/otel-agent-cm.yaml
- manifests/test-resources/resourcegroup-manifest.yaml
- Enable the GCP resource processor on the opentelemetry agent. This adds the following resource attributes:
* cloud.provider
* cloud.platform
* cloud.account.id
* cloud.region OR cloud.availability_zone
* host.id
* host.name (when not using workload identity)
- When then GCE metadata server is unavailable, the resource processor exits without modifying the resource attributes. So it's safe to enable globally.
- Enabling the resource processor on the agent sidecars allows for more accurate attributes, like the host.id of the node the reconciler is on, instead of the host.id of the otel-collector.
For more details, see the docs:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor
> Add GCP+GKE metric attributes

- pkg/declared/resources.go
- pkg/parse/updater.go
- This fixes an edge case where declared_resources was zero when more than zero resources were declared.
- The reason this wasn't caught before is because TestDontDeleteAllNamespaces expects zero resources when it tests deletion of all namespaces.
- This unblocks adding a new cluster-scoped safety resource in a future change.
> Send correct number of declared_resources

- e2e/nomostest/metrics/validate.go
- e2e/nomostest/nt.go
- pkg/importer/filesystem/reconcile.go
- pkg/metrics/record.go
- pkg/metrics/tagkeys.go
- pkg/metrics/views.go
- pkg/parse/namespace.go
- pkg/parse/root.go
- pkg/syncer/metrics/metrics.go
- Add `"status"` tag to `last_sync_timestamp` so it can be used to check whether a sync had either source or sync errors. Because, `last_apply_timestamp` only represents sync errors, not source errors.
- Change e2e metrics validation to wait for `last_sync_timestamp`, instead of `last_apply_timestamp`. This more correctly waits until sync is complete, not just apply, and has an error status that includes source errors.
- Add constants for status metric tag values.
- These changes should reduce flakey errors.
Depends onhttps://github.com/GoogleContainerTools/kpt-config-sync/pull/115
> Validate metrics after Sync, not just Apply

- Makefile.e2e
Currently, the presubmit jobs may fail due to CPU/mem resource shortage. This change reduces the parallel setting from 18 to 15 to see whether it helps.
> Reduce the parallel setting of presubmit mono/multi jobs to 15

- cmd/nomos/migrate/migrate.go
- cmd/reconciler-manager/main.go
- e2e/nomostest/config-sync.go
- e2e/testcases/namespace_repo_test.go
- e2e/testdata/reconciler-manager-configmap-updated.yaml
- manifests/otel-agent-cm.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- pkg/api/configsync/register.go
- pkg/applier/kpt_applier.go
- pkg/applier/utils_test.go
- pkg/diff/precedence_test.go
- pkg/kinds/kinds.go
- pkg/kmetrics/register.go
- pkg/metadata/labels.go
- pkg/metrics/register.go
- pkg/metrics/tagkeys.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- The following resource attributes were added to all metrics from the reconciler and reconciler-manager:
- k8s.pod.name
- k8s.pod.namespace
- k8s.pod.uid
- k8s.pod.ip
- k8s.node.name
- k8s.deployment.name
- The following resource attributes were added to all metrics from the reconciler:
- configsync.sync.kind
- configsync.sync.name
- configsync.sync.namespace
- The above resource attributes are injected via the OTEL_RESOURCE_ATTRIBUTES env var in the Deployment yaml for the otel-agent container.
- The following labels are used to inject resource attribute values:
- configsync.gke.io/deployment-name
- configsync.gke.io/sync-kind
- configsync.gke.io/sync-name
- configsync.gke.io/sync-namespace
- The following env vars are use to inject values from the k8s downward API into resource …
> Add k8s resource attributes to metrics

- e2e/nomostest/config-sync.go
- e2e/nomostest/git.go
- e2e/nomostest/metrics/validate.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/multi_repo.go
- e2e/testcases/acme_test.go
- e2e/testcases/cluster_resources_test.go
- e2e/testcases/cluster_selectors_test.go
- e2e/testcases/custom_resource_definitions_test.go
- e2e/testcases/custom_resources_test.go
- e2e/testcases/gatekeeper_test.go
- e2e/testcases/kptfile_test.go
- e2e/testcases/lifecycle_directives_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/multiversion_test.go
- e2e/testcases/namespace_repo_test.go
- e2e/testcases/namespaces_test.go
- e2e/testcases/preserve_fields_test.go
- e2e/testcases/root_sync_test.go
- manifests/templates/otel-collector.yaml
- pkg/metrics/otel.go
- pkg/metrics/tagkeys.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
Fix metrics validation
- Enable resource_to_telemetry_conversion on the otel-collector.
- Use the k8s.deployment.name resource attribute to filter and
validate metrics from specific reconcilers.
- Add a safety ClusterRole to e2e tests.
This cluster-scoped resource is required to allow deletion of
all other cluster-scoped resources in mono-repo mode.
This allows for generic cleanup code, rather than needing each
test to work around the deletion validation code.
- Rewrite e2e validation of the declared_resources metric to
dynamically account for default resources, whether the test is
using centralized or delegated setup.
- Fix a race condition in the TestAddUpdateRemoveClusterScopedCRDV1
tests when deleting both the CRD and CR in the same commit.
- Shorten the metrics wait timeout to 1m …
> Fix metrics validation

- Makefile.build
This includes both the Config Management namespaces and the ResourceGroup manifests, which are needed for OSS installation.
https://github.com/GoogleContainerTools/kpt-config-sync/issues/127
> add test-resources to OSS manifest

- e2e/testcases/custom_resource_definitions_test.go
The new DefaultRootSyncObjectCount should solve the flakiness that caused this check to be disabled.
> Re-enable a disabled metrics validation test

- pkg/configsync/git-importer.go
- pkg/hydrate/controller.go
- pkg/importer/filesystem/controller.go
- pkg/parse/run.go
- pkg/policycontroller/reconciler.go
- pkg/reconciler/reconciler.go
Tickers can cause memory leaks and continuous execution, when execution takes longer than the tick duration. This is especially problematic in e2e where the timers are set very short and at scale when the sync can take longer than the retry/polling/resync period.
Timers with resets function more as a delay between executions, which is preferable, rather than something tied to a wall-clock.
> Use timers instead of tickers

- e2e/testinfra/terraform/Makefile
- e2e/testinfra/terraform/README.md
- e2e/testinfra/terraform/common/service_accounts.tf
- e2e/testinfra/terraform/common/source_repositories.tf
- e2e/testinfra/terraform/dev/clusters.tf
- e2e/testinfra/terraform/dev/variables.tf
- e2e/testinfra/terraform/environments.tf
- e2e/testinfra/terraform/main.tf
- e2e/testinfra/terraform/modules/e2ecluster/e2ecluster.tf
- e2e/testinfra/terraform/modules/e2ecluster/variables.tf
- e2e/testinfra/terraform/modules/e2ecluster_autopilot/e2ecluster.tf
- e2e/testinfra/terraform/modules/e2ecluster_autopilot/variables.tf
- e2e/testinfra/terraform/modules/service_account/service_account.tf
- e2e/testinfra/terraform/modules/service_account/variables.tf
- e2e/testinfra/terraform/modules/testgroup/networks.tf
- e2e/testinfra/terraform/modules/testgroup/testgroup.tf
- e2e/testinfra/terraform/modules/testgroup/variables.tf
- e2e/testinfra/terraform/modules/testgroup_autopilot/networks.tf
- e2e/testinfra/terraform/modules/testgroup_autopilot/testgroup.tf
- e2e/testinfra/terraform/modules/testgroup_autopilot/variables.tf
- e2e/testinfra/terraform/prow/networks.tf
- e2e/testinfra/terraform/prow/prow_clusters.tf
- e2e/testinfra/terraform/variables.tf
This terraform config is intended to automate the provisioning of test infra resources needed to run the e2e tests. It can be used for the use case of our prow periodic jobs as well as development workflows.
> add terraform config for dev/ci clusters

- e2e/testinfra/terraform/common/registries.tf
- e2e/testinfra/terraform/common/services.tf
- e2e/testinfra/terraform/prow/registries.tf
- e2e/testinfra/terraform/prow/services.tf
This updates the terraform config to create the docker registristries used by the e2e tests. Also enable the APIs which are required for the e2e tests.
> add registries and enable APIs in terraform

- e2e/testcases/resource_conditions_test.go
The Constraint and ConstraintTemplate CRD have been updated to use the v1 apiversion. The test can run on clusters with k8s 1.22+.
> Re-enable the resource condition tests for mono-repo mode

- Makefile.build
This includes both the Config Management namespaces and the ResourceGroup manifests, which are needed for OSS installation.
> add test-resources to OSS manifest (#128)

- e2e/testcases/helm_sync_test.go
- manifests/rootsync-crd.yaml
- pkg/api/configsync/register.go
- pkg/api/configsync/v1alpha1/helmconfig.go
- pkg/api/configsync/v1beta1/helmconfig.go
- pkg/helm/helm.go
Change the helm.namespace default value from "config-management-system"
to "default" to be consistent with other tools: Helm, Kustomize etc.
> Change the RootSync helm.namespace field default value

- Makefile
We currently pass in a custom USER variable to uniquely identify the image tags for each prow job. This switches the make target functionality to check for BUILD_ID from the environment and use that instead if present.
> use BUILD_ID as unique identifier for prow jobs

- e2e/testcases/helm_sync_test.go
Add more e2e tests to verify `gcenode` and `gcpserviceaccount` auth types work with Artifact Registry.
> Add e2e tests for Helm support (#93)

- cmd/reconciler/main.go
- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/resource_override.go
- pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
- pkg/api/configsync/v1beta1/resource_override.go
- pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
- pkg/configsync/git-importer.go
- pkg/reconciler/reconciler.go
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/util.go
We have a few hundreds of CRDs in our clusters, and are seeing Config Sync reconciliation fail with API Server timeouts due to the client-side timeout parameter being too aggressive.
This makes the client-side timeout for API server requests configurable under `.spec.override` (next to things like `gitSyncDepth` and `statusMode`; if you'd like it to be somewhere else, feel free to recommend something and I'll adjust the PR). I tried to mimic patterns already in use for other parameters, both in implementation and tests (but oh, god, does this test suite need some work...!) so I hope it looks OK.
I [added](https://github.com/GoogleContainerTools/kpt-config-sync/pull/141/files#diff-96d9758339603eab1bf5deb9d64abf4acb751b8474cd85e2cd4d790a76514291R2384-R2480) two [new …
> Make client-side timeout when talking to API Server configurable

- pkg/validate/raw/validate/source_spec_validator.go
Add "helm" to error message: must specify spec.sourceType to be one of "git", "oci", "helm"
> Fix InvalidSourceType error message (#76)

- e2e/testcases/helm_sync_test.go
The code snippet was not removed by cherrypicking from #93 in #144. Remove it to fix multi-repo test failure on v1.13 branch.
> Fix cherrypick discrepancy in #93 and #144

- e2e/testcases/helm_sync_test.go
- pkg/helm/helm.go
Reverts GoogleContainerTools/kpt-config-sync#153 
This change does not work for all cases, revert it for now, need a generic solution to support all special value cases.
> Revert "Support passing number only values as string directly through helm.va…"

- e2e/nomostest/nt.go
- e2e/testcases/custom_resource_definitions_test.go
- e2e/testcases/custom_resources_test.go
- e2e/testcases/multiversion_test.go
- e2e/testcases/resource_conditions_test.go
TestResourceConditionAnnotations failed on clusters with K8s 1.22+ because the v1beta1 API for the RBAC resources are deprecated and the k8s-api-server only returns one copy of the RBAC resource.
b/240334486
> Fix the test failure for TestResourceConditionAnnotations (#88)

- e2e/nomostest/metrics/validate.go
- e2e/nomostest/nt.go
- e2e/testcases/cluster_selectors_test.go
- e2e/testcases/custom_resource_definitions_test.go
- e2e/testcases/custom_resources_test.go
- e2e/testcases/invalid_git_branch_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/namespaces_test.go
- e2e/testcases/root_sync_test.go
- pkg/metrics/record.go
- pkg/metrics/tagkeys.go
- pkg/parse/namespace.go
- pkg/parse/root.go
- Fix some failing tests that were erroring because their expectations
were assuming all the metrics for the same deployment would be
reported with the same tags. Now they filter by pod names instead of
delpoyment name, using the latest reconciler pod for that deployment.
- Add debug logging for SyncMetricOptions
- Fix status updates that were being skipped too agressively.
They now record metrics and status if the status has never been
updated before.
- Remove unnecessary metrics diff on update
- Add NONE value for commit tag in last_sync_timestamp and
last_apply_timestamp metrics, to work around a bug in the
otel-collector which causes invalid output by the Prometheus exporter.
Without this fix, the commit value gets parsed to the status value, and the status
tag is ignored as invalid. …
> Filter some metrics by pod name for testing

- e2e/testcases/resource_conditions_test.go
This is to stabilize one flaky mono-repo test.
> Increase the wait timeout and add retries to a mono-repo test

- cmd/monitor/main.go
- cmd/nomos/parse/parse.go
- e2e/nomostest/new.go
- pkg/client/restconfig/restconfig.go
- pkg/configsync/git-importer.go
https://github.com/GoogleContainerTools/kpt-config-sync/commit/732f94ea702a9a2f97335f0000306f4e17b363ee disabled client-side throttling, which then caused the monorepo CI jobs to start becoming flaky and then constantly failing.
This commit forces to enable the client-side throttling for mono-repo only. Compared with 1.12.x releases, the client-side throttling QPS was
increased from 20 (burst: 40) to 30 (burst: 60).
> Force to enable client-side throttling for mono-repo mode

- cmd/monitor/main.go
- cmd/nomos/parse/parse.go
- e2e/nomostest/new.go
- pkg/client/restconfig/restconfig.go
- pkg/configsync/git-importer.go
https://github.com/GoogleContainerTools/kpt-config-sync/commit/732f94ea702a9a2f97335f0000306f4e17b363ee disabled client-side throttling, which then caused the monorepo CI jobs to start becoming flaky and then constantly failing.
This commit forces to enable the client-side throttling for mono-repo only. Compared with 1.12.x releases, the client-side throttling QPS was
increased from 20 (burst: 40) to 30 (burst: 60).
> Force to enable client-side throttling for mono-repo mode (#169)

- e2e/nomostest/config-sync.go
- e2e/nomostest/git-server.go
- e2e/nomostest/nt.go
PSP is removed as of k8s 1.25, causing tests to fail when they try to apply these PSP resources on 1.25 clusters. This change intends to make all PSP-related resources conditionally created based on whether the cluster has PSP enabled. We currently perform this check by checking whether psp is in the cluster name.
> only create e2e psp resources on psp clusters

- e2e/testcases/custom_resource_definitions_test.go
- e2e/testcases/multi_sync_test.go
The root-sync being synced doesn't mean the resource is reconciled. Hence, this commit adds a retry block around the validation.
One example test failure:
https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/pr-logs/pull/GoogleContainerTools_kpt-config-sync/175/kpt-config-sync-presubmit-e2e-mono-repo-test-group2/1577083658446049280.
> Retry the validation for the large CRD test

- scripts/e2e-kind.sh
the artifacts env var was not being passed into the container, causing some places which look for the env var to not produce artifacts at the correct location. For example, the kind cluster logs are emitted to the artifacts dir on failure.
> pass ARTIFACTS env var into kind container

- cmd/monitor/main.go
- cmd/nomos/parse/parse.go
- e2e/nomostest/new.go
- pkg/client/restconfig/restconfig.go
- pkg/configsync/git-importer.go
Related changes:
- https://github.com/GoogleContainerTools/kpt-config-sync/commit/732f94ea702a9a2f97335f0000306f4e17b363ee
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/169
> Always enable client-side throttling with QPS 20 for mono-repo mode

- cmd/monitor/main.go
- cmd/nomos/parse/parse.go
- e2e/nomostest/new.go
- pkg/client/restconfig/restconfig.go
- pkg/configsync/git-importer.go
Related changes:
- https://github.com/GoogleContainerTools/kpt-config-sync/commit/732f94ea702a9a2f97335f0000306f4e17b363ee https://github.com/GoogleContainerTools/kpt-config-sync/pull/169
> Always enable client-side throttling with QPS 20 for mono-repo mode (#180)

- e2e/testcases/gatekeeper_test.go
- This should fix a flakey bug for mono-repo in TestConstraintTemplateAndConstraintInSameCommit
> Change test expectation to match behavior

- Makefile.build
- docs/installation.md
Fixes: https://github.com/GoogleContainerTools/kpt-config-sync/issues/167
> separate acm-psp manifest from OSS config-sync-manifest

- e2e/nomostest/sync.go
- pkg/util/log/stringer.go
- Add a json stringer to lazily format json in logs and errors.
- Use the json stringer in the e2e sync test errors to make it easier to debug expectation failures by including more context in the error.
> Print Repo/RepoSync/RootSync json on e2e error

- Makefile.e2e.ci
- build/test-e2e-go/e2e.sh
This change makes it so that prober creds are used by default, but can be overridden with an empty string at runtime to not use them. This is intended to enable a transition to workload identity for the prow jobs.
> make prober creds optional in go-gke-ci target

- cmd/helm-sync/main.go
- e2e/nomostest/predicates.go
- e2e/testcases/csr_auth_test.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/hydration_test.go
- e2e/testdata/root-sync-helm-chart-cr.yaml
- pkg/helm/helm.go
Instead of using helm template option --set, using option --values to set values.
After this change, users do not need to flatten the nested fields to set values, and will be able to pass special string values like "1234", "true" directly through helm.values
Add test cases to test helm.values field with different types of values.
> Support passing different types of values directly through helm.values

- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
Without this fix, individual subjects were never removed when their RootSync was deleted. Cleanup only worked when all RootSyncs were deleted.
> Fix bug in RootSync ClusterRoleBinding cleanup

- e2e/testcases/csr_auth_test.go
The lingering membership may be created in the same test project, or cross project. We need to delete them from both projects.
> Clean up the membership for cross-project as well

- e2e/nomostest/config-sync.go
- e2e/nomostest/new.go
- e2e/testcases/invalid_git_branch_test.go
- e2e/testcases/root_sync_test.go
This should fix some mono-repo tests that were using a different branch, without affecting the fragile multi-repo cleanup.
Update: I've confirmed this code passes the multi-repo tests that were failing from https://github.com/GoogleContainerTools/kpt-config-sync/pull/187:
```
GCP_PROJECT=stolos-dev GCP_CLUSTER=karlisenberg-cluster-1 GCP_REGION=us-central1 GCP_ZONE="" make E2E_ARGS="--share-test-env --multirepo --test-features=acm-controller,nomos-cli" test-e2e-go-gke-local
```
This PR is a subset of [that PR](https://github.com/GoogleContainerTools/kpt-config-sync/pull/187) with some modifications, excluding the `resetRootRepo` changes that affected multi-repo.
> Fix mono-repo e2e test cleanup to reset the branch

- pkg/declared/value.go
- pkg/parse/root_test.go
- pkg/testing/openapitest/doc.go
- pkg/validate/raw/hydrate/declared_field_hydrator_raw_test.go
- pkg/validate/raw/hydrate/declared_field_hydrator_test.go
- pkg/validate/validate_test.go
- pkg/webhook/fields_test.go
- pkg/webhook/validate_test.go
This previously assumed that there was a kpt.dev parent directory to reach, which adds an unnecessary constraint to dev environment setups. This could probably be improved further, but this makes it so that the file can be found regardless of the parent directory structure.
> make openapi test file not depend on dir structure

- scripts/tag-promotion.sh
- scripts/tag-release-candidate.sh
By default fetch will only fetch HEAD, i.e. main. For patch releases we need to also fetch release branches. This change updates the refspec to fetch all heads from remote.
> fetch all branches in release tagging script

- e2e/testcases/repoless.bats
Reverts GoogleContainerTools/kpt-config-sync#198
Reason: CI tests were continuously failing after this PR was merged. It seems like other failing tests rely on the clean-up code that is removed in PR #198.
> Revert "Fix repoless.bats test cleanup"

- e2e/testinfra/terraform/README.md
- e2e/testinfra/terraform/common/service_accounts.tf
- e2e/testinfra/terraform/common/services.tf
A fresh GCP project may not have all required APIs enabled, leading to certain resources not being available (such as the default compute account).
terraform apply will enable all of the required APIs, but they may not be available in time to create the actual resources. This adds a note to instruct the user that they may need to run apply twice for new projects.
> fix terraform config for fresh projects

- e2e/testcases/basic_test.go
TestNamespaceKubePublicCanBeManaged should be testing for "kube-public" namespace, not "kube-system"
> Fixed test data for TestNamespaceKubePublicCanBeManaged

- cmd/monitor/main.go
- cmd/nomos/flags/flags.go
- cmd/nomos/hydrate/hydrate.go
- cmd/nomos/parse/parse.go
- cmd/nomos/vet/vet.go
- cmd/nomos/vet/vet_impl.go
- e2e/nomostest/client.go
- e2e/nomostest/ntopts/gke.go
- pkg/hydrate/tool_util.go
This follows up on https://github.com/GoogleContainerTools/kpt-config-sync/pull/141#issuecomment-1261588575, in the simplest way possible: I just searched the project for references to `restconfig.DefaultTimeout` and replaced them with something coming form a CLI arg in the simplest way I could.
> Harmonize CLI args

- e2e/testcases/invalid_git_branch_test.go
This commit resets the branch back to main to ensure proper cleanup checks.
Tested locally using a GKE cluster.
> test: Fix cleanup for TestSyncFailureAfterSuccessfulSyncs

- e2e/testcases/lifecycle_directives_test.go
The test `TestPreventDeletionRole` has been flakey on MonoRepo. The test sets up a Role with `client.lifecycle.config.k8s.io/deletion: detach` annotation so it can't be deleted, but when the test is flaky it gets deleted anyway. The other tests in this suite have more validation to the annotation, so I added the annotation validation to this test too. If the test is still failing/flaky, this additional validation should help us isolate the root cause
> Added additional annotation validation to TestPreventDeletionRole

- e2e/testcases/oci_sync_test.go
https://testgrid.k8s.io/googleoss-kpt-config-sync runs all the periodic jobs in the oss-prow-build-kpt-config-sync project. It needs to get an exemption for the public access to the artifact registry and container registry. Before the exemption is approved, the test continues to use the public image in the stolos-dev project.
> Use the public AR/GCR image in the stolos-dev project for testing

- e2e/testcases/gatekeeper_test.go
If the k8sallowedrepos.constraints.gatekeeper.sh CRD exists on the cluster before TestConstraintTemplateAndConstraintInSameCommit starts, the test would fail since it expects UnknownKindError.
> Remove the k8sallowedrepos.constraints.gatekeeper.sh CRD if needed

- e2e/testcases/gatekeeper_test.go
Enable `TestConstraintTemplateAndConstraintInSameCommit` on Autopilot clusters
> Enable TestConstraintTemplateAndConstraintInSameCommit on Autopilot clusters

- cmd/reconciler-manager/main.go
- e2e/testcases/reconciler_manager_test.go
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_base_test.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
VPA isn't updating deployment and update the pods directly. We need to revert allowVerticalScale flag addition and revert the e2e test because they don't resemble how VPA works
https://github.com/GoogleContainerTools/kpt-config-sync/pull/20 was the original PR
> Revert VPA flag and e2e test

- e2e/testcases/custom_resource_definitions_test.go
The flakiness of `TestLargeCRD` was identified while working on https://github.com/GoogleContainerTools/kpt-config-sync/pull/215: 
https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/pr-logs/pull/GoogleContainerTools_kpt-config-sync/215/kpt-config-sync-presubmit-e2e-mono-repo-test-group2/1582107528844546048
> Add retries to mitigate the flakiness

- e2e/testcases/proxy_test.go
- e2e/testdata/proxy/proxy-enabled.yaml
- e2e/testdata/reconciler-manager/rootsync-sample.yaml
The proxy test uses an archived Git repository, which includes a PSP resource whose API was removed from Kubernetes 1.25. This results in a test failure in the rapid channel:
https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/multi-repo-7-standard-rapid-latest/1582080124612775936.
This commit replaces the archived test repo with the official example.
> Update a test git repository

- Makefile
- Makefile.build
- e2e/nomostest/config-sync.go
- manifests/base/kustomization.yaml
- manifests/operator/kustomization.yaml
- manifests/oss/kustomization.yaml
- manifests/templates/admission-webhook.yaml
- manifests/templates/reconciler-manager.yaml
This change adds two new targets for building operator/oss manifests using kustomize. The move to kustomize is intended to improve readability of the manifest scaffolding.
A critical difference of the new build-manifests-operator target is that it only builds manifests for the multirepo mode. This is in preparation of migrating the legacy monorepo code to a separate repository. Since this will be a breaking change, it is implemented as a new make target. The old manifest related targets will be cleaned up and refactored once the monorepo migration is complete.
> add new operator/oss build manifest targets

- Makefile.build
these are deployments for monorepo mode and do not belong in the OSS/multirepo deployment.
This is already handled in the new make targets, but this fixes the old make target in the meantime.
> exclude monitor and git-importer from oss manifest

- e2e/nomostest/new.go
The metrics validation hits timeout on Autopilot clusters, that is because it takes longer for the reconciler Pod to get ready. This commit increases the timeout from 1 minute to 3 minutes.
> Increase the metrics wait timeout for Autopilot cluster

- e2e/nomostest/ntopts/gke.go
https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/multi-repo-1-autopilot-regular/1582649977673355264 failed to get cluster credentials. We need the stdout to understand what happened.
> Log more details for command execution failures

- scripts/build.sh
- scripts/generate-clientset.sh
When using zsh as your default shell the GOPATH variables do not get set.
Example of how to set unset variables in bash is taken from here: 
https://unix.stackexchange.com/questions/594841/how-do-i-assign-a-value-to-a-bash-variable-if-that-variable-is-null-unassigned-f
If we do not have this a zsh user gets the following output:
```
λ make clientgen
+++ Generating clientgen directory
./scripts/generate-clientset.sh
++ dirname ./scripts/generate-clientset.sh
+ NOMOS_ROOT=./scripts/..
./scripts/generate-clientset.sh: line 38: GOPATH: unbound variable
make: *** [Makefile.gen:22: clientgen] Error 1
```
Meanwhile the variables are set:
```
λ set | grep GO 
GOBIN=/usr/local/google/home/mikebz/go/bin
GOPATH=/usr/local/google/home/mikebz/go
```
> GOPATH explicit setting

- e2e/nomostest/config-sync.go
- e2e/nomostest/git.go
- e2e/nomostest/new.go
- e2e/nomostest/ntopts/multi_repo.go
- e2e/nomostest/ntopts/nomos.go
- e2e/testcases/multi_sync_test.go
This feature of the Repository abstraction was designed to allow changing the upstream git repo. It's not clear it it was once used, but it's not used now and if you tried to use it, it probably wouldn't work, because the reset code doesn't handle changing it. So we can just delete it to clean up the code a bit. And if we need it later (unlikely) we can add it back after the reset code is rewritten to be simpler/cleaner.
> Remove unused UpstreamRepoURL from e2e tests

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/gke.go
- e2e/nomostest/ntopts/kind.go
- e2e/nomostest/ntopts/new.go
- e2e/testcases/cli_test.go
Setting environment variables in the test process is not thread safe and can lead to unpredictable behavior. This updates the usage of kubeconfig in the tests to pass the environment variable into the subprocess rather than setting the env var in the test process.
> make test KUBECONFIG thread safe

- e2e/nomostest/config-sync.go
- e2e/nomostest/git-server.go
Some tests failed with a namespace reconciler Pod not found error, e.g. https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/multi-repo-7-standard-stable/1583109762550075392. The root cause is that the ValidateMultiRepoDeployments function validates the Pods after the Deployment objects are ready. When validating the Pods, it checks all Pods in the c-m-s namespace, but when validating the Deployments, it only checks the default root reconciler and other controllers. It is possible that the namespace reconciler Deployment is not available yet, which results in validation error for the corresponding Pod.
This commit adds the namespace reconciler Deployment to the validation list.
It also adds the error to the log when the git-server fails to be installed: …
> Skip validating non-central root reconciler Pods in validateMultiRepoPods

- Makefile
- Makefile.build
- Makefile.reconcilermanager
this ensures that the CRD yaml is up to date as part of presubmit checks. also consolidates the kustomize install make targets and runs addlicense after generating crds.
> run configsync-crds as part of presubmit

- e2e/flags.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/kind.go
- e2e/nomostest/ntopts/new.go
- e2e/nomostest/testing/ntb.go
- e2e/testcases/main_test.go
- e2e/testcases/reconciler_manager_test.go
this change adds support to run kind clusters with a shared test environment. This can be run either sequentially or in parallel. The clusters are created at the beginning of the suite, reused between tests, and deleted at the end of the suite.
This is intended to:
- Speed up the presubmit jobs by reducing time spent creating kind clusters
- Make it easier to run tests with a shared test environment (e.g. reproducing test cleanup issues locally)
- Shift-left the shared environment testing to the presubmits so issues with test cleanup can be found before reaching periodics
It occurred to me while implementing this that we could use the same approach for the GKE testing, where we treat a set of GKE clusters as a shared pool in the tests. This approach could potentially replace the test …
> add support for shared kind clusters

- e2e/nomostest/predicates.go
- e2e/testcases/lifecycle_directives_test.go
Deletion prevention should remove configsync annotations and labels when abandoning an object.
> Add test validation for annotation/label removal

- manifests/templates/git-importer.yaml
- manifests/templates/reconciler-manager-configmap.yaml
High: CVE-2022-43680 for expat/2.2.10-2+deb11u4 (debian) CVSS Score: 7.5
Fixed in 2.2.10-2+deb11u5
b/256594156
> Fix vulnerability found in the git-sync image

- pkg/reposync/conditions.go
- pkg/reposync/conditions_test.go
- pkg/rootsync/conditions.go
- pkg/rootsync/conditions_test.go
- LastTransitionTime should only change if the Status changes.
- LastUpdateTime should only change if one of the condition field values changes.
- This should prevent unnecessary updates. Tho hopefully this behavior is redundant, due to the existing cmp.Equal check using IgnoreTimestampUpdates.
- Ideally this should alow us to stop using cmp.Equal in the future and consistently use semantic.DeepEqual instead.
> Only update condition timestamps on change

- pkg/declared/value.go
Use the example from upstream Kubernetes to avoid copying mutexes.
> fix: Avoid copying mutex/lock for Parser

- Makefile.build
the .output/manifests directory is leftover from the legacy manifest make targets. the new manifest make targets do not create this directory, so we should copy directly from the committed manifest.
> fix: copy acm-psp from correct directory

- Makefile.e2e
- Makefile.e2e.ci
These targets are no longer used by CI and can be removed. More thorough cleanup will be performed by a subsequent change.
> remove monorepo e2e test targets

- e2e/nomostest/metrics/validate.go
- The test is waiting for the reconciler_errors metric to be recorded for both source and sync status, but if there is a source error, the sync status won't be updated and the metric won't be sent for the sync component.
- The only reason this works today is that the async calls to setSyncStatus aren't being deduped. Once they're deduped, this flakiness would become consistent failure. So this fix helps unblock  additional synchronization fixes.
> Fix flakey TestInvalidR*SyncBranchStatus

- e2e/nomostest/wait_for_sync.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/sync_ordering_test.go
When waiting for an error in the RSync status, ignore the Syncing condition, for now.
This is a temporary hack to make tests less flakey until the Syncing condition is fixed to reflect all errors and only the latest commit.
This problem should be fixed by https://github.com/GoogleContainerTools/kpt-config-sync/pull/260, which will be updated to re-add these disabled checks.
> Disable Syncing condition validation on error

- cmd/hydration-controller/main.go
- cmd/reconciler-manager/main.go
- cmd/reconciler/main.go
- pkg/api/configsync/register.go
- pkg/api/configsync/v1alpha1/getters.go
- pkg/api/configsync/v1beta1/getters.go
- pkg/hydrate/controller.go
- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/run.go
- pkg/reconciler/reconciler.go
- Use the -Period suffix consistently. Technically, most of these should be "Delay", because they're a timer between attempts and not the duration of the event itself, but we're already using "period" for most of them. So this at least makes them all consistent without requiring rename of any external facing env vars or command flags.
- Standardize the many duplicate descriptions for duration options, at each layer of the stack.
- Add missing constants to replace hard-coded durations.
- Reafactor existing duration constants to make the names consistent.
> Cleanup time duration options

- e2e/nomostest/config_sync.go
- e2e/testcases/composition_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/oci_sync_test.go
The e2e tests were creating their own version of the ns reconciler cluster role with namespace admin permissions.
This updates the test scaffolding to more closely reflect real scenarios where the CS installation comes with a ClusterRole for the NS reconcilers and the user adds additional roles/bindings.
> use NS reconciler cluster role in e2e tests

- cmd/reconciler/main.go
- pkg/api/configsync/register.go
- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/run.go
- pkg/reconciler/reconciler.go
- This avoids needing to synchronize two goroutines. Instead, the
periodic status updater will only run between parse.run calls.
- Disable sync status updates when a newer commit is being processed.
> Move periodic status updates into the parser

- Makefile.e2e.ci
- build/test-e2e-go/e2e.sh
This change makes it so that prober creds are used by default, but can be overridden with an empty string at runtime to not use them. This is intended to enable a transition to workload identity for the prow jobs.
> make prober creds optional in go-gke-ci target (#157)

- manifests/templates/otel-collector.yaml
- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
Config Sync updated Otel Collector image in v1.12.2 and started having
[incompatibilities](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/breaking-changes.md) in resource label format. The issue was mitigated in 1.13.1 by reverting Otel Collector to legacy mode.
This change
- uses `resourcedetection` processor to correclty map resource labels from OpenCensus to OpenTelemetry
- modified the `googlecloud` exporter to remove `instrumentation_source` and `insrtumentation_version` labels when exporting to Cloud Monarch
- disables metricDescriptor creation in Monarch pipeline so it won't conflict with internal definitions
> Fix Otel Collector resource mapping

- e2e/nomostest/predicates.go
- e2e/testcases/override_resource_limits_test.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
The quantity of CPU resources can be specified in multiple formats: https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/. For example, '1' and '1000m' are semantically equal to each other.
There is a bug in ACM 1.11.0 - ACM 1.13.1, which causes a root|ns-reconciler Deployment to be updated constantly if the CPU resource request/limit are in the format of '1000m' instead of '1'. The issue is fixed in
https://github.com/GoogleContainerTools/kpt-config-sync/pull/78.
This PR add e2e and unit test coverage for this.
> Add e2e and unit test coverage to make sure a root|ns-reconciler Deployment is not updated unnecessarily

- pkg/metrics/views.go
Currently, the bounds for the histogram distribution is `[]float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10}`, and all the timeseries whose values are greater than 10 are put into the same bucket, [10, +Infinite]. This PR uses the bounds `[]float64{1, 5, 10, 30, 60, 300, 600, 1200, 1800, 3600, 5400}` to better align with the common use cases.
> Enhance the `parser_duration_seconds` and `apply_duration_seconds` metrics

- pkg/applier/clientset.go
- pkg/applier/kpt_applier.go
- pkg/metrics/record.go
- pkg/metrics/tagkeys.go
- pkg/metrics/views.go
- pkg/remediator/reconcile/reconciler.go
- pkg/syncer/reconcile/apply.go
- pkg/syncer/syncertest/fake/applier.go
* add a new label named `controller` to track whether the operation
is from the applier or the remediator
* record this metric when an ApplyFailed/PruneFailed event is
observed on the event channel returned from the cli-utils library.
> Enhance the `apply_operations` metric

- pkg/metrics/record.go
- pkg/parse/namespace.go
- pkg/parse/root.go
Currently, the metric may be sent with an empty commit, since we support asynchronous status updates.  This PR ensures this metric is only recorded when the `commit` label is not empty.
> Enhance the `last_sync_timestamp` metric

- e2e/nomostest/predicates.go
- e2e/testcases/override_resource_limits_test.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
Reverts GoogleContainerTools/kpt-config-sync#289
This breaks some CI jobs.
> Revert "Add e2e and unit test coverage to make sure a root|ns-reconciler Deployment is not updated unnecessarily"

- e2e/testcases/multi_sync_test.go
- e2e/testcases/namespaces_test.go
- pkg/applier/kpt_applier.go
- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/run.go
- pkg/parse/updater.go
- pkg/remediator/remediator.go
- Add a new setSyncStatus that handles:
- Updating the cached sync status in `state`
- Checking the cached sync status to avoid unnecessary updates
- Calling SetSyncStatus with the new sync errors
- Calling reportRootSyncConflicts to update remote RootSyncs, if
they are causing conflicts with the current RSync.
- Rename UpdateConflictManagerStatus -> reportRootSyncConflicts
- Rename parse.setXStatus -> setXStatusFields to allow the name
setSyncStatus to be used by the wrapper that handles state
- Call the new parse.setSyncStatus to make all the updates
consistent, instead of calling parser.SetSyncStatus directly.
- Rename updateSyncStatus -> updateSyncStatusPeriodically to
indicate it handles retrying until cancelled.
- Rename Parser.ApplierErrors() -> SyncErrors() and have it
delegate to …
> Simplify status reporting of sync errors

- cmd/nomos/parse/parse.go
- e2e/nomostest/client.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/gke.go
- e2e/nomostest/ntopts/kind.go
- e2e/nomostest/ntopts/new.go
- e2e/nomostest/watch.go
- pkg/client/restconfig/config.go
- pkg/client/restconfig/restconfig.go
- Split out NewFromConfigFile & NewFromInClusterConfig for direct use
- Add a new WatchConfig and WatchCLient to the e2e test config. **This fixes a bug where the WatchForObject calls would timeout in 5s on GKE.**
- Use NewRestConfig in e2e for both GKE and Kind. **This uses UpdateQPS in the e2e tests for faster API calls.**
- Remove the unused MonoRepo client config (slower QPS)
> Clean up REST client construction

- pkg/applier/kpt_applier.go
- pkg/applier/kpt_applier_test.go
- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/run.go
- pkg/parse/state.go
- pkg/parse/updater.go
- Wrap applier errors in their own mutex
- Move applier.Syncing() to Parser.Syncing() with updater.Updating() doing the heavy lifting. The Syncing condition status should reflect the whole updater, not just the applier.
- Rename applier.Interface -> KptApplier to make room for adding KptDestroyer in the future.
- Rename KptApplier.sync -> applyInner to make room for adding destroyInner in the future.
- Refactor state.syncStatus and Parser.SetSyncStatus to use a new syncStatus struct, which is like the sourceStatus struct but with an added sync bool. This should also be less confusing, because state.syncStatus no longer uses a sourceStatus struct as its value.
- Add a new setSyncStatusErrors func to use in prependRootSyncRemediatorStatus, to avoid needing to to re-construct the initial …
> Improve thread-safety of sync status updates

- build/test-e2e-go/e2e.sh
- docs/development.md
- e2e/flags.go
- e2e/nomostest/client.go
- e2e/nomostest/new.go
- e2e/nomostest/ntopts/gke.go
- e2e/nomostest/ntopts/kind.go
- e2e/nomostest/ntopts/new.go
There was a combination of a required kubeconfig and env vars that needed to be set to run tests on GKE. This change consolidates the setup to only require the env vars to be set. This simplifies some of the scaffolding and interface for running GKE tests.
> ci: consolidate gke cluster args

- cmd/reconciler-manager/main.go
- e2e/testcases/reconciler_manager_test.go
- go.mod
- manifests/templates/reconciler-manager-configmap.yaml
- pkg/kinds/resources.go
- pkg/reconcilermanager/controllers/jsonpath.go
- pkg/reconcilermanager/controllers/jsonpath_test.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_base_test.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/syncer/syncertest/fake/dynamic_client.go
Create an allowlist in reconciler manager and add the fields that we
allow others to modify to the allowlist.
When compare the current reconciler deployment with the declared
reconciler deployment, ignore the differences of the fields in the
allowlist.
Use Sever Side Apply to only manage the fields defined in
reconciler-manager-configmap to prevent the reconciler manager from fighting with other controllers 
on the fields we do not define
> Resolve the fight between reconciler manager and Autopilot

- e2e/testinfra/terraform/prow/prow_clusters.tf
These clusters are no longer in use since the mono repo jobs have been deleted
> ci: remove mono repo clusters

- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/permissions.go
- pkg/reconcilermanager/controllers/permissions_test.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- The old code for subject deletion used a List of RSyncs to decide what all the subjects should be in the [Cluster]RoleBinding for the reconciler ServiceAccount. This aggresively removes subjects when their RSync is deleted. However, this caused the upsert to remove subjects when it only needed to add subjects, which can cause reconcilers to be de-authorized before they're deleted.
- This change splits the update code into add and remove code. So the subject will only ever be removed if the RSync is already NotFound, and only by the Reconcile loop specific to that RSync.
- This should unblock the Finalizer to delete managed resources even if the deletion timestamp is already set on the RSync (which is the only time the finalizer runs anyway).
> Fix over-agressive role binding subject deletion

- Makefile.build
- Makefile.e2e.ci
- Makefile.oss.prow
- scripts/e2e-kind.sh
- buildx is demonstratably faster than the current build behavior, and is even faster than just seperating out the multi-stage builds into thier own Dockerfiles.
> Switch to docker buildx for faster builds

- build/test-e2e-go/e2e.sh
- build/test-e2e-go/gke/Dockerfile
- build/test-e2e-go/kind/Dockerfile
go-junit-report v2.0.0 added support for -subtest-mode flag to exclude or ignore results of subtest parent tests:
https://g3doc.corp.google.com/third_party/golang/github_com/jstemmer/go_junit_report/v/v2/README.md#changelog.
> Update go-junt-report version and config

- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
Config Sync SLIs:
https://cloud.google.com/anthos-config-management/docs/how-to/config-sync-slis
> Export SLI-related metrics to Google Cloud Monitoring

- Makefile.build
- build/test-e2e-go/e2e.sh
- build/test-e2e-go/gke/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- cmd/junit-report/main.go
- cmd/junit-report/resetfailure/reset_failure.go
- cmd/junit-report/resetfailure/reset_failure_test.go
- e2e/testdata/junit-report-updated.xml
- e2e/testdata/junit-report.xml
- go.mod
- go.sum
- scripts/build-junitreport-cli.sh
- scripts/lint-license-headers.sh
- vendor/github.com/jstemmer/go-junit-report/v2/LICENSE
- vendor/github.com/jstemmer/go-junit-report/v2/gtr/gtr.go
- vendor/github.com/jstemmer/go-junit-report/v2/junit/junit.go
- vendor/modules.txt
The testgrid failed to autocloase the bug because the testcases.Failure entry wasn't removed from a successful run.
This commit postprocesses the junit report to ensure the bug can be autoclosed immediately.
> Postprocess the junit report by appending a testcases.Failure

- e2e/nomostest/config_sync.go
- pkg/applier/applier.go
- pkg/applier/utils.go
- pkg/applier/utils_test.go
- Make RepoSync depend on the [Cluster]RoleBinding & ClusterRole that grant the reconciler permissions. This ensures the reconciler has correct permissions until fully exited.
- No need to do the same for RootSync, because the RootSync permissions are not managed by setupCentralizedControl.
> Add dependencies to e2e CentralizedControl setup

- pkg/reconcilermanager/controllers/otel_controller_test.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/secret_test.go
- pkg/reconcilermanager/controllers/validate_secret_test.go
- pkg/remediator/reconcile/reconciler_test.go
- pkg/remediator/reconcile/worker_test.go
- pkg/syncer/syncertest/fake/client.go
- pkg/syncer/syncertest/fake/dynamic_client.go
- Fix ID lookup to work for typed objects without GVK set. Use the scheme to look up the GVK by struct type.
- Add support for auto-incrementing Generation when the spec changes (technically any change that isn't status or metadata, not just the spec field)
- Fix status update to log the diff correctly
- Fix Update to copy UID, ResourceVersion, and Generation changes back to the input object.
- Make fake.Client.Check ignore Timestamps, so conditions can be easily compared.
- Fix Update to error if the specified UID or ResourceVersion is no longer current.
- Update impacted test expectations.
> Fake client fixes

- pkg/syncer/syncertest/fake/client.go
To align with the real typed client, remove the logic to copy latest values back to input object from the Delete method.
> Modify the Delete method in fake client

- cmd/hydration-controller/main.go
- cmd/reconciler-manager/main.go
- cmd/reconciler/main.go
- manifests/otel-agent-cm.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- pkg/kmetrics/register.go
- pkg/metrics/otel.go
- pkg/metrics/register.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
This change converts the non-k8s-pod typed resource attributes added in [this PR](https://github.com/GoogleContainerTools/kpt-config-sync/pull/114) that are related to Config Sync resources into metric labels.
The resource_filter in googlecloud exporter converts the cloud / k8s /
host related attributes directly into metrics labels in GCM.
Configsync.sync attributes are added with resource processor as metric
labels.
Adding metrics labels at reconciler level requires the shared Otel Collector
to remove them from all metrics before exporting to internal(Monarch) pipeline.
Labels are viewable in `groupby` drop down list and can be selected to
aggregate metrics.http://screen/ZtkKWoEx6bxnyiZ
This change also adds k8s.container.name to Config Sync metrics and Kustomize
wrapper metrics in …
> Add Config Sync resource related attributes to GCM

- e2e/testinfra/terraform/README.md
This reuses the prow terraform config to create an isolated yet similar environment for the release branch CI.
> add docs for release branch infra provisioning

- manifests/templates/reconciler-manager-configmap.yaml
Bumped from https://github.com/kubernetes/git-sync/issues/644
> Update git-sync version to 3.6.2 to clear vulnerabilities

- e2e/nomostest/config_sync.go
- e2e/nomostest/git.go
- e2e/testcases/composition_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/oci_sync_test.go
- Add Repository.Exists(path) to avoid fatal errors from Delete in a Cleanup block
- Fix TestComposition level-1 RootSync file location, so that it's correctly managed by level-0 and can depend on its RoleBinding
- Add nomostest.SetDependencies to simplify annotation construction
- Add TestMultiSyncs_Unstructured_MixedControl Cleanup to handle deletion ordering of dependencies between managed and unmanaged resources
> Add RSync -> RoleBinding dependencies in e2e tests

- e2e/nomostest/git.go
This should prevent some flakey errors in shared environments stemming from format changes between tests.
> Update git repo format when changed by ReInit

- Makefile
This passes the same options for the default value of VERSION and IMAGE_TAG. This ensures that the version the image is tagged with is the same as the version that the nomos binary is built with. This disparity was leading to a test failure when the HEAD commit has a tag.
This change does not alter the release functionality, since the release flows pass in a value rather than relying on the default.
> make default VERSION and IMAGE_TAG the same

- Makefile
This passes the same options for the default value of VERSION and IMAGE_TAG. This ensures that the version the image is tagged with is the same as the version that the nomos binary is built with. This disparity was leading to a test failure when the HEAD commit has a tag.
This change does not alter the release functionality, since the release flows pass in a value rather than relying on the default.
> make default VERSION and IMAGE_TAG the same (#353)

- e2e/testinfra/terraform/common/service_accounts.tf
this enables the compute account to write cloud logs and cloud monitoring metrics
> add log/metric writing roles to compute account

- go.mod
- go.sum
- pkg/util/log/stringer.go
- pkg/util/log/stringer_test.go
- vendor/github.com/kylelemons/godebug/LICENSE
- vendor/github.com/kylelemons/godebug/diff/diff.go
- vendor/modules.txt
- Use the Stringer pattern (like the existing log.AsJSON) to avoid expensive diffing and serializing of objects, for logging with configurable verbosity.
- Use github.com/kylelemons/godebug/diff for diffing, because it doesn't truncate the way cmp.Diff does.
- Use the (configurable) scheme to lookup object GKV from its type and encode YAML, if possible. Fallback to yaml.Marshal for other Go types.
> Add log.AsYAML and log.AsYAMLDiff

- e2e/nomostest/clean.go
- e2e/nomostest/config_sync.go
- e2e/nomostest/wait.go
- e2e/nomostest/watch.go
- e2e/testcases/cluster_selectors_test.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/managed_resources_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/namespaces_test.go
- e2e/testcases/override_reconcile_timeout_test.go
- e2e/testcases/private_cert_secret_test.go
- e2e/testcases/reconciler_finalizer_test.go
- pkg/util/log/stringer.go
- pkg/util/log/stringer_test.go
- Rename WatchForObject to WatchObject
- Update WatchObject to List before Watch, to get the current state,
instead of needing to wait for the next change.
- Update Watch funcs to return an error, instead of calling Error or
Fatal. This makes it possible to use in parallel and in Clean/Reset
where test failure is undesirable.
- Update Watch to use log.AsYAMLDiff, for non-truncating diffs that are
only computed if debug is enabled.
- Replace WaitForNotFound with WatchForNotFound. This makes it faster
and easier to debug (diffs logged for each state change)
- Update log.AsYAMLDiff to work with nil objects
Extracted:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/362
> Replace Wait with Watch (continued)

- e2e/nomostest/clean.go
- e2e/nomostest/config_sync.go
- e2e/nomostest/deletion_propagation.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/reset.go
- e2e/nomostest/watch.go
- e2e/testcases/csr_auth_test.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/kcc_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/oci_sync_test.go
- e2e/testcases/reconciler_finalizer_test.go
- e2e/testcases/root_sync_test.go
- Rewrite test cleanup to use the RSync finalizer to delete all
managed resources by default (for e2e tests only)
- Add deletion propagation helper functions
- Fix TestDeleteRootSyncAndRootSyncV1Alpha1 to handle longer RSync
deletion timeout
- Log elapsed time for Clean and Reset
- Add more logging for test setup and teardown
- Remove test cleanup blocks that are no longer necessary.
Most of these involved resetting the sync config, which is now
being deleted and re-created with the required settings by test
Reset.
Extracted:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/351
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/352
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/354
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/355 …
> Use deletion propagation for e2e test cleanup

- e2e/nomostest/clean.go
- e2e/nomostest/deletion_propagation.go
Just disable deletion-propagation and the finalizer and let namespace deletion handle deleting the objects without ordering requirements.
> Clean RepoSyncs with deletion-propagation enabled

- Makefile.e2e
- Makefile.e2e.ci
Streaming requires test verbosity and one package at a time, but still allows any number of parallel tests.
> Stream e2e log output

- pkg/applier/status.go
- pkg/applier/status_test.go
- pkg/applier/utils.go
The applier logs each status with a new line, which makes it an Error log in cloud logging: http://screen/sk9CAhpH7e4YqxA.
This commit escapes the newline character, so it will be a single line in cloud logging. It can also be easily converted to multiple lines.
> Escape the newline character in the apply/reconcile log

- e2e/testcases/helm_sync_test.go
`TestHelmNamespaceRepo` validates that a namespace reconciler gets a source error when syncing from a public helm chart that includes cluster-scoped resources. The wordpress chart doesn't include any cluster-scoped resources, so this commit updates the chart to pass the validation.
> Update the public helm chart used by the namespace repo

- e2e/testdata/root-sync-helm-chart-cr.yaml
Mariadb persistent storage is enabled by default, which creates a PVC in the namespace. When wordpress is deleted, the PVC is left behind after the test.
This commit updates the chart values to disable mariadb persistent storage.
> Disable MariaDB persistence to avoid leaking PVCs

- build/test-e2e-go/gke/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- e2e/testcases/oci_sync_test.go
Use gcloud to check image digests, instead of the OCI SDK.
- Work with user credentials. No longer require app credentials.
- Automatically authenticate with GCR and GAR.
- Read the digest without pulling the whole image.
- Cache the digest to avoid excessive API calls to the registry.
> Fix OCI e2e tests to run locally

- e2e/testdata/hydration/compiled-json/helm-components/wordpress/service_my-wordpress.json
- e2e/testdata/hydration/compiled/helm-components/wordpress/service_my-wordpress.yaml
- e2e/testdata/hydration/helm-components-remote-values-kustomization.yaml
- e2e/testdata/hydration/helm-components/kustomization.yaml
- e2e/testdata/hydration/krm-function-helm-components-kustomization.yaml
- e2e/testdata/hydration/krm-function-helm-components-remote-values-kustomization.yaml
- e2e/testdata/root-sync-helm-chart-cr.yaml
Due to b/267197563, any Service type of LoadBalancer leaves the GCP resources (firewall rules and target pools) behind. This commit changes the wordpress Service type from the default LoadBalancer to ClusterIP to avoid leading resources.
> Change the wordpress service type to avoid leaking GCP resources

- e2e/testcases/namespace_repo_test.go
This check is flaky in some of our CI jobs. It stands to reason that it may take longer for the RepoSync to be NotFound after deletion due to the introduction of a finalizer. This change increases the timeout accordingly in an attempt to reduce flakiness of the associated tests.
Impacted tests:
- TestDeleteRepoSync_Centralized_AndRepoSyncV1Alpha1
- TestDeleteRepoSync_Delegated_AndRepoSyncV1Alpha1
> increase timeout for not found after deletion

- e2e/nomostest/client.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/new.go
- e2e/nomostest/watch.go
- Switch from using the controller-runtime client to client-go. This allows us access to the following features, which aren't exposed in the controller-runtime client.
- Use ResourceVersion between LIST and WATCH to ensure we don't miss events, especially DELETE events which were causing timeouts when missed.
- Use watch.Until with cache.NewListWatchFromClient to handle retrying watches that failed due to recoverable errors.
- Remove unused NT.WatchConfig. We can just use nt.Config with a custom timeout based on the input to WatchObject.
- Log watch events when watching, to show progress, but only log
the diffs if --debug is enabled.
Fixes b/267941443
> Rewrite WatchObject to use client-go

- e2e/nomostest/predicates.go
- e2e/nomostest/watch.go
- e2e/testcases/cluster_selectors_test.go
- Update all Predicate impls to tollerate nil objects without panic.
- Remove hacky workaround previously used to exit early when the object was not found. Now a normal predicate can handle it.
> Modify Predicates to recieve nil for NotFound

- e2e/nomostest/watch.go
- e2e/testcases/apiservice_test.go
This validation will prevent accidentally specifying a namespace for a cluster-scoped object when using WatchObject in e2e tests.
> Don't allow namespace for cluster-scope watch

- e2e/nomostest/crds.go
- e2e/nomostest/reset.go
- e2e/testcases/composition_test.go
- e2e/testcases/namespace_repo_test.go
Range values are re-used in a for loop.
Use indirection to avoid using the last value for every task.
> Fix usages of TaskGroup in a for loop

- e2e/nomostest/config_sync.go
- Change delegated control to wait the default timeout for reconciler readiness, instead of only 1m
Fixes: b/269473968
> Increase wait timeout for reconciler

- pkg/validate/raw/hydrate/declared_field_hydrator.go
- pkg/validate/raw/hydrate/declared_field_hydrator_raw_test.go
ExternalName Service is not required to have ports specified.
This change explicitly filters this type out, while maintaining
the check for other Services.
> Skip .spec.ports check for ExternalName Service

- cmd/nomos/status/client.go
- e2e/testcases/cli_test.go
From Github issue https://github.com/GoogleContainerTools/kpt-config-sync/issues/226
Currently, nomos status will check for Operator pods and ConfigManagement resource, so it wouldn't work in OSS Config Sync installation.
To get nomos status to work in OSS, the function IsOssInstallation will check for the existence of ConfigManagement object, Operator deployment, and RSync CRD.  If RSync CRD exist but ConfigManagement and Operator doesn't, it indicates an OSS installation
> Enable nomos status command in OSS

- e2e/testcases/cli_test.go
e2e test for nomos status was using git server string as its validation, which can vary in other git providers. Validation is changed to use sync status instead, which value is only SYCED/PENDING/RECONCILING/STALLED
> Change e2e test validation to use sync status output

- e2e/nomostest/new.go
This should allow the retry loop to execute, allowing it to be tested. 
This should also allow the remediator more time to run between applies.
> Increase e2e polling periods

- e2e/nomostest/sync.go
JSON takes less vertical space, but it significantly harder to read/scan quickly. Debug only runs on dev machines so this wont affect CI.
> Print YAML instead of JSON on e2e validation error

- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/filteredwatcher_test.go
- pkg/remediator/watch/listwatch.go
- pkg/remediator/watch/manager.go
- pkg/remediator/watch/manager_test.go
- pkg/remediator/watch/watcher.go
- Fix a bug where drift changes that occurred between apply and watch update would be tolerated until there was another change. Now the drift will be detected as soon as the watch starts.
- Use ListAndWatch, instead of just Watch, to track changes to managed objects for remediation.
> Fix remediator missing events

- pkg/hydrate/controller.go
The status error builder doesn't allow format errors in string form because the type information is lost. It forces to use .Wrap instead.
> Fix a misuse of error builder  (#439) 

- e2e/testcases/managed_resources_test.go
- Use constant for kubectl apply annotation
- Shorten timeout when waiting for remediation
> Minor cleanup of managed resource e2e tests

- cmd/nomos/util/configmanagement.go
- cmd/nomos/version/version.go
- e2e/testcases/cli_test.go
nomos version output in standalone OSS installation will now display the matching version with the image that is used for installation
> Change nomos version output in standalone OSS to match image version

- e2e/testcases/apiservice_test.go
The reconcileTimeout is set to 1 minute for all clusters, but it takes more time for a Deployment to be reconciled on an autopilot cluster. This commit increases the timeout to 2 minutes on autopilot clusters.
> Increase the reconcileTimeout on the Autopilot cluster

- e2e/testcases/apiservice_test.go
The test can now run and pass on Kind clusters. Removing this constraint.
> Remove GKE requirement in API service test

- pkg/hydrate/controller.go
- pkg/hydrate/controller_test.go
- pkg/parse/run.go
- pkg/parse/source.go
- pkg/parse/source_test.go
In a rare condition hydration-controller and parser may proceed with file hydration or listing when git-sync see and updates the commit hash in status, which causes resource mismatch and accidental deletion.
This change blocks the risk by double checking if commit has changed during hydration or listing.
go/cs-race-condition
> Fix race condition (#415)

- e2e/nomostest/wait_for_sync.go
- pkg/applier/applier.go
- pkg/applier/applier_test.go
- pkg/applier/clientset.go
- pkg/syncer/syncertest/fake/client.go
- Rename disableObject to abandonObject, to be consistent with terminology used in the applier.
- Fix supervisor.abandonObject to not adopt all object fields. Use merge-patch, instead of server-side apply. SSA only works if you have the source of truth for all the fields you previously applied. The way it was being used assumed that all fields were owned by configsync.
- Fix supervisor to correctly abandon objects that have their delete or prune skipped with an AnnotationPreventedDeletionError. Previously, the configsync annotations weren't being removed and then the remediator detected it as drift and removed them.
- Use the client.Client in abandonObject. There's no need to use the dynamic.Client, because the client.Client can still populate an Unstructured object, and now that we're …
> Fix abandonment

- e2e/nomostest/metrics/validate.go
- e2e/testcases/managed_resources_test.go
- e2e/testcases/multi_sync_test.go
- pkg/declared/resources.go
- pkg/declared/resources_test.go
- pkg/parse/cache.go
- pkg/parse/root_test.go
- pkg/parse/run.go
- pkg/parse/updater.go
- pkg/remediator/queue/queue.go
- pkg/remediator/queue/queue_test.go
- pkg/remediator/reconcile/worker.go
- pkg/remediator/reconcile/worker_test.go
- pkg/remediator/remediator.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/filteredwatcher_test.go
- pkg/remediator/watch/manager.go
- Fix a bug that might cause objects to be applied or deleted
in the wrong order. This was being caused by the remediator
detecting new changes as drift, when an object was updated
asynchronously, before the applier had a chance to apply
the new intended state.
The reconciler now pauses the remediator before syncing,
and resumes remediating after syncing is successful.
The remediator will continue watching and enqueuing
objects to remediate when changed while paused. This
way no drift is missed while other objects are being applied.
- Fix a bug where sync retries might use unsanitized objects.
This following fields are silently ignored:
- status
- metadata.creationTimestamp
- metadata.finalizers
This helps when applying objects from 3rd party sources
which can't be easily sanitized.
- Fix …
> Pause the remediator while the Applier is running

- e2e/nomostest/git-server.go
- e2e/nomostest/metrics.go
- e2e/nomostest/nt.go
- Return an error, instead of failing the current test, to allow use in test setup and teardown.
- Use GetDeploymentPod to lookup the git-server pod
- Use GetDeploymentPod to lookup the otel-collector pod
- Add checks to ensure the deployment is updated and ready
> Make GetDeploymentPod return an error

- e2e/nomostest/clean.go
Because Clean now deletes multiple resource types in parallel, this sometimes leads to a case where deletion of a CRD causes garbage collection to delete the custom resource objects before the Clean function does, causing either the List or Delete to error. Add checks to tollerate these, since we wanted them to be deleted.
> Fix e2e Clean to handle async deletions

- e2e/nomostest/config_sync.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- Run sharedTestEnv or freshTestEnv, not both.
- Only run test setup once per test
- Only run WatchForAllSyncs once per test setup
- Rename test setup funcs to make them private
> Fix e2e to avoid double setup

- Makefile.build
- e2e/nomostest/new.go
- e2e/nomostest/notification_server.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/new.go
- test/docker/http-notification-webhook/Dockerfile
- test/docker/http-notification-webhook/main.go
This is an in cluster test component that enables simple testing of the notification controller using http/webhooks. It hosts a few http endpoints which record requests from the notification controller and can be queried from the test framework using a port forward.
Creating this PR before the notification controller to provide smaller/incremental code reviews and so that the test scaffolding is available before the notification controller PR is created
> test: add notification server test component

- Makefile.oss.prow
This upgraded base image contains Go version 1.19, which will enable bumping the Go version in kpt-config-sync without breaking CI.
A subsequent change update the Kind prow jobs to use this image.
> ci: bump kubekins-e2e base image

- Makefile
- scripts/license-headers.sh
The linting script was using a different ignore list than the add script, requiring manual fixing after adding the license headers using the script. This ensures both targets use the same ignore definitions.
> use same ignore list for add/lint license headers

- e2e/nomostest/config_sync.go
- e2e/nomostest/git-server.go
- e2e/nomostest/git.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- Move setupTestCase out of SharedTestEnv & FreshTestEnv and into nomostest.New. This avoids setupTestCase being called when shared environments are created by newSharedNT, which was initializing Repos & Syncs redundantly. This should speed up test suites on shared environments and reduce log spam.
- Reset port-forwarding on every test for both git-server and otel-collector. Both now track the pod name, so that they can be called again within the same test if changes are made to the deployments, to re-connect to the new backend pod.
- Make GKE autopilot detection and skipping more consistent between SharedTestEnv and FreshTestEnv. Both now skip before running the reset/cleanup code, which is unnecessary for skipped tests. This should slightly speed up autopilot test suites and reduce log …
> De-dupe test setup on shared environments

- e2e/nomostest/config_sync.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/reset.go
- e2e/testcases/cluster_resources_test.go
- e2e/testcases/cluster_selectors_test.go
- e2e/testcases/custom_resource_definitions_test.go
- e2e/testcases/custom_resources_test.go
- e2e/testcases/kptfile_test.go
- e2e/testcases/lifecycle_directives_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/multiversion_test.go
- e2e/testcases/namespace_repo_test.go
- e2e/testcases/namespaces_test.go
- e2e/testcases/preserve_fields_test.go
- e2e/testcases/root_sync_test.go
- Always validate a standard set of metrics after test setup.
- Record the expected "declared resources" populated by test setup.
This is used when validating standard metrics or as a base-line
when calculating declared resources from a test.
- Clean up setupDelegatedControl and setupCentralizedControl to use
RootRepos/NonRootRepos created by setupTestCase, rather than using
the opts they came from.
- Configure reconcile timeout consistently.
> Fix test setup metric validation 

- e2e/nomostest/clean.go
This is an optimization to simply return if the namespace had no annotations or labels removed. We are also seeing an issue on autopilot where the update is being denied by a webhook, so this should hopefully fix that.
> test: only update ns if it was changed

- e2e/nomostest/nt.go
This scenario occurs during test cleanup - if killing the port-forward process fails because the process is already finished, we can treat this as a non-fatal error.
> do not error test if port forward finished

- pkg/declared/resources.go
- pkg/declared/resources_test.go
- pkg/metrics/otel.go
- pkg/metrics/record.go
- pkg/metrics/views.go
- pkg/parse/updater.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
- pkg/remediator/reconcile/reconciler.go
- pkg/remediator/reconcile/reconciler_test.go
- pkg/remediator/reconcile/worker.go
- pkg/remediator/reconcile/worker_test.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/filteredwatcher_test.go
- pkg/syncer/syncertest/fake/applier.go
- Added `type` tag to the following metrics:
- APICallDuration
- ApplyOperations
- RemediateDuration
- Added `commit` tag to the following metrics:
- DeclaredResources
- LastApply
- ResourceConflicts
- Filtered the `type` and `commit` tags from all metrics when exporting to Monarch
- **Type** is important for validating metrics occurred because of a specific type (aka Kind) of object. Type allows verifying that the expected number of API calls were made for the expected resource types. Without this granularity, it's really hard to debug why the count is off when it doesn't match expectations.
- **Commit** is important for validating metrics occurred because of a specific source change. Without commit, it's difficult to validate that a metric was recorded after or before any given commit. …
> Add type & commit metric tags

- e2e/testcases/csr_auth_test.go
In the original cleanup code, it checks the membership object on the cluster. Sometimes, the membership object is deleted successfully, while the membership resource still exists in the GCP project.
This commit updates the cleanup function to check the membership resource using gcloud.
> Fix the cleanup for fleet memberships

- Makefile.build
- e2e/nomostest/notification_config.go
- e2e/nomostest/notification_server.go
- e2e/nomostest/predicates.go
- e2e/testcases/notification_test.go
- manifests/ns-reconciler-cluster-role.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- pkg/api/configsync/v1beta1/getters.go
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/util.go
- pkg/util/notification.go
- pkg/util/notification_test.go
This change adds logic to manage the notification controller via the reconciler-manager. The reconciler-manager will create the notification controller as a pod in the reconciler deployment if the notification API is enabled in the RSync.
> feat: manage notification controller

- e2e/testcases/csr_auth_test.go
There're different error messages returned from the fleet. This commit updates the check to include all possible messages.
Examples:
$ gcloud container fleet memberships describe kpt-config-sync-ci-r-multi-repo-8-standard-regular --project kpt-config-sync-ci-release ERROR: (gcloud.container.fleet.memberships.describe) No memberships available in the fleet.
$ gcloud container fleet memberships describe kpt-config-sync-ci-r-multi-repo-8-standard-regular --project cs-dev-hub ERROR: (gcloud.container.fleet.memberships.describe) Membership kpt-config-sync-ci-r-multi-repo-8-standard-regular not found in the fleet.
$ gcloud container fleet memberships describe kpt-config-sync-ci-r-multi-repo-8-standard-regular --project kpt-config-sync-ci-release ERROR: …
> Fix the check for the membership existence message (#486)

- pkg/remediator/reconcile/reconciler.go
- pkg/syncer/reconcile/apply.go
- pkg/syncer/syncertest/fake/applier.go
The remediator's applier defines a list of methods that return both a boolean and an error, but the boolean value is never used. This commit removes the unused boolean value.
> Remove the unused boolean from the remediator's applier methods

- cmd/nomoserrors/examples/examples.go
- pkg/status/fight_error.go
- pkg/syncer/reconcile/fight_detector.go
This will be a user-facing error and exposed in the R*Sync status field.
> Moves the fight error to the status package

- e2e/testcases/remediator_test.go
- pkg/parse/root_test.go
- pkg/parse/updater.go
- pkg/remediator/reconcile/reconciler.go
- pkg/remediator/reconcile/reconciler_test.go
- pkg/remediator/reconcile/worker.go
- pkg/remediator/reconcile/worker_test.go
- pkg/remediator/remediator.go
- pkg/syncer/reconcile/apply.go
- pkg/syncer/reconcile/fight/detector.go
- pkg/syncer/reconcile/fight/detector_test.go
- pkg/syncer/reconcile/fight/handler.go
- pkg/syncer/reconcile/fight/logger.go
- pkg/syncer/syncertest/fake/fight_handler.go
Previously, if Config Sync constantly fights with other controllers on certain resources, Config Sync only logs the fight as a warning in the reconciler log. The fight is not exposed to the user in the R*Sync status.
This commit adds the fight errors to the `status.sync` field, which is more visible to the user so they can take actions to address the fight.
> Surface the fight errors in the R*Sync status field

- pkg/applier/applier.go
- pkg/metrics/record.go
- pkg/remediator/reconcile/reconciler.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/syncer/client/client.go
- pkg/syncer/reconcile/apply.go
The record functions only use the Kind tag. Passing GVK requires providing an empty version string to the callers.
It also sets the name tag.
> Pass Kind instead of GVK to the record metrics functions

- cmd/nomos/status/client.go
- cmd/nomos/status/cluster_state.go
- cmd/nomos/status/status.go
- e2e/testcases/cli_test.go
Customers have been requesting a feature to filter the result of `nomos status` based on their selected RootSync object. To accommodate this, we added `name` flag that will filter the output of `nomos status` based on the provided root or repo sync name. This will work in conjunction with `namespace` flag that will filter based on namespace, and have been used by customer to filter RepoSync.
In this PR:
- add --name flag for sync name filtering
- update --namespace flag to work when the value is config-management-system
- update nomos status usage in OSS cluster to work with the new name and namespace flag
- e2e test for use cases and different combination of name and namepsace flag
> Nomos status rsync filter

- scripts/vulnerabilities.sh
Example output:
```
$ scripts/vulnerabilities.sh
Scanning..........
IMAGE                                                                          VULNERABILITIES
gcr.io/config-management-release/admission-webhook:v1.15.0-rc.1                12
gcr.io/config-management-release/git-sync:v3.6.4-gke.1__linux_amd64            0
gcr.io/config-management-release/helm-sync:v1.15.0-rc.1                        46
gcr.io/config-management-release/hydration-controller:v1.15.0-rc.1             86
gcr.io/config-management-release/hydration-controller-with-shell:v1.15.0-rc.1  86
gcr.io/config-management-release/nomos:v1.15.0-rc.1                            12
gcr.io/config-management-release/oci-sync:v1.15.0-rc.1                         12
gcr.io/config-management-release/reconciler-manager:v1.15.0-rc.1 …
```
> Add script to report image vulnerabilities

- Makefile
- build/all/Dockerfile
- build/buildenv/Dockerfile
- go.mod
- pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
- pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
- scripts/lint-go.sh
- Fix several CVEs from Go 1.17
- Update buildenv image to use golang:1.19.7-buster
- Pull out variable for golangci-lint version
This started as a cherry-pick of https://github.com/GoogleContainerTools/kpt-config-sync/pull/465, but some different choices were made previously when upgrading golangci-lint, so there weren't any more lint failures to fix. And we don't need to use the default exclusions, because we already have exclusions configured in .golangci.yaml.
> Update Go to v1.19

- build/all/Dockerfile
- Should help reduce the number of CVEs in the image scanner, since it's using Go 1.19
> Update kustomize to v5.0.1 for hydration

- Makefile
- build/test-e2e-go/gke/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- manifests/patch/kustomization.yaml
- pkg/hydrate/tool_util.go
- pkg/kmetrics/exec_test.go
- Update nomos hydrate
- Update kind & gke build images
- Update local install make target
- Update manifest/kustomize.yaml to use patches, instead of the
deprecated patchesStrategicMerge.
- Ensure patchesStrategicMerge still works, by leaving it in the
hydration unit tests.
> Update helm & kustomize (cont.)

- build/test-e2e-go/gke/Dockerfile
- build/test-e2e-go/kind/Dockerfile
This change installs the gke-gcloud-auth-plugin in the image which the e2e tests run in. This change will be needed to support authentication with GKE clusters starting with v1.26.
> ci: install gke-auth-plugin in e2e image

- build/all/Dockerfile
- e2e/nomostest/testshell/shell.go
- e2e/testcases/cli_test.go
- Use 65532 for nonroot user & group, for all images. This is the distroless standard. Some of the containers were using 1000, the id from docker docs, which was causing files to be owned by the wrong user.
- Extract a debian-nonroot base image to avoid duplicating the nonroot user setup.
- Clean up TestNomosImage by extracting a Shell.Docker method to handle logging.
Docker uses the 1000 UID for its dind images, and vscode uses it too, but Debian doesn't ship with a nonroot user or group. Distroess uses 65532 for nonroot. So setting `USER nonroot:nonroot` in debian wasn't actually working but also not failing the build or the test. Same with using `USER 1000` in distroless. And there was a `chown 1000` that also wasn't really doing what was intended.
> Fix debian container nonroot user

- e2e/nomostest/git.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/portforwarder/port_forwarder.go
- e2e/nomostest/prometheus.go
- e2e/nomostest/prometheus_metrics.go
- e2e/nomostest/testkubeclient/client.go
- e2e/nomostest/testwatcher/watch.go
- e2e/testcases/root_sync_test.go
This updates the port forwarding logic to spawn a thread which ensures the port forward stays open if the deployment pod changes. The git server also needs to have its git repositories re-initialized because it uses emptyDir storage.
> test: keep port forwards open when pod changes

- e2e/nomostest/gitproviders/bitbucket.go
Create repository API in bitbucket (POST https://api.bitbucket.org/2.0/repositories/) will return an error if the repository name ends in a non alphanumeric character. Given that we are currently using `uuid.NewRandom` to generate a unique repository name and perform truncation to keep the name within maximum length, the repository name can end with a hyphen '-' character. To prevent this, all the hyphens in the name and uuid will be stripped
> Bitbucket e2e test create repository fix

- Makefile
- Makefile.build
- build/all/Dockerfile
- Move creation of LICENSES.txt into the release build image. This allows inclusion of the binary dependency licenses, which are not vendored.
> Add helm & kustomize licenses into images

- build/all/Dockerfile
Since wget validates the TLS cert of github when downloading, we can trust that the file is from the expected source without MITM modification. Validating the checksum proves that the file downloaded without corruption. This mirrors what a package manager would do.
> Validate helm & kustomize checksums

- e2e/nomostest/git.go
The port argument only needs to be provided for the in-cluster git provider. In other cases, such as Gitlab or Bitbucket, the gitRepoPortForwarder is nil and the port argument is unused. This updates the logic for git repository setup to support the other git provider types.
> test: fix git portforward to support non-local provider

- scripts/vulnerabilities.sh
The -u flag was showing only the unique values, which isn't what we wanted. Now it reduces duplicate entries to single entries as intended.
> Fix vulnerabilities.sh uniqueness filter

- e2e/nomostest/git.go
- e2e/nomostest/gitproviders/bitbucket.go
- e2e/nomostest/gitproviders/git-provider.go
- e2e/nomostest/gitproviders/gitlab.go
- e2e/nomostest/gitproviders/local.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/portforwarder/port_forwarder.go
This refactors the git port forwarder abstraction to be underneath the git provider. The git port forwarder is only relevant with the in-cluster git server, and thus fits as an implementation detail of the LocalProvider.
> test: refactor git portforwarder under gitprovider

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
There are certain code paths which expect the GitProvider to be set, such as Clean for shared test environments on GKE. Initializing the GitProvider later in setupTestCase was leading to a null pointer exception. This moves the initialization to FreshTestEnv/SharedTestEnv.
> test: init GitProvider before setupTestCase

- e2e/nomostest/git.go
The GitProvider must be set here, otherwise the Repository may be using a GitProvider from a previous NT. Using a stale GitProvider means that the PortForwarder will be closed, since it is closed at the end of the test.
> test: set GitProvider in ReInit

- e2e/nomostest/git.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
The RootRepos/NonRootRepos fields are reset for every testcase, which required for the PortForwarder to be recreated with each testcase. This switches the reset function to use RemoteRepositories, which represents all Repositories that have been created (across test cases). This change enables us to create a single GitProvider in FreshTestEnv and share it across shared test environments. This also means there is only a single PortForwarder to the git server active at a given time, which is preferred.
> test: use RemoteRepositories for setPortCallback

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/validate_secret.go
The reconciler-manager should validate that the Secret referred to by caCertSecretRef is well-formed. If the key named cert is not set in the secret, then the reconciler-manager should report an error to the user.
> Improved caCert validation

- pkg/hydrate/controller.go
- pkg/hydrate/controller_test.go
- pkg/util/log/logging.go
The Args field sometimes contains values which change between reconciles, such as the failCount in the *-sync containers. Having errors which flap between iterations makes it unfeasible to treat the error message as a unique key for notification delivery, as the user will get repeat notifications for errors with trivial differences. This change adds logic to filter out the Args field of the error payload before passing it through to the RSync status.
> feat: filter Args from error json in RSync status

- e2e/nomostest/gitproviders/git-provider.go
- e2e/nomostest/gitproviders/local.go
- e2e/nomostest/gitproviders/repository.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/portforwarder/port_forwarder.go
- e2e/nomostest/reset.go
Prior to this change the port forward was restarted only if the Pod was
restarted. This change makes it so that the port forward is restarted
either if the Pod is restarted or if the port-forward process is killed.
> test: restart PortForwarder if process is killed

- Makefile.e2e
- Makefile.e2e.ci
- cmd/notification/main.go
- e2e/nomostest/notification_config.go
- e2e/nomostest/testing/feature.go
- e2e/testcases/notification_test.go
- pkg/notifications/expressions/strings/strings.go
- pkg/notifications/expressions/strings/strings_test.go
- pkg/notifications/expressions/utils/utils.go
- pkg/notifications/expressions/utils/utils_test.go
This change adds a set of functions which can be invoked from
notification templates and triggers. These functions are intended to
help with configuring notifications for common use cases, such as a sync
failure.
> Notification helper functions

- e2e/nomostest/gitproviders/bitbucket.go
- e2e/nomostest/gitproviders/git-provider.go
- e2e/nomostest/gitproviders/gitlab.go
- e2e/nomostest/new.go
There seem to be some flaky failures in CI around DeleteObsoleteRepos. This extra logging is intended to help identify the source of those errors.
> test: improve logging of gitlab/bitbucket cleanup

- e2e/testcases/apply_scoped_resource_test.go
- examples/kubevirt-compiled/bookstore1/virtualmachine_testvm.yaml
- examples/kubevirt-compiled/clusterrole_kubevirt-operator.yaml
- examples/kubevirt-compiled/clusterrole_kubevirt.io-operator.yaml
- examples/kubevirt-compiled/clusterrolebinding_kubevirt-operator.yaml
- examples/kubevirt-compiled/customresourcedefinition_kubevirts.kubevirt.io.yaml
- examples/kubevirt-compiled/kubevirt/deployment_virt-operator.yaml
- examples/kubevirt-compiled/kubevirt/kubevirt_kubevirt.yaml
- examples/kubevirt-compiled/kubevirt/role_kubevirt-operator.yaml
- examples/kubevirt-compiled/kubevirt/rolebinding_kubevirt-operator-rolebinding.yaml
- examples/kubevirt-compiled/kubevirt/serviceaccount_kubevirt-operator.yaml
- examples/kubevirt-compiled/namespace_bookstore1.yaml
- examples/kubevirt-compiled/namespace_kubevirt.yaml
- examples/kubevirt-compiled/priorityclass_kubevirt-cluster-critical.yaml
- examples/kubevirt/README.md
- examples/kubevirt/kubevirt-operator.yaml
The colon in the file name breaks Go imports. This updates the kubevirt examples to not include any colons in file names.
Fixes:
- https://github.com/GoogleContainerTools/kpt-config-sync/issues/552
Context:
- https://github.com/GoogleContainerTools/kpt-config-sync/issues/4
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/8
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/297
> chore: fix kubevirt file naming

- e2e/testcases/helm_sync_test.go
Accidentally put a v in front of the helm chart version when I should not have. This PR fixes the typo.
> fix typo in helm chart version

- cmd/reconciler-manager/main.go
- pkg/reconcilermanager/controllers/constants.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
- pkg/reconcilermanager/controllers/otel_sa_controller.go
Currently, to export CS metrics to Cloud Monitoring and Cloud Monarch on a GKE cluster with Workload Identity enabled, the customers need to: 
1) bind the `default` service account in the    `config-management-monitoring` namespace to a GSA with the metric    writer role;
2) set the `iam.gke.io/gcp-service-account` annotation of the k8s        service account to the email address of the GSA;
3) restart the `otel-collector` Deployment.
This PR automates the third step by adding a new reconciler into reconciler-manager. The new reconciler watches the default service account under the config-management-monitoring namespace, and adds/updates the `iam.gke.io/gcp-service-account` annotation in the `spec.template.annotation` field of the otel-collector Deployment. This triggers the Deployment to …
> Add a new reconciler into reconciler-manager

- cmd/reconciler-manager/main.go
- pkg/reconcilermanager/controllers/constants.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
- pkg/reconcilermanager/controllers/otel_sa_controller.go
Add a new reconciler into reconciler-manager watching the default service account under the config-management-monitoring namespace
Currently, to export CS metrics to Cloud Monitoring and Cloud Monarch on a GKE cluster with Workload Identity enabled, the customers need to: 1) bind the `default` service account in the
`config-management-monitoring` namespace to a GSA with the metric
writer role;
2) set the `iam.gke.io/gcp-service-account` annotation of the k8s
service account to the email address of the GSA;
3) restart the `otel-collector` Deployment.
This PR automates the third step by adding a new reconciler into reconciler-manager. The new reconciler watches the default service account under the config-management-monitoring namespace, and adds/updates the `iam.gke.io/gcp-service-account` …
> Add a new reconciler into reconciler-manager (#539)

- e2e/testcases/override_reconcile_timeout_test.go
We've observed some flaky CI failures for this test when checking the ResourceGroup status immediately after WatchForAllSyncs. The objects have not necessarily reconciled after WatchForAllSyncs, so this uses WatchObject to implement waiting for reconciliation.
> test: add wait for resourcegroup status

- e2e/testcases/override_reconcile_timeout_test.go
We've observed some flaky CI failures for this test when checking the ResourceGroup status immediately after WatchForAllSyncs. The objects have not necessarily reconciled after WatchForAllSyncs, so this uses WatchObject to implement waiting for reconciliation.
> [CHERRYPICK] test: add wait for resourcegroup status (#561)

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/prometheus_metrics.go
The metrics validation now gets the dynamic port forward in the retry loop. If the port forward has to restart during the loop, this can take longer than the default metrics timeout (esp on autopilot). This is because under this scenario we may need to wait for the Pod to be ready before we can get a valid port forward. This change replaces the metrics timeout with the standard wait timeout to account for longer delays.
Context:
- https://testgrid.k8s.io/googleoss-kpt-config-sync-release-multi-repo-8#autopilot-rapid-latest
- https://oss.gprow.dev/view/gcs/oss-prow-build-kpt-config-sync/logs/release-multi-repo-8-autopilot-rapid-latest/1653362701939773440
- https://oss.gprow.dev/view/gcs/oss-prow-build-kpt-config-sync/logs/release-multi-repo-8-autopilot-rapid-latest/1653331999286366208
> test: replace metrics timeout with wait timeout

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/prometheus_metrics.go
The metrics validation now gets the dynamic port forward in the retry loop. If the port forward has to restart during the loop, this can take longer than the default metrics timeout (esp on autopilot). This is because under this scenario we may need to wait for the Pod to be ready before we can get a valid port forward. This change replaces the metrics timeout with the standard wait timeout to account for longer delays.
> [CHERRYPICK] test: replace metrics timeout with wait timeout (#565)

- e2e/testdata/prometheus/prometheus.yaml
Recent test failures in release-multi-repo-8-autopilot-rapid-latest were caused by OOMKilled failures in the prometheus container:
```
containerStatuses:
- containerID: containerd://eda177e63e2c28e473c95a17287015cae17af4503ad8ad04f99a138fa14dfd6f
image: docker.io/prom/prometheus:v2.37.6
imageID: docker.io/prom/prometheus@sha256:92ceb93400dd4c887c76685d258bd75b9dcfe3419b71932821e9dcc70288d851
lastState:
terminated:
containerID: containerd://eda177e63e2c28e473c95a17287015cae17af4503ad8ad04f99a138fa14dfd6f
exitCode: 137
finishedAt: "2023-05-03T18:05:49Z"
reason: OOMKilled
startedAt: "2023-05-03T18:05:16Z"
name: prometheus
ready: false
restartCount: 7
started: false
state:
waiting:
message: back-off 5m0s restarting failed container=prometheus …
```
> Increase the test prometheus memory request

- e2e/testdata/prometheus/prometheus.yaml
Recent test failures in release-multi-repo-8-autopilot-rapid-latest were caused by OOMKilled failures in the prometheus container:
```
containerStatuses:
- containerID: containerd://eda177e63e2c28e473c95a17287015cae17af4503ad8ad04f99a138fa14dfd6f
image: docker.io/prom/prometheus:v2.37.6
imageID: docker.io/prom/prometheus@sha256:92ceb93400dd4c887c76685d258bd75b9dcfe3419b71932821e9dcc70288d851
lastState:
terminated:
containerID: containerd://eda177e63e2c28e473c95a17287015cae17af4503ad8ad04f99a138fa14dfd6f
exitCode: 137
finishedAt: "2023-05-03T18:05:49Z"
reason: OOMKilled
startedAt: "2023-05-03T18:05:16Z"
name: prometheus
ready: false
restartCount: 7
started: false
state:
waiting:
message: back-off 5m0s restarting failed container=prometheus …
```
> Increase the test prometheus memory request (#569)

- Makefile.release
- scripts/tag-release-candidate.sh
this is intended to provide more context to the releaser when they are running the script
> add commit log to release tag script

- e2e/testdata/prometheus/prometheus.yaml
We're still seeing OOMKilled issues for the Prometheus Pod running on Autopilot rapid-latest channel after clearing the cache.
This commit further increases the memory request to 1.5GiB.
> Bump the test prometheus memory request to 1.5Gi (#581)

- Makefile
- build/all/Dockerfile
- build/test-e2e-go/gke/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- pkg/hydrate/tool_util.go
Kustomize v5.0.2 breaks helmCharts with chartHome option. This commit updates the version to address the issue.
More context: https://github.com/kubernetes-sigs/kustomize/issues/5163
> Bump the kustomize CLI version to fix a regression

- Makefile
- build/all/Dockerfile
- build/test-e2e-go/gke/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- pkg/hydrate/tool_util.go
Kustomize v5.0.2 breaks helmCharts with chartHome option. This commit updates the version to address the issue.
More context: https://github.com/kubernetes-sigs/kustomize/issues/5163
> Bump the kustomize CLI version to fix a regression (#585)

- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/logger.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/otel_sa_controller.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/secret.go
- pkg/reconcilermanager/controllers/secret_test.go
- Add a new base class to handle logger methods
- Add the logger to the context for each Reconcile with contextual values that identify the rsync and reconciler.
- Add new contextual values for objects being modified that doesn't overlap with the rsync values.
- Use the logr whenever the context is available, otherwise just use klog (setup and event handlers).
- Use ObjectKeys in places where it makes sense to use them in logs.
- Clarify a few log messages
> Clean up reconciler-manager logging

- e2e/testdata/prometheus/prometheus.yaml
The Prometheus Pod consumes more than 1.5GiB memory on Autopilot 1.26 clusters. We tried to clear the cache before each test case (PR#579), but WAL replays the deleted data series, which caused the Pod to crash again.
This commit limits the retention size to 1GB, so that old data can be removed to avoid exceeding the limit.
> Set Prometheus retention size to limit the memory usage

- e2e/testdata/prometheus/prometheus.yaml
The Prometheus Pod consumes more than 1.5GiB memory on Autopilot 1.26 clusters. We tried to clear the cache before each test case (PR#579), but WAL replays the deleted data series, which caused the Pod to crash again.
This commit limits the retention size to 1GB, so that old data can be removed to avoid exceeding the limit.
> Set Prometheus retention size to limit the memory usage (#601)

- Makefile
- Makefile.build
- Makefile.e2e.ci
- Makefile.oss
These targets will be used by a new postsubmit prowjob to publish artifacts.
> ci: add postsubmit targets

- e2e/testdata/prometheus/prometheus.yaml
Autopilot 1.26 sends more than 220k data series for the `cilium_k8s_client_api_latency_time_seconds` metric, which caused OOMkilled issue.
This commit drops the metric to fix the CI failures.
b/283001264
> Drop the k8s client api latency metric to fix the OOMKilled issue

- Makefile.build
gcloud auth configure-docker takes a list of host names to set up a credential helper for. This change updates the invocation to select the hostname from the provided REGISTRY, which enables pushing to artifact registry repositories.
> fix: support auth for artifact registry with push-images

- e2e/testdata/prometheus/prometheus.yaml
Autopilot 1.26 sends more than 220k data series for the `cilium_k8s_client_api_latency_time_seconds` metric, which caused OOMkilled issue.
This commit drops the metric to fix the CI failures.
b/283001264
> Drop the k8s client api latency metric to fix the OOMKilled issue (#604)

- cmd/nomos/status/cluster_state.go
- cmd/nomos/status/cluster_state_test.go
When user is using `nomos status` command with `--name` filter, the separator "--------------------" is displayed for every RootSync even when the RootSync isn't being printed. This fix will display the separator only when the RootSync is printed in the result.
> Nomos status filter separator fix

- Makefile.build
- Makefile.e2e.ci
- build/prow/vulnerability-scanner/Dockerfile
- scripts/pull-postsubmit-retry.sh
- scripts/vulnerabilities.sh
- Use manifests for getting image tags. This makes it straightforward to pull down the manifest and get all images included with that manifest.
- Fix assumptions about GCP project/registries. It should be assumed that all images are hosted on either GCR/GAR with container scanning enabled. These may also be hosted in different projects/registries, e.g. git-sync, gcenode-askpass-sidecar, etc.
> update vulnerability scan script for CI usage

- Makefile.e2e.ci
The clean/output_dir targets are required by the underlying pull-gcs target, which pull-gcs-postsubmit uses as a building block.
> fix: move prerequisites to pull-gcs recipe

- Makefile
- docs/development.md
- scripts/build-status.sh
- scripts/lib/manifests.sh
- scripts/vulnerabilities.sh
This script is parses the rendered manifests on the local filesystem and provides some build status information. This is intended for developer use cases to help with understanding the build state.
These manifests are used as inputs for other commands, such as deploying config sync or running the e2e tests.
> add build-status script

- pkg/reconcilermanager/controllers/garbage_collector.go
- Add a check to allow Not Found when getting ClusterRoleBinding and RoleBinding before removing a subject. This fixes multiple edge cases where the CRB/RB might have already been deleted.
> Fix reconciler-manager to handle async deletion

- pkg/core/names.go
- pkg/reconcilermanager/controllers/controller.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/syncer/syncertest/fake/cache.go
- pkg/syncer/syncertest/fake/informer_factory.go
- vendor/github.com/go-logr/logr/funcr/funcr.go
- vendor/github.com/go-logr/logr/testr/testr.go
- vendor/modules.txt
- Add fake.Cache and fake.TypedInformerFactory to facilitate building testable controller-runtime managers.
- Add core.RootReconcilerObjectKey and core.NsReconcilerObjectKey to make it easier to build ObjectKey/NamespacedName for reconciler deployments.
- Add a Controller interface for self-registering controllers, like RootSyncReconciler and RepoSyncReconciler
- Configure controller-runtime logs to print to the test log for reconciler-manager controller unit tests.
> Add rsync manager lifecycle tests

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- The reconciler-manager rurrently skips reconciles if the RootSync or RepoSync ResourceVersion didn't change. This causes it to miss updates to other watched resources, like user Secrets, and drift in other managed objects, like the reconciler Deployment, ServiceAccount, RoleBinding, and Secrets.
- Fix the issue by removing the ResourceVersion cache "optimization" that was originally added to reduce API calls.
- This may moderately increase API calls, but mostly Get & List calls, which are fast due to server-side cache, and don't cause etcd churn.
> Fix reconciler-manager missing object updates

- cmd/nomos/status/cluster_state.go
- cmd/nomos/status/cluster_state_test.go
When user is using `nomos status` command with `--name` filter, the separator "--------------------" is displayed for every RootSync even when the RootSync isn't being printed. This fix will display the separator only when the RootSync is printed in the result.
> Nomos status filter separator fix (#612)

- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- Remove the RepoSync cache "optimization", because it was causing the reconciler-manager to skip cleanup of managed objects in some edge cases, like restart/reschedule that would reset the cache.
- The optimization was originally added to reduce the number of API calls, but since Reconcile is only triggered by objects that map to the specific RepoSync, we do actually need to handle each change, especially if it happens to a managed object after its RepoSync was deleted. It probably needs deleting.
> Fix reconciler-manager skipping cleanup

- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/otel_sa_controller.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/util.go
- Convert RootSync controller to manage cleanup the same way the
RepoSync controller does: delete everything after the RSync is
Not Found, instead of using the K8s Garbage collector.
This makes the behavior and code more consistent, in prep for the
upcoming reconciler-manager finalizer.
- Combine cleanup methods in the reconcilerBase class.
- Extract upsertManagedObjects and deleteManagedObjects methods
- Log & skip managed object upserts when an RSync is being deleted.
Extracted:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/594
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/597
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/598
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/637
- …
> Rewrite sync controller garbage collection

- e2e/nomostest/helm/helm.go
- e2e/testcases/csr_auth_test.go
- e2e/testcases/helm_sync_test.go
- e2e/testdata/helm-charts/simple/templates/deployment.yaml
- e2e/testdata/root-sync-helm-chart-version-range-cr.yaml
- pkg/helm/helm.go
- pkg/parse/root.go
This PR adds support for allowing users to specify a range in `spec.helm.version` in the RSync object and we pull down the latest one from the range.
- The version range syntax is natively supported by Helm CLI. See the syntax here: [https://github.com/Masterminds/semver#hyphen-range-comparisons](https://www.google.com/url?q=https://github.com/Masterminds/semver%23hyphen-range-comparisons) 
- This PR has some changes to ensure that the RSync object is reporting the actual version that was pulled down, instead of just displaying whatever was specified in `spec.helm.version`
- If someone pushes a new helm chart, helm-sync will pick up the new chart without requiring changes to the RSync object.
> helm api: allow user to specify a version range

- pkg/reconcilermanager/controllers/create_or_update.go
- pkg/reconcilermanager/controllers/errors.go
- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/secret.go
- Extract setup method to wrap upsertManagedObjects and handle updating the sync object status conditions.
- Add ObjectOperationError & ObjectReconcileError to pass more context about errors between abstraction layers.
- Update upsert and delete methods to return these new errors.
- Add CreateOrUpdate func that returns ObjectOperationErrors where applicable.
- Avoid updating RoleBinding and ClusterRoleBinding when noting changed.
> Rewrite reconciler-manager error handling

- pkg/helm/helm.go
This seemed to fix the issue for autopilot clusters on my end, hopefully it will fix the issue in the test cluster too. Leaving this as a draft while I do some more experimentation.
b/286152128
> helm: clear cache after getting chart version

- Makefile
- Makefile.oss.prow
The install-helm target was installing helm into a nested subdirectory, causing it to not be discoverable in the PATH. This refactors the target to reuse the buildenv-dirs target, which correctly creates the directory.
Also set the PATH in the makefile so that we use the correct binaries, prioritizing the local build dir, then the go bins, then the parent PATH.
> fix: install/use binaries from local build dir

- e2e/testcases/helm_sync_test.go
- e2e/testinfra/terraform/common/service_accounts.tf
- e2e/testinfra/terraform/modules/service_account/service_account.tf
There is no workload identity binding for ns reconcilers, which was causing this test to fail. This change adds a workload identity binding for repo-sync and updates the test to create the correctly named RepoSync.
Also removes the AR/CSR reader permissions from the default compute SA, as this was causing false positives when testing with a cluster that did not have workload identity enabled.
> ci: fix workload identity for reposync

- e2e/nomostest/clusters/gke.go
The cluster creation was missing the workload identity option, causing tests which require workload identity to fail.
> test: enable workload identity for new gke clusters

- e2e/testcases/csr_auth_test.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/oci_sync_test.go
The flag pointers are updated after module initialization, causing these string to be evaluated with the default value instead of the parsed value. This works when the desired value is the default or and environment variable, but not when the desired value is the command line flag. Update the variables to functions so that the pointer value is evaluated after the flag has been parsed.
> test: fix usage of flag pointers in tests

- e2e/nomostest/clusters/gke.go
- e2e/testcases/csr_auth_test.go
- e2e/testcases/oci_sync_test.go
- e2e/testinfra/terraform/common/service_accounts.tf
The gcenode tests require the compute GSA to have reader permissions for AR and CSR. Having this permission on the default compute SA can lead to false positives with the workload identity tests, so this change adds assertions for workload identity on the target cluster.
> ci: fix permissions for gcenode tests

- e2e/testdata/root-sync-helm-chart-cr.yaml
- e2e/testdata/root-sync-helm-chart-version-range-cr.yaml
follow up experimentation https://github.com/GoogleContainerTools/kpt-config-sync/pull/662 - trying to find the minimum resource request we can make and still have these tests pass in CI
> tweak memory request for some helm sync tests

- cmd/reconciler-manager/main.go
- e2e/nomostest/git-server.go
- e2e/nomostest/ssh.go
- e2e/testcases/reconciler_manager_test.go
- pkg/metadata/finalizers.go
- pkg/reconcilermanager/controllers/errors.go
- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/syncer/syncertest/fake/storage.go
- pkg/syncer/syncertest/fake/watcher.go
- pkg/util/watch/delete.go
- pkg/util/watch/listerwatcher.go
- pkg/util/watch/listerwatcher_test.go
- pkg/util/watch/until.go
- The reconciler-manager now adds a finalizer onto all RootSyncs &
RepoSyncs ("configsync.gke.io/reconciler-manager") which blocks
removal of these objects until garbage collection is complete.
This ensures that garbage collection has completed when the object
is reconciled (Not Found), making it safer to use RootSyncs &
RepoSyncs as dependencies.
- Watch for object deletion before completing garbage collection.
This ensures the objects are Not Found before allowing RSync
removal.
- Add watch.DeleteAndWait & watch.UntilDeletedWithSync to help work
around limitations of the controller-runtime client.Delete.
b/236892981
Extracted:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/582
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/583
- …
> feat: Add reconciler-manager finalizer

- Makefile
- Makefile.e2e
- Makefile.e2e.ci
- Makefile.oss.prow
- build/prow/gke-e2e/Dockerfile
- build/prow/kubekins-e2e/Dockerfile
- build/test-e2e-go/e2e.sh
Adds a series of make targets to support running the newly added parallel gke e2e tests in CI.
Add Dockerfile for gke-e2e image. This is based on and intended to replace the test-e2e-go/gke image. The latter image is rebuilt on every CI test execution and invoked using docker-in-docker inside the prowjob. The new prowjob is intended to not require docker-in-docker, and will use this new image which is built once and used many times. This is intended to simplify and reduce the runtime of the prowjob. Versioned dependencies such as kustomize and helm are still installed at runtime.
This change adds some make targets which are similar to existing targets - this is intentional. New prowjobs will be defined which use the new targets, and the old targets will be cleaned up once the existing …
> ci: add make targets for parallel gke e2e

- Makefile.build
- Makefile.e2e.ci
This change adds a copy-cli target which copies the nomos binary from the os/arch subdirectory into the top level bin directory. This enables it to be in the PATH for subsequent commands. Call copy-cli after pulling postsubmit artifacts so that the binary can be used. This enables the periodic CI jobs to use the binary that is pulled from the postsubmit artifacts.
> ci: copy nomos binary into path

- Makefile.e2e
This change updates the kind e2e target which is used by the presubmits to enable shared test env. This makes the presubmits behave more similarly to the periodics, so that we can discover cleanup related issues before they are submitted.
> ci: use share-test-env for kind presubmits

- e2e/testcases/sync_ordering_test.go
These namespaces were being created implicitly, and thus not being deleted by the end of the test. This change adds the namespace to the git repo so that it will be created explicitly and deleted at the end of the test.
> test: add bookstore namespace to sync order tests

- e2e/testcases/cli_test.go
There is a known issue around nomos bugreport that breaks workload identity based authentication when running in a Pod. This change adds the known workaround to enable running the command in a Pod. This should be removed once the underlying issue is fixed.
> ci: hack to enable nomos bugreport in pod

- e2e/nomostest/clusters/gke.go
- e2e/testcases/main_test.go
Some of these flags cannot be provided when creating autopilot clusters, such as machine type.
> test: add conditional for invalid autopilot flags

- build/prow/gke-e2e/Dockerfile
This binary is needed for the e2e prow script to generate a junit report
> add junit cli to gke-e2e image

- e2e/testcases/override_reconcile_timeout_test.go
- e2e/testdata/low-priority-pause-deployment.yaml
Explicitly set the namespace for the pause-deployment object. When running this in a Pod the applied object defaults to the namespace of the Pod.
Also move the cleanup instantiation to before the apply, so the cleanup runs in the case that the apply errors.
> test: fix for reconcile timeout test on autopilot

- e2e/nomostest/reset.go
- e2e/testcases/reconciler_finalizer_test.go
Now that the reconciler-manager uses a finalizer to delete managed resources, it's safe to delete RootSyncs with foreground deletion propagation.
> Use foreground delete on RootSyncs

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/testing/ntb.go
- e2e/nomostest/testlogger/testlogger.go
Using the logger from the testing.T ensures proper interleaving of logs. Without this change shared test environments used the logger from the original FreshTestEnv.
> test: use new logger for each sharedNT

- e2e/nomostest/prometheus_metrics.go
If a connection error occurs here, the portforwarder is most likely in the process of restarting the local port forward. If the portforwarded successfully restarts then ValidateMetrics can succeed on a subsequent retry.
> test: do not treat ECONNREFUSED as terminal err

- e2e/nomostest/docker.go
- e2e/nomostest/new.go
- e2e/testcases/main_test.go
This accomplishes a few things:
- run check images before clusters are created
- allow running tests on kind with images not in the local registry
- check images before running tests on GKE
> test: shift left e2e check images

- e2e/nomostest/clusters/gke.go
Since we were not matching the end of the string, this filter could return operations for multiple clusters. The stricter regex should result in operations for a unique cluster name.
> test: stricter regex for gke operation filter

- pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
Declare a common rootSync/repoSync helper that is reused by the various source types, so that it is easier to define common logic.
> refactor: consolidate rsync helper functions

- cmd/reconciler-manager/main.go
- e2e/nomostest/config_sync.go
- e2e/nomostest/new.go
Pulled out from https://github.com/GoogleContainerTools/kpt-config-sync/pull/707, see discussion in https://github.com/GoogleContainerTools/kpt-config-sync/pull/707#discussion_r1240911054
I separated the rename and logic fix into separate commits to ease review.
> test: fix poll override logic in `nomostest`

- cmd/helm-sync/main.go
- cmd/reconciler-manager/main.go
- e2e/nomostest/config_sync.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/testcases/helm_sync_test.go
- pkg/api/configsync/register.go
- pkg/helm/helm.go
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/util.go
- pkg/reconcilermanager/controllers/util_test.go
When a version range is detected in the RSync `spec.helm.version`, we currently continuously poll to get the latest version from that range, causing performance degradation. 
This PR does the following:
- by default, we poll every hour for the latest version
- make the poll configurable in helm-sync for testing purposes, but we don't make it configurable through the RSync API
- use 1m as the poll period in tests
b/288478227
> perf: limit helm-sync polling to every hour when a version range is specified

- e2e/flags.go
- e2e/nomostest/nt.go
This parameter can be used to specify a prefix to use when generating cluster names. The default behavior remains to generate a prefix using cs-e2e-<timestamp>.
> test: add cluster-prefix parameter

- pkg/parse/run.go
- pkg/parse/source.go
- pkg/parse/source_test.go
We make the same check when reading the source files, this adds the check when reading the hydration dir for consistency.
Also fixes some test assertions which were passing erroneously.
> fix: check that symlink is unchanged for hydration

- e2e/flags.go
- e2e/nomostest/client.go
- e2e/nomostest/new.go
- e2e/nomostest/ntopts/new.go
- e2e/testcases/main_test.go
This adds several options for destroying clusters:
- true always destroys clusters
- auto destroys clusters if created (default)
- false never destroys clusters
This streamlines the logic for destroying clusters and decouples it from
the cluster creation logic, while maintaining backwards compatible
defaults.
> test: enhance cleanup logic for destroy-clusters

- cmd/reconciler/main.go
- e2e/nomostest/testpredicates/predicates.go
- e2e/testcases/cli_test.go
- e2e/testcases/hydration_test.go
- e2e/testcases/reconciler_manager_test.go
- pkg/hydrate/tool_util.go
- pkg/metadata/annotations.go
- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/run.go
- pkg/parse/run_test.go
- pkg/parse/source.go
- pkg/parse/state.go
- pkg/reconciler/reconciler.go
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/util.go
- pkg/reconcilermanager/controllers/util_test.go
The hydration-controller is used for last mile hydration when the source of truth contains kustomization files, and is a no-op otherwise. This change optimizes the resource footprint of reconciler Pods by dynamically detecting whether the source of truth requires hydration, and only enabling the hydration-controller container if it does.
This is accomplished by setting an annotation with the reconciler, and having the reconciler-manager read that annotation to determine whether to include hydration-controller in the Deployment.
> feat: dynamically disable hydration-controller

- e2e/flags.go
- e2e/nomostest/clusters/gke.go
This adds options to configure the disk size/type for GKE standard clusters. This enables customizing the shape of persistent disks when creating clusters with the test framework.
> test: add e2e options for disk size/type

- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
This change modifies metrics to align with Monarch definition
- includes rg_reconcile_duration_seconds in Monarch pipeline for future SLI setup
- clean up kcc_resource_count_total exclusion since the metric has been removed from Resource Group Controller
> Modify the metrics for CS smokedetector setup

- e2e/nomostest/reset.go
This prints the full namespace yaml for namespaces which fail to be cleaned up in Reset. This is intended to help with diagnosing errors related to Reset, e.g. if the Namespace has a finalizer or deletion timestamp.
> test: add namespace yaml to reset error logging

- e2e/nomostest/clusters/gke.go
The default value is larger than what is required. This sets the default CIDR range to a more reasonable value. This helps fit a greater number of clusters into a network, particularly for CI use cases.
> test: set GKE cidr range when creating clusters

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_base_test.go
Volume names have a length limit of 63 or we get an error, this fixes it so that we just use the valuesFileRef index rather than the ConifgMap name
b/289378438
> helm fix: volume names will use the valuesFileRef index rather than ConfigMap name

- e2e/testcases/helm_sync_test.go
This removes the need of LoadBalancer and avoids the problem of firewall rules cleanup.
> Avoid creating LoadBalancer in wordpress Helm chart

- e2e/nomostest/nt.go
There is currently an issue with cleaning up the ConfigConnector resource in CI that is wedging the cluster. A known issue with cleanup is currently being worked on in cli-utils, so this may be fixed with that change. Prior to a recent change the ConfigConnector resource was created with a one-off provisioning script, so this essentially reverts to that behavior. The KCC tests run on a dedicated KCC cluster, so this should not be too disruptive.
> ci: skip cleanup of ConfigConnector resource

- e2e/flags.go
This updates the default shape of GKE clusters created by the e2e test scaffolding. The default values here are chosen to be identical to the cluster shape used by the CI clusters, which is optimized for speed and minimal resource allocation.
> test: update default GKE shape

- build/all/Dockerfile
- build/prow/vulnerability-scanner/Dockerfile
Using a minor go version, different builds may generate different images.
> Use a patch go version

- e2e/testcases/helm_sync_test.go
- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/zz_generated.conversion.go
- pkg/api/configsync/v1beta1/helmconfig.go
- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_base_test.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/validate/raw/validate/source_spec_validator.go
- Errors from `copyConfigMapsToCms` should cause stalled errors
- ConfigMaps that have been copied to the c-m-s namespace should get deleted if the original source ConfigMap was deleted, the RepoSync object is deleted, or the RepoSync no longer references them.
- Remove extra debug logs.
- Regenerate version conversion code.
- Rename `spec.helm.valuesFileRefs.valuesFile` to `spec.helm.valuesFileRefs.dataKey`
- Remove the default values from the CRDs (if any) and encode them in the controller.
> helm api: better handling of copying referenced configmaps to c-m-s (and other cleanup)

- e2e/nomostest/prometheus_metrics.go
- e2e/testcases/cluster_selectors_test.go
- e2e/testcases/custom_resource_definitions_test.go
- e2e/testcases/custom_resources_test.go
- e2e/testcases/invalid_git_branch_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/namespace_repo_test.go
- e2e/testcases/namespaces_test.go
- e2e/testcases/remediator_test.go
- e2e/testcases/root_sync_test.go
- manifests/otel-agent-cm.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- pkg/metadata/labels.go
- pkg/metrics/otel.go
- pkg/metrics/tagkeys.go
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/util.go
- Add `configsync.gke.io/sync-generation` reconciler deployment/pod label, populated by the reconciler-manager
- Add `CONFIGSYNC_SYNC_GENERATION` env var on the otel-agent container, populated by the k8s downward API from the pod label
- Add `configsync.sync.generation` metric resource attribute on the otel-agent config, populated from the env var
- Add attribute filter to delete the `configsync.sync.generation` label in the otel-collector config, when sending to Monarch
- Change the e2e tests to use the sync metric labels, instead of the pod name. This allows the metrics validation to tolerate pod replacement due to rescheduling, oomkill, or autoscaling
This PR blocks VPA: https://github.com/GoogleContainerTools/kpt-config-sync/pull/691
The e2e tests have been using pod name + source …
> Add configsync_sync_generation metric resource tag

- e2e/nomostest/new.go
- pkg/applier/applier.go
- pkg/applier/applier_err.go
- pkg/applier/applier_test.go
This change updates the WaitEvent processing to treat a reconcile failure or timeout as an error for Destroyer. This ensures that the finalizer waits until all objects are NotFound before exiting.
The behavior is left unchanged for the Applier.
> fix: reconciler fail/timeout as error for destroy

- e2e/nomostest/new.go
- e2e/testcases/stress_test.go
All of the stress tests are now passing in CI with the exception of TestStressLargeRequest. It turns out this test takes a much longer time to reconcile, because it is creating 13,000+ resources in a single RootSync. Increasing the default timeout gives the finalizer enough time to cleanup all of the resources.
> test: increase timeout for stress tests

- e2e/nomostest/testpredicates/predicates.go
- e2e/nomostest/testutils/validate.go
- e2e/testcases/reconciler_finalizer_test.go
With recent changes to cli-utils and the finalizer, the finalizer will properly wait for managed objects to be NotFound before completing. This adds an e2e test to document/verify the behavior.
> test: add finalizer reconcile timeout e2e test

- e2e/testinfra/terraform/common/service_accounts.tf
- e2e/testinfra/terraform/common/services.tf
Otel Collector e2e test requires IAM permission on WI enabled clusters.
This change sets up a Google Service Account with metricWriter role and binds it with the default Kubernetes Service Account under config-management-monitoring namespace.
b/255608560
> [Terraform] Add e2e-metric-writer-sa to test infra

- pkg/reconcilermanager/controllers/errors.go
- pkg/util/watch/delete.go
- pkg/util/watch/until.go
We don't have any yet, but when VPA is added, the reconciler-manager cleanup will need to work with resources whos CRD may have been removed. Also fix the errors so they can be unwrapped correctly. This will fix error messages to be more clear.
> Fix deletion of resources with deleted CRDs

- e2e/nomostest/config_sync.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/multi_repo.go
- Add WithoutReconcileTimeout to remove the setting, if needed.
- Move default ReconcileTimeout into the options constructor, so it can be overridden by test options.
> test: Clean up ReconcileTimeout config

- cmd/reconciler-manager/main.go
- manifests/templates/reconciler-manager.yaml
Previously, -v=# and other log flags were not being registered. Not it sets up log flags the sam as other component binaries.
> Fix reconciler-manager cmd to accept log flags

- e2e/testcases/reconciler_manager_test.go
Reassigning the value in the nested function causes the value to keep increasing on each invocation of the predicate.
> test: fix memory request predicate

- Makefile
- Makefile.build
- Makefile.e2e
- build/prow/kubekins-e2e/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- docs/development.md
- scripts/docker-registry.sh
- scripts/e2e-kind.sh
Assuming that kind is pre-installed on the prow image makes it very difficult to upgrade the kind version, because the kind version of the binary must be the same as the go import. Installing it at runtime makes it easier to change the version.
> test: install kind at runtime

- e2e/nomostest/clean.go
- e2e/nomostest/testutils/validate.go
- e2e/testcases/reconciler_finalizer_test.go
If an error occurs mid-test, it is possible that the finalizer removal is not reached and the object cannot be deleted. This adds a test-specific cleanup and generic suite cleanup for removing the test finalizer.
> test: remove test finalizer in cleanup

- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/third_party/resourcegroup-manifest.yaml
This should prevent the otel-agent and otel-collector from being restarted due to CPU throttling.
> fix: Remove otel agent & collector liveness probe

- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/filteredwatcher_test.go
- pkg/remediator/watch/manager.go
- pkg/status/internal_error.go
Update the remediator's filteredwatcher to handle context cancellation, which is used to shut down the remediator. Previously, the cancel error was treated as any other error and the watcher would restart repeatedly until hitting the retry timeout (~4m). Now it should exit more quickly.
This also avoids logging the confusing watch error, `unable to decode an event from the watch stream`, when the context is cancelled during normal execution.
b/281728670
> fix: Handle watcher context cancel

- e2e/testcases/multi_sync_test.go
This is currently a flaky assertion in some of the CI tests. Logging the objects should help with identifying the source of flakiness.
> test: log objects in validateReconcilerResource

- e2e/testdata/configsync-kcc/kcc/policy-member.yaml
The IAMPolicyMember must be deleted before the IAMServiceAccount in order to ensure proper cleanup.
See https://cloud.google.com/config-connector/docs/troubleshooting#update_error_with_iampolicy_iampartialpolicy_and_iampolicymember
> test: fix cleanup ordering of kcc resources

- e2e/testcases/reconciler_manager_test.go
- manifests/templates/reconciler-manager-configmap.yaml
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- scripts/lib/manifests.sh
The askpass sidecar is a container in the reconciler Pod akin to the other containers, but is treated differently and declared in code rather than the manifests. This inconsistency can be a gotcha and requires our other tooling to have special exceptions for parsing the image tag from code. This change makes the askpass sidecar consistent with the other reconciler containers.
Note this is intended as a non-functional refactor, so the overall behavior should be unchanged.
> refactor: move the askpass declaration to manifest

- Makefile
- Makefile.build
- Makefile.oss.prow
- build/all/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- pkg/hydrate/tool_util.go
This version is similar to the upstream release, but with several CVE fixes.
> fetch helm from patched GKE version

- build/all/Dockerfile
This contains CVE fixes for OS packages
> chore: bump debian base image

- Makefile
- Makefile.build
- Makefile.oss.prow
- Makefile.reconcilermanager
- build/all/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- pkg/hydrate/tool_util.go
This version is similar to the upstream release, but with several CVE fixes.
> fetch kustomize from patched GKE version

- e2e/nomostest/testwatcher/watch.go
- e2e/nomostest/validate.go
- Add generation & resource version to WatchObject log message
Hopefully, these should make it easier to debug e2e test failures.
> test: Log object YAML on validate failure

- e2e/testcases/reconciler_manager_test.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
The reconciler manager validates the R*Sync first before finalizing it. If the R*Sync is invalid (e.g. missing git-creds), the validation error results in the failure to finalize the object.
This commit skips the validatin if the R*Sync object has a deletion timestamp, so that it can still be finalized.
b/296270191
> Skip validating R*Sync if it has a deletion timestamp

- e2e/nomostest/metrics/expectations.go
- e2e/nomostest/metrics/validate.go
- e2e/nomostest/prometheus_metrics.go
- e2e/testcases/lifecycle_directives_test.go
- e2e/testcases/namespaces_test.go
- pkg/applier/applier.go
- pkg/metrics/record.go
- pkg/metrics/tagkeys.go
- pkg/metrics/views.go
- pkg/remediator/reconcile/reconciler.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/syncer/client/client.go
- pkg/syncer/metrics/metrics.go
- pkg/syncer/reconcile/apply.go
The type label was increasing the cardinality of metrics by a significant amount, especially when used with config connector or crossplane, which have hundreds or even thousands of CRDs.
So this removes the type label from all metrics, which should reduce the total number of metrics and the cost, especially when combined with high-commit repositories.
> fix: Remove 'type' label from all metrics

- e2e/testcases/otel_collector_test.go
- e2e/testdata/otel-collector/otel-cm-monarch-rejected-labels.yaml
This is a cleanup after https://github.com/GoogleContainerTools/kpt-config-sync/pull/817.
With `type` label removed from the original metrics, the attribute processor that force removes the tag will no longer create the error thus checking for the error condition is not needed.
Changed the error case to metrics fail to export due to the rejected labels by the Cloud Monarch.
> Modify the otel_collector_test error condition

- e2e/testdata/configsync-kcc/kcc/policy-member.yaml
The IAMPolicyMember must be deleted before the IAMServiceAccount in order to ensure proper cleanup.
See https://cloud.google.com/config-connector/docs/troubleshooting#update_error_with_iampolicy_iampartialpolicy_and_iampolicymember
> test: fix cleanup ordering of kcc resources (#799)

- e2e/nomostest/wait_for_sync.go
WatchForSync now also waits for Current kstatus, meaning the reconciler-manager is done Reconciling the reconciler and is not Failed/Stalled.
> test: Wait for Current + Synced

- e2e/testcases/reconciler_manager_test.go
- manifests/templates/reconciler-manager-configmap.yaml
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- scripts/lib/manifests.sh
The askpass sidecar is a container in the reconciler Pod akin to the other containers, but is treated differently and declared in code rather than the manifests. This inconsistency can be a gotcha and requires our other tooling to have special exceptions for parsing the image tag from code. This change makes the askpass sidecar consistent with the other reconciler containers.
Note this is intended as a non-functional refactor, so the overall behavior should be unchanged.
> refactor: move the askpass declaration to manifest (#790)

- e2e/testcases/multi_sync_test.go
This is currently a flaky assertion in some of the CI tests. Logging the objects should help with identifying the source of flakiness.
> test: log objects in validateReconcilerResource (#795)

- pkg/parse/cache.go
- pkg/parse/run.go
- pkg/parse/run_test.go
- pkg/parse/state.go
Currently, the retry behavior for different triggers are different. When the trigger is managementConflict, it waits 5 seconds between retries. When the trigger is watchUpdate, it retries every second. When the trigger is the fact that the last reconciliation failed, it retries every second for the first 5 retires, and then does exponential backoff retry up to 5 minutes.
This PR unifies the retry behavior for these three triggers with backoff
+ jitter (inital duration: 1s; factor: 2; jitter: 0.1). There can be up to 12 retries for a given commit.
b/289254423
> Improve the retry behavior (#812)

- build/all/Dockerfile
This contains CVE fixes for OS packages
> chore: bump debian base image (#810)

- Makefile
- Makefile.build
- Makefile.oss.prow
- build/all/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- pkg/hydrate/tool_util.go
This version is similar to the upstream release, but with several CVE fixes.
> fetch helm from patched GKE version (#806)

- e2e/testcases/otel_collector_test.go
- go.mod
- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
This should reduce the number of unique metrics recorded and the cost of using Config Sync with Google Cloud Monitoring. Prometheus metrics still include the commit, to facilitate metrics validation.
Extracted:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/827
> Aggregate commit label for GCM metrics

- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/filteredwatcher_test.go
- pkg/remediator/watch/manager.go
- pkg/status/internal_error.go
Update the remediator's filteredwatcher to handle context cancellation, which is used to shut down the remediator. Previously, the cancel error was treated as any other error and the watcher would restart repeatedly until hitting the retry timeout (~4m). Now it should exit more quickly.
This also avoids logging the confusing watch error, `unable to decode an event from the watch stream`, when the context is cancelled during normal execution.
b/281728670
> Cherrypick: fix: Handle watcher context cancel (#792)

- e2e/testcases/reconciler_manager_test.go
With the change in #814, test case 6 in `TestManagingReconciler` will only bump generation by 1 in both standard and autopilot cluster
> Fix TestManagingReconciler

- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
It fixes an issue introduced in #790, and also updates the unit test to validate the injection.
> Inject GSA email to root-reconciler when using FWI (#856)

- e2e/testcases/stress_test.go
- pkg/client/restconfig/config.go
Based on demand by a few customers, we will remove client-side throttling from nomos status
> Remove client-side throttling from nomos status

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
Previously, printTestLogs is in its own cleanup block to catch fatal errors from the reset block.
Now we decided to reset after `printTestLogs`, so we can combine them into a single block for simplicity.
It also prints test logs if reset fails.
The `testPods` function is also renamed to `listAndDescribePods` to print the pod describe info, which shows the reason for pod restarts.
The purpose of the change is to capture pods describe info before RSync is deleted or reset.
> Add more logs when the test fails

- e2e/nomostest/testpredicates/predicates.go
- e2e/testcases/override_resource_limits_test.go
- e2e/testcases/reconciler_manager_test.go
- pkg/reconciler/finalizer/reposync_finalizer.go
- pkg/reconciler/finalizer/reposync_finalizer_test.go
- pkg/reconciler/finalizer/rootsync_finalizer.go
- pkg/reconciler/finalizer/rootsync_finalizer_test.go
- pkg/reconcilermanager/controllers/create_or_update.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/status/api_server_error.go
- pkg/util/mutate/mutate.go
- pkg/util/mutate/mutate_test.go
Status updates should retry if the error is recoverable, especially if it's just a ResourceVersion conflict, as long as the generation hasn't changed. This should reduce unnecessary reconcile loops and API calls in the reconciler-manager and reconciler finalizer.
> fix: Retry status updates

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
Previously, printTestLogs is in its own cleanup block to catch fatal errors from the reset block.
Now we decided to reset after `printTestLogs`, so we can combine them into a single block for simplicity.
It also prints test logs if reset fails.
The `testPods` function is also renamed to `listAndDescribePods` to print the pod describe info, which shows the reason for pod restarts.
> Merge reset and printTestLogs into a single cleanup block (#861)

- e2e/nomostest/testpredicates/predicates.go
- e2e/testcases/composition_test.go
TestComposition was testing ResourceVersion, when it should have been testing Generation. Status changes should be allowed and expected when changing the spec. Should make this test less flakey, especially on autopilot where node pool updates are common and can cause eviction & rescheduling of the reconciler and reconciler-manager.
> test: Fix TestComposition to allow status changes

- pkg/applier/applier.go
Add missing metrics for delete failure (APICallDuration, ApplyOperation).
> fix: Record metrics when delete fails

- e2e/testcases/stress_test.go
This should slightly speed up listing in stress tests and reduce memory allocation.
> test: Use partial metadata when counting lists

- docs/design-docs/01-explicit-only-namespace-strategy.md
This proposal suggests adding support for an annotation `configsync.gke.io/namespace-strategy`, with values `implicit` (the default) or `explicit`. By setting the annotation to `explicit`, setups like #207 become possible without resource fights.
> Proposal: Explicit-only namespace strategy for RootSyncs

- Makefile
- Makefile.build
The buildenv image is used for several presubmit targets, which means that this image needed to be published before the change is approved/submitted. This is a bit of an anti-pattern, as the change should be reviewed/approved before the image is published. This change enables the presubmits to run on a new image version before it is published, so that the image can be published after submission.
> ci: enable presubmits on new buildenv before publishing

- docs/development.md
The e2e scaffolding now supports providing num-clusters for both kind and GKE.
> docs: fix description of num-clusters flag

- Makefile
- Makefile.build
- build/buildenv/Dockerfile
- build/prow/gke-e2e/Dockerfile
- build/test-e2e-go/kind/Dockerfile
- scripts/test-unit.sh
We need to update the go version to fix CVEs.
This commit updates the test images first, so that we can build and push the gke-e2e image from a commit on the main branch.
We'll have a following commit to update go versions used by Config Sync components.
> Update go version in the test images

- Makefile
- Makefile.build
Some of our make targets use bash syntax, which requires for the shell used by make to be bash. Make uses sh by default, so the shell should be set explicitly here. This was a gotcha before, because some systems replace sh with bash. Explicitly setting the shell should help avoid future gotchas.
> fix: explicitly set makefile shell to bash

- pkg/hydrate/controller.go
- pkg/hydrate/controller_test.go
This PR adds commit SHA and syncDir to the hydration error payload, so that the rehydrateOnError function can get them directly without invoking hydrate.SourceCommitAndSyncDir.
> Store last hydration error in-memory for rehydrate

- build/test-e2e-go/e2e.sh
After upgrading to Go 1.20 there was a breaking change in the test output, in which resuming tests print NAME instead of CONT.
https://go-review.git.corp.google.com/c/go/+/443596
The go-junit-report utility does not properly parse NAME, so this hack replaces the output to look how it did before. The upstream go-junit-report should be fixed to properly parse the new gotest output format.
> ci: fix junit test output parsing

- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/resource_override.go
- pkg/api/configsync/v1beta1/resource_override.go
The askpass sidecar is supported by the overrides in code, but is rejected by the RSync API because it is not enumerated in the CRD. This change enables overriding the askpass container via the RSync.
> fix: add askpass to override container enum

- pkg/reconcilermanager/controllers/reconciler_container_resources.go
The askpass sidecar is failing regularly on autopilot due to timing out before the request can be served. This seems to be an issue of insufficient CPU to serve the request within the 1s timeout. The new value seems to pass consistently from experimentation. Intermediate values of 20m and 30m were tested but still flaky.
> fix: increase default cpuRequest for askpass

- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/resource_override.go
- pkg/api/configsync/v1beta1/resource_override.go
The support for otel-agent overrides has already been implemented in code, but was not allowed on the RSync api since it was not enumerated on the CRD.
> fix: add otel-agent to override api

- pkg/reconcilermanager/controllers/reconciler_container_resources.go
The helm-sync container is failing regularly on autopilot due to OOMKill. Autopilot sets the limits equal to the requests, and the current value is too low for all of the e2e tests to pass. Standard allows bursting while autopilot does not. We may be able to revert this increase after an upcoming change which will allow separate defaults for standard and autopilot.
> fix: increase default memoryRequest for helm-sync

- cmd/nomoserrors/examples/examples.go
- e2e/testcases/cli_test.go
- pkg/vet/api_resources.go
- pkg/vet/api_resources_test.go
`APIGROUP` column name has been [replaced](https://github.com/kubernetes/kubernetes/pull/95253) from Kubernetes v1.20 onwards with `APIVERSION`. This has broken the usage of `api-resources.txt` with Nomos command for users using Kubernetes v1.20 or newer. 
[b/299337751](http://b/299337751)
> Nomos CLI: replace APIGROUP with APIVERSION

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_base_test.go
The deleteDeploymentFields function was mutating the passed in pointer when deleting the allowList fields. This caused the Deployment patch data to be missing any of the allowListed fields if set. The reconciler Deployment does not contain any of the allowListed fields by default, but these fields can be patched in the reconciler-manager-cm ConfigMap by users.
The allow-listed fields are intended to be ignored when comparing the declared to the actual object to allow drift, but we should still apply the Deployment as it is declared.
> fix: persist deployment fields during allowListing

- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- pkg/api/configsync/register.go
- pkg/api/configsync/v1alpha1/getters.go
- pkg/api/configsync/v1alpha1/gitconfig.go
- pkg/api/configsync/v1beta1/getters.go
- pkg/api/configsync/v1beta1/gitconfig.go
- pkg/reconcilermanager/controllers/gitsync_env.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/util.go
`git-sync` v4 has a bunch of improvement, such as efficiency, and closing the race condition where a symbolic name can change after `git ls-remote` but before `git fetch`. It also addresses the missing error file when `git clone` is slow.
Most of the env variables are backward compatible, but this commit updates the env variable names to avoid jamming the git-sync logs.
> Migrate to git-sync v4

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_base_test.go
The deleteDeploymentFields function was mutating the passed in pointer when deleting the allowList fields. This caused the Deployment patch data to be missing any of the allowListed fields if set. The reconciler Deployment does not contain any of the allowListed fields by default, but these fields can be patched in the reconciler-manager-cm ConfigMap by users.
The allow-listed fields are intended to be ignored when comparing the declared to the actual object to allow drift, but we should still apply the Deployment as it is declared.
> [CHERRY-PICK] fix: persist deployment fields during allowListing (#898)

- e2e/testcases/policy_dir_test.go
- pkg/hydrate/controller.go
- pkg/hydrate/controller_test.go
- pkg/parse/run.go
- pkg/parse/run_test.go
- pkg/parse/source.go
- pkg/parse/source_test.go
- pkg/util/retry.go
If the internal retry fails eventually, it returns an internal error and surfaces the error in the R*Sync status field.
> Add internal retry for SourceCommitAndDir and readHydratedDir

- e2e/testcases/override_resource_limits_test.go
- e2e/testcases/reconciler_manager_test.go
- e2e/testcases/stress_test.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_base_test.go
- pkg/reconcilermanager/controllers/reconciler_container_resources.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/util/autopilot.go
- Increase requests & limits on autopilot to avoid OOMKill and
CPU throttling. Leave standard defaults alone, to continue
using boosting above the minimal requests.
- Clean up createOrPatchDeployment impl
- Use a fake autopilot webhook to test autopilot enablement
- Add TestStressMemoryUsage to test maximum number of supported objects with 100 CRDs and 50 objects each
Depends On:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/876
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/882
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/910
Proposal: [go/config-sync-reconciler-profiling](http://goto.google.com/config-sync-reconciler-profiling)
b/300294367
> fix: Increase reconciler resources on autopilot

- pkg/reconcilermanager/controllers/reconciler_container_resources.go
Reason for revert: The problems solved by these commits have been fixed
by using autopilot-specific defaults
> revert resource increases

- pkg/hydrate/controller_test.go
- pkg/parse/run_test.go
- pkg/parse/source_test.go
Some unit tests failed intermittently because the test directory wasn't created in the retryCap. This commit increases the cap. It also makes the backoff step consistent.
> Tune retryCap used in unit test to fix flakiness

- e2e/nomostest/testshell/shell.go
The ExecWithDebug function is invoked to run `nomos status`, which requires the KUBECONFIG env variable to be set. Otherwise, `nomos status` will fail with no cluster info, for example, https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-rapid-latest-stress/1709417838403391488.
> test: Fix the missing KUBECONFIG env variable

- e2e/testcases/otel_collector_test.go
- e2e/testdata/otel-collector/otel-cm-monarch-rejected-labels.yaml
- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/third_party/resourcegroup-manifest.yaml
- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
The currently used version 0.54.0 has two fixable vulnerabilities, which requires to update jaeger to 1.47.0.
The openTelemetry-collector-contrib versions that are earlier than 0.85.0 use jaeger 1.41.0 or older.
Hence, this commit updates the image to the latest version, which unfortunately introduces breaking changes.
This commit includes the following changes:
- removed `--feature-gates=-exporter.googlecloud.OTLPDirect` because feature gate "exporter.googlecloud.OTLPDirect" is stable, can not be disabled.
- removed retry_on_failure because it was from the googlecloud exporter. The exporter itself handles retries, and retrying can cause issues. (#57233)
- appended _ratio to the gauge metric names in the prometheus metrics valiation functions, because prometheus transformer appends _ratio …
> Update otelcontribcol image from 0.54.0 to 0.86.0

- manifests/templates/reconciler-manager-configmap.yaml
This is not a cherrypick commit from the main branch because the git-sync version diverges from the main branch.
> Update git-sync version for CVE fixes

- e2e/testcases/otel_collector_test.go
- e2e/testdata/otel-collector/otel-cm-monarch-rejected-labels.yaml
- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/third_party/resourcegroup-manifest.yaml
- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
The currently used version 0.54.0 has two fixable vulnerabilities, which requires to update jaeger to 1.47.0.
The openTelemetry-collector-contrib versions that are earlier than 0.85.0 use jaeger 1.41.0 or older.
Hence, this commit updates the image to the latest version, which unfortunately introduces breaking changes.
This commit includes the following changes:
- removed `--feature-gates=-exporter.googlecloud.OTLPDirect` because feature gate "exporter.googlecloud.OTLPDirect" is stable, can not be disabled.
- removed retry_on_failure because it was from the googlecloud exporter. The exporter itself handles retries, and retrying can cause issues. (#57233)
- added `--feature-gates=pkg.translator.prometheus.NormalizeName` to enable metric suffix trimming because the prometheus transformer …
> Update otelcontribcol image from 0.54.0 to 0.86.0 (#916)

- manifests/operator/kustomization.yaml
The policy-controller-psp was removed by a separate commit, but the inclusion in this kustomization file was overlooked.
The manifest was removed in https://github.com/GoogleContainerTools/kpt-config-sync/pull/909
> fix: remove policy-controller-psp from operator

- e2e/nomostest/new.go
- e2e/testdata/autopilot-keepalive/deployment.yaml
- go.mod
- Add a persistent Deployment on GKE Autopilot clusters to prevent scale-to-zero. This prevents metric-server from becoming unhealthy and breaking API discovery. b/209800496
> test: Prevent autopilot scale-to-zero

- Makefile
- build/buildenv/Dockerfile
- scripts/build.sh
The upx package was being used to compress the nomos binary as part of the build process. upx poses a few problems:
- Compressed binaries cannot be scanned for packages (SBOM)
- The upx package is not available on bookworm package manager
> ci: remove upx from CLI build

- e2e/nomostest/new.go
- go.mod
The keepalive deployment was not being parsed since it was using the wrong yaml parser. This changes the import to use the k8s parser.
> fix: use k8s yaml parser to unmarshal

- Makefile.build
This was missed during a rebase, and is required to set up docker auth for the correct registry host (e.g. GAR).
> fix: specify registry for auth-docker

- Makefile
- Makefile.e2e
- Makefile.oss.prow
This change adds the crane binary to the execution environments for e2e tests. The crane binary is intended to be used by the test framework to push OCI images during test execution.
> ci: add crane binary to e2e environments

- e2e/testdata/root-sync-helm-chart-cr.yaml
The override setting is borrowed from
https://github.com/GoogleContainerTools/kpt-config-sync/pull/665/files#diff-d79a2bfd62bc74a4236bb679fd53f68e6e7618a1e04fb3b7788add5e36a64243.
This is to fix the test flakiness on the v1.16 branch.  The main branch  does not have the flakiness.
> Override the resource requests for helm-sync to address the flakiness of TestPublicHelm

- manifests/templates/reconciler-manager-configmap.yaml
note - this commit is not a cherry pick. The main branch has moved forward a major version which contains breaking changes. This commit upgrades the patch version on the release branch to avoid breaking changes.
> chore: bump git-sync for security fixes

- .dockerignore
- Makefile
- build/buildenv/Dockerfile
- scripts/generate-clientset.sh
- scripts/license-headers.sh
- scripts/lint-bash.sh
This refactors the test-presubmit entrypoint to wrap the entrypoint and all nested targets in a single container. This ensures that all of the presubmit targets run inside the same nested container. Before this change, some targets such as tidy/vendor ran on the host machine. This also has the benefit on minimizing the number of extra containers that need to be pulled and/or created.
> ci: run all of test-presubmit in a single container

- Makefile
- Makefile.e2e.ci
This change publishes the buildenv image in the postsubmit target if the image tag does not already exist. This removes any need for manual steps to publish a new buildenv image.
> ci: publish buildenv in postsubmit

- docs/design-docs/01-explicit-only-namespace-strategy.md
- docs/design-docs/02-custom-root-reconciler-clusterrole.md
- e2e/testcases/reconciler_manager_test.go
- e2e/testcases/root_sync_test.go
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1beta1/resource_override.go
- pkg/core/names.go
- pkg/reconcilermanager/controllers/build_names.go
- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
Closes #935.
This introduces a new override for `RootSync`s, which allows customization of which `ClusterRole` to bind the reconciler's service account to. The default is `cluster-admin`, which is the same as what was done before this change. For more details, see the included design document.
> Custom ClusterRole for RootSync reconcilers

- manifests/templates/reconciler-manager-configmap.yaml
This includes security fixes for the previous version. Note this is not a cherry-pick as the main branch has moved forward to a new major version which includes breaking changes.
> chore: bump git-sync to v3.6.9-gke.5

- e2e/nomostest/artifactregistry/helm.go
- e2e/nomostest/artifactregistry/image.go
Helm is still unable to retrieve from AR using empty version if the version has suffixes, so we're removing version suffix addition. Chart version that exceed 20 characters will throw an error
> TestHelmLatestVersion: Remove helm chart version suffix

- cmd/nomos/README.md
This change updates the Nomos CLI README by fixing a broken link and clarifying the CLI is not limited to ACM.
> docs: update nomos cli readme

- cmd/gen-core-scoper/main.go
- cmd/nomos/initialize/init.go
- cmd/nomos/migrate/migrate.go
- cmd/nomos/parse/find_files_test.go
- cmd/nomos/status/status.go
- cmd/nomos/version/version.go
- e2e/nomostest/artifactregistry/yaml.go
- e2e/nomostest/config_sync.go
- e2e/nomostest/docker.go
- e2e/nomostest/gitproviders/repository.go
- e2e/nomostest/new.go
- e2e/nomostest/ssh.go
- e2e/testcases/admission_test.go
- e2e/testcases/cli_test.go
- e2e/testcases/custom_resource_definitions_schema_test.go
- e2e/testcases/custom_resource_definitions_test.go
- e2e/testcases/managed_resources_test.go
- e2e/testcases/oci_sync_test.go
- e2e/testcases/stress_test.go
- pkg/bugreport/bugreport.go
- pkg/hydrate/controller.go
- pkg/hydrate/tool_util.go
- pkg/importer/filesystem/filesystemtest/test_dir.go
- pkg/importer/reader/parse_file.go
- pkg/reconcilermanager/controllers/parse.go
- pkg/testing/openapitest/doc.go
- pkg/util/log/logging.go
- pkg/vet/api_resources.go
This change removes uses of the deprecated [io/ioutil](https://pkg.go.dev/io/ioutil) package, moving any uses to the [io](https://pkg.go.dev/io) and [os](https://pkg.go.dev/os) packages.
> refactor: remove uses of deprecated io/ioutil package

- e2e/nomostest/config_sync.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/reset.go
- e2e/testcases/otel_collector_test.go
- pkg/api/configmanagement/register.go
- pkg/bugreport/bugreport.go
- pkg/bugreport/constants.go
- pkg/importer/analyzer/validation/nonhierarchical/illegal_namespace_validator.go
- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
- pkg/reconcilermanager/controllers/otel_sa_controller.go
- pkg/validate/raw/validate/namespace_validator_test.go
Config Sync checks and errors out if config-management-system namespace is declared in SoT. 
This PR extends the check to config-management-monitoring namespace and resource-group-controller to avoid accidental modification or removal to the managed namespaces.
> Validate all Config Sync controller Namespaces

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_container_log_level.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
After the refactor in https://github.com/GoogleContainerTools/kpt-config-sync/pull/876, reconciler container log level will only be configured after override is specified. To mitigate this, the default log level value will be set earlier alongside the container resource.
Also in this PR, removed some hardcoded log level value and updated unit test data.
> Set default log level value and configure at runtime

- docs/design-docs/02-custom-root-reconciler-clusterrole.md
The roleRefs field is intended to allow more flexible and simple management of bindings for both RootSync and RepoSync objects. The field allows a list of references to Role and ClusterRole objects. For RepoSyncs, this will always create a RoleBinding in the same namespace as the RepoSync. For RootSyncs, the user can either choose to create a RoleBinding or ClusterRoleBinding via the namespace field.
This is an iteration upon the previous design which added a single ClusterRoleBinding configuration for RootSyncs. This design allows more flexible configuration for RootSyncs, as well as a consistent API for RepoSyncs which simplifies the management of RepoSync RoleBindings.
Issue: https://github.com/GoogleContainerTools/kpt-config-sync/issues/935
Iterates on this PR: …
> docs: add design doc for RSync roleRefs

- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
The RoleBinding created for RepoSyncs is actually in the namespace of the RepoSync, rather than the controller namespace. This change fixes the watch configuration and mapping logic to correctly map the RoleBinding.
> fix: map RepoSync RoleBinding to RepoSync namespace

- pkg/core/names.go
This prefix was unintentionally changed to the wrong value in https://github.com/GoogleContainerTools/kpt-config-sync/pull/938
> fix: use GroupName for RootSyncPermissionPrefix

- e2e/nomostest/gitproviders/bitbucket.go
Bitbucket now has three types of access tokens, repository access token, project access token and workspace access token:
https://developer.atlassian.com/cloud/bitbucket/rest/intro/#access-tokens.
The config-sync-ci-bot account only has access to the repository access token. The other two requires upgrading to premium plan.
The repository access token only allows listing repositories with the project filter. Hence this commit as a query to the list call.
b/308221985
b/308219656
> Fixes the bitbucket API failures

- Makefile
- Makefile.build
- Makefile.e2e
- Makefile.oss.prow
- Makefile.reconcilermanager
- scripts/install-helm.sh
- scripts/install-kustomize.sh
Move install out to bash scripts for safer execution, linting, trap function cleanup, and conditional install with verion checking.
> Skip helm/kustomize install when version matches

- e2e/nomostest/testpredicates/predicates.go
- e2e/testcases/override_log_level_test.go
Add validation for container args in reconciler and add e2e test scenario for overriding log level API
b/308638701
> Add container args validation and e2e test for log verbosity override

- build/all/Dockerfile
Several images using the same debian-nonroot base were performing similar apt-get update/install calls. Consolidating these to a single layer should improve runtime.
> consolidate apt-get calls to a single layer

- .dockerignore
- build/prow/e2e/Dockerfile.dockerignore
This is intended to reduce the time to build the core docker images by only copying needed files into the docker context.
> copy only needed files to docker context

- e2e/nomostest/testpredicates/predicates.go
- e2e/nomostest/testresourcegroup/resourcegroup.go
- e2e/testcases/kcc_test.go
- e2e/testcases/resource_group_controller_test.go
- e2e/testcases/stress_test.go
This implements the e2e test cases as they are defined in the upstream ResourceGroup repository. Implementing these tests here will enable migrating the remaining controller logic and API definitions to this repository.
> test: migrate ResourceGroup e2e tests to this repo

- e2e/nomostest/gitproviders/bitbucket.go
The BitBucket CI's current workspace is config-sync-ci-bot. There is a repository which is stuck in deletion. The DELETE request failed with a `Repository currently not available` error. The UI page for that repository is not responding.
The BitBucket system status shows the API is operational: https://bitbucket.status.atlassian.com/, but there was an increased error rate across API, GIT, Pipelines and other operations on Nov 8, 2023. The Bot account is a free account, so we can't get one-to-one support on this issue.
As a workaround, we deleted the stuck workspace and created a new one. Unfortunately, the old workspace ID can't be reused, so this commit updates the workspace ID.
> test: use a new bitbucket workspace for CI test

- e2e/testcases/kcc_test.go
- e2e/testcases/stress_test.go
These recently added test cases for ResourceGroup do not match the expected pattern for KCC and stress tests. This change will make it so that the periodic jobs properly run these tests.
> test: fix name pattern of kcc and stress test

- scripts/lint-go.sh
This simplifies the tooling for the go linter and makes it more consistent with our similar tooling. This also removes the reliance on wget to fetch the binary.
> use go install for golangci-lint

- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/gitconfig.go
- pkg/api/configsync/v1beta1/gitconfig.go
- pkg/reconcilermanager/controllers/gitsync_env.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
`spec.git.branch` is not technically deprecated. Users can still use it for backward compatibility. It is not recommended.
This commit clarifies the description.
> Sync from the branch if git.rev is empty or HEAD

- e2e/testcases/helm_sync_test.go
- e2e/testcases/hydration_test.go
- e2e/testcases/namespace_repo_test.go
- e2e/testcases/no_ssl_verify_test.go
- e2e/testcases/override_git_sync_depth_test.go
- e2e/testcases/override_resource_limits_test.go
- e2e/testcases/private_cert_secret_test.go
- e2e/testcases/reconciler_manager_test.go
- e2e/testcases/root_sync_test.go
- pkg/api/configmanagement/v1/constants.go
- pkg/parse/source.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/secret_test.go
v1.NSConfigManagementSystem can be replaced by
configsync.ControllerNamespace. This simplifies a followup PR that restructures the configmanagement/v1 APIs.
> Remove a redefined constant

- e2e/nomostest/config-connector.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
Apply config sync, prometheus, and config connector async. This should speed up test setup, since some of these take a minutes to reconcile.
> test: wait for test dependencies asyncronously

- pkg/api/configmanagement/v1/types.go
This commit configures the scope and the apiVersion of those CRDs. If the scope is not set, the scope of those CRD manifests will be set to Namespaced after regeneration.
Setting the apiVersion is for preparation of moving some types into a separate package.
> Add the scope marker to ConfigManagement CRDs

- cmd/nomos/bugreport/bugreport.go
- cmd/nomos/nomos.go
Before:
```
Flags:
-h, --help   help for nomos
```
After
```
Flags:
--add_dir_header                   If true, adds the file directory to the header of the log messages
--alsologtostderr                  log to standard error as well as files (no effect when -logtostderr=true)
-h, --help                             help for nomos
--kubeconfig string                Path to the client config file.
--log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
--log_dir string                   If non-empty, write log files in this directory (no effect when -logtostderr=true)
--log_file string                  If non-empty, use this log file (no effect when -logtostderr=true)
--log_file_max_size uint           Defines the maximum size a log file can grow …
```
> feat: Add klog flags to nomos cli

- cmd/nomos/nomos.go
- pkg/client/restconfig/config.go
- pkg/client/restconfig/restconfig.go
Work around a controller-runtime quirk that was causing nomos not to have a default KUBECONFIG value.
> fix: nomos default kubeconfig path

- Makefile.reconcilermanager
- manifests/cluster-selector-crd.yaml
- manifests/hierarchyconfig-crd.yaml
- manifests/namespace-selector-crd.yaml
- manifests/patch/kustomization.yaml
- pkg/api/configmanagement/v1/types.go
- pkg/status/error.go
The following manifests haven't been updated and are not auto-generated:
- cluster-selector-crd.yaml
- hierachyconfig-crd.yaml
- namespace-selector-crd.yaml
This commit updates the configsync-crd target to include them in the auto-generated manifests.
> Auto-generate manifests for ConfigManagement CRDs

- Makefile
- scripts/lint-go.sh
Install with "go install" into .output/go/bin, instead of the local user's $GOPATH/bin.
The latest versions of go install respect GOPATH, but not GOBIN. But we can't set GOPATH as a global in the Makefile, otherwise we wouldn't be able to build, cache, and vendor using the system Go.
> test: fix go linter install

- e2e/nomostest/config-connector.go
Use unstructured watching to avoid needing to import the ConfigConnector client lib and add the resources to the scheme.
> test: fix ConfigConnector watch

- cmd/reconciler/main.go
- pkg/parse/run.go
- pkg/reconciler/namespacecontroller/namespace_controller.go
- pkg/reconciler/namespacecontroller/namespace_predicate.go
- pkg/reconciler/namespacecontroller/state.go
- pkg/reconciler/namespacecontroller/state_test.go
- pkg/reconciler/reconciler.go
- pkg/reconcilermanager/constants.go
The Namespace controller watches for Namespace events. If an event is detected, it checks whether the corresponding Namespace was previously selected or will be selected. If it does, it updates a flag to indicate a reconciliation needs to be executed by the reconciler.
> Add a new Namespace Controller

- e2e/nomostest/ssh.go
- e2e/testcases/private_cert_secret_test.go
- e2e/testcases/ssh_known_hosts_test.go
- pkg/reconcilermanager/controllers/gitsync_env.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
Currently config sync is not supporting known_host configuration for git connection over ssh. With this PR, we are updating the controller logic to check for `known_host` key in the secret. Also added e2e test for Root and Repo sync that demonstrates the end to end process of this feature.
go/cs-known-hosts
b/309005641
> Implement known_host ssh support

- e2e/testcases/override_role_refs_test.go
The validation for garbage collection was happening in parallel with the RootSync NotFound validation, which creates a race condition that can be exacerbated on autopilot. By waiting for the RootSync to be NotFound first, it should be guaranteed that all of the managed resources have been garbage collected.
Example test flake: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-autopilot-stable/1725176860112850944
> test: fix test flake for role ref on autopilot

- Makefile
- Makefile.build
- Makefile.reconcilermanager
- manifests/cluster-selector-crd.yaml
- manifests/hierarchyconfig-crd.yaml
- manifests/namespace-selector-crd.yaml
- manifests/reposync-crd.yaml
- manifests/resourcegroup-crd.yaml
- manifests/rootsync-crd.yaml
- scripts/generate-test-loggers.sh
- scripts/license-headers.sh
Install with "go install" into .output/go/bin, instead of the local user's $GOPATH/bin.
The latest versions of go install respect GOPATH, but not GOBIN. But we can't set GOPATH as a global in the Makefile, otherwise we wouldn't be able to build, cache, and vendor using the system Go.
> test: fix addlicense & controller-gen install

- cmd/reconciler/main.go
- pkg/metadata/annotations.go
- pkg/reconciler/reconciler.go
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/util.go
The reconciler-manager checks the
`configsync.gke.io/requries-ns-controller` annotation in the RSync object and sets the `ns-controller-requires` flag in the reconciler container if the annoation is true.
> Update the reconciler-manager to set the ns-controller-requires flag

- pkg/parse/namespace.go
- pkg/reconciler/reconciler.go
The scope is defined in the Updater, which is part of the `namespace` struct, so no need to redefine it.
> chore: remove scope from the namespace struct

- e2e/nomostest/new.go
- e2e/testcases/main_test.go
This change records time measurements for each test feature of the e2e tests and prints them out at the end of the suite. This is intended to help with tracking the duration of the sub-suites, and to help inform the sharding of test suites in the presubmits.
> test: add timing measurements for each e2e feature

- Makefile.e2e
The test-group1 job is currently taking the longest of the three test groups, and test-group2 is taking the shortest amount of time on average. This rebalances the test features with the intention of reducing variance in run time between groups.
> ci: rebalance e2e presubmit tests

- Makefile.gen
- clientgen/apis/clientset.go
- clientgen/apis/typed/configmanagement/v1/configmanagement_client.go
- clientgen/apis/typed/configmanagement/v1/fake/fake_clusterconfig.go
- clientgen/apis/typed/configmanagement/v1/fake/fake_clusterselector.go
- clientgen/apis/typed/configmanagement/v1/fake/fake_hierarchyconfig.go
- clientgen/apis/typed/configmanagement/v1/fake/fake_namespaceconfig.go
- clientgen/apis/typed/configmanagement/v1/fake/fake_namespaceselector.go
- clientgen/apis/typed/configmanagement/v1/fake/fake_repo.go
- clientgen/apis/typed/configmanagement/v1/fake/fake_sync.go
- clientgen/apis/typed/configsync/v1alpha1/configsync_client.go
- clientgen/apis/typed/configsync/v1beta1/configsync_client.go
- clientgen/apis/typed/hub/v1/hub_client.go
- clientgen/apis/typed/kpt.dev/v1alpha1/kpt.dev_client.go
- clientgen/informer/factory.go
The version for the clientgen tools was previously hard coded, which
required a manual update and allowed for drift from the k8s version
set in the go dependencies. Parsing the version from go.mod ensures
there is no drift by default.
Based on https://github.com/GoogleContainerTools/kpt-config-sync/pull/1041
> fix: get clientgen version from go.mod file

- cmd/nomos/hydrate/hydrate.go
- cmd/nomos/vet/vet_impl.go
- cmd/nomoserrors/examples/examples.go
- e2e/nomostest/testpredicates/predicates.go
- e2e/nomostest/webhook.go
- e2e/testcases/namespace_selectors_test.go
- pkg/api/configmanagement/v1/constants.go
- pkg/hydrate/for_each_cluster.go
- pkg/importer/analyzer/transform/selectors/namespace_selectors.go
- pkg/parse/namespace.go
- pkg/parse/repository_scope.go
- pkg/parse/root.go
- pkg/parse/root_test.go
- pkg/parse/run_test.go
- pkg/parse/source_test.go
- pkg/reconciler/reconciler.go
- pkg/validate/objects/raw.go
- pkg/validate/objects/scoped.go
- pkg/validate/raw/raw.go
- pkg/validate/scoped/hydrate/namespace_hydrator.go
- pkg/validate/scoped/hydrate/namespace_hydrator_test.go
- pkg/validate/scoped/scoped.go
- pkg/validate/validate.go
- pkg/validate/validate_test.go
Previously, NamespaceSelector only supports selecting namespace-scoped
resources whose labels match those labels of the Namespaces that are
statically declared in the source of truth.
This commit updates the NamespaceSelector to support selecting
dynmaic/on-cluster Namespaces as well.
When it applies the NamespaceSelector, it sends out a LIST request to
get all Namespaces and select resources match the on-cluster Namespaces.
> Implement the select mode in the NamespaceSelector API

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/secret.go
- pkg/reconcilermanager/controllers/secret_test.go
This change updates the label logic for the resources managed by reconciler-manager to apply a consistent set of rules.
- Apply the sync-kind and sync-namespace label for shared RBAC bindings, leaving out the sync-name field given that multiple RSyncs may be mapped to the same binding.
> fix: apply managed resource labels consistently

- e2e/nomostest/testpredicates/predicates.go
- e2e/testcases/reconciler_manager_test.go
- pkg/reconcilermanager/controllers/errors.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
Prior to this change, if one of the managed objects failed to reconcile during setup or teardown the error would get swallowed and the reconciler-manager would proceed. This resulted in the finalizer exiting prematurely if one of the deletions timed out while waiting to reconcile.
For example, on autopilot it has been observed that the Deployment deletion may timeout during reconcile. When this happens, the error is swallowed and the finalizer exits even if the other managed objects have not been deleted (e.g. ServiceAccount, ClusterRoleBinding, etc).
Example logs:
```
I1117 14:10:13.788408       1 rootsync_controller.go:376] controllers/RootSync "msg"="Deleting managed objects" "reconciler"="config-management-system/root-reconciler" "sync"="config-management-system/root-sync" …
```
> fix: setup/teardown keep finalizer on reconcile err

- e2e/testcases/namespace_selectors_test.go
- pkg/validate/scoped/hydrate/namespace_hydrator.go
- pkg/validate/scoped/hydrate/namespace_hydrator_test.go
`hasDynamicNSSelector` should only be set to true when the mode is set to `dynamic` explicitly. It was probably a merging issue that mistakenly sets the flag to true for unknown mode.
> fix: remove a false condition that sets the dynamic mode

- cmd/reconciler-manager/main.go
- e2e/nomostest/config_sync.go
- e2e/nomostest/wait_for_sync.go
- e2e/testcases/reconciler_manager_test.go
- go.mod
- go.sum
- pkg/api/configsync/register.go
- pkg/reconcilermanager/controllers/controller.go
- pkg/reconcilermanager/controllers/crd_controller.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/otel_sa_controller.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
- vendor/golang.org/x/exp/slices/cmp.go
- vendor/golang.org/x/exp/slices/slices.go
- vendor/golang.org/x/exp/slices/sort.go
- vendor/golang.org/x/exp/slices/zsortanyfunc.go
- vendor/golang.org/x/exp/slices/zsortordered.go
- vendor/modules.txt
Add a CRD controller that watches for CRD updates and registers the RSync controllers when the RSync CRDs become Established, meaning the resources are registered and availible for use.
This allows the RootSync and RepoSync controllers to come up independently, which can unblock uninstall when the CRDs are being deleted simultaniously, in case the reconciler-manager is restarted or rescheduled.
> fix: Delay RSync controller registration

- manifests/reposync-crd.yaml
- manifests/resourcegroup-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/sync_types.go
- pkg/api/configsync/v1beta1/sync_types.go
- pkg/api/kpt.dev/v1alpha1/resourcegroup_types.go
- pkg/parse/root_test.go
- pkg/validate/validate_test.go
Setting the default observedGeneration to 0 should ensure that it is initialized even when using Unstructured resources. This should prevent kstatus.Compute from considering the object to be Current before the controller has updated the status. This should prevent the Config Sync reconciler from considering the object to be reconciled and returning prematurely. This should prevent any dependencies from being applied or deleted prematurely, avoiding out of order problems.
> fix: Prevent RSync from premature Current status

- pkg/kinds/resources.go
- pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
- pkg/syncer/syncertest/fake/dynamic_client.go
- pkg/util/watch/until.go
Add unit tests for changes from #1066
Now that observedGeneration has a default, the status should always be non-Current until reconciliation is complete.
Validate this in setup by running a deployment controller simulator and validator in parallel.
Validate this in teardown by blocking teardown with a ServiceAccount finalizer.
b/315199932
> chore: Validate RSync reconciliation status

- pkg/metadata/labels.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/secret_test.go
This change adds a managed-by label which is applied uniformly to all
resources which are managed by the reconciler-manager. With the
existence of this new label, we can eventually add a label selector to
optimize the API calls of the reconciler-manager client. The selector is
not added right now due to backwards compatibility concerns, but can be
added in the future.
> feat: add managed-by label for manager

- .gitignore
- e2e/testinfra/terraform/prow/service_accounts.tf
This reflects the current project level permissions which have been manually applied.
> ci: add test runner iam to terraform config

- e2e/nomostest/git-server.go
The git-server is susceptible to eviction on autopilot, which can cause flakiness for many test cases. This annotation prevents autopilot workloads from being evicted for up to 7 days. The git-server deployment is scoped to a test execution, and therefore should not live longer than a few hours in the worst case.
> test: annotate git-server as not safe to evict

- e2e/testcases/multi_sync_test.go
Prior to this change the repositories used by the test were initialized before being tracked in RootRepos/NonRootRepos. This meant that if the git-server had to be repaired at any point during the test, the untracked repos would not be recreated. This updates the test to initialize the repos at the same time that they are tracked.
> test: fix multi sync test repo initialization

- e2e/testcases/namespace_selectors_test.go
- pkg/validate/scoped/hydrate/namespace_hydrator.go
- pkg/validate/scoped/hydrate/namespace_hydrator_test.go
`hasDynamicNSSelector` should only be set to true when the mode is set to `dynamic` explicitly. It was probably a merging issue that mistakenly sets the flag to true for unknown mode.
It also updates the namespace_selectors_test to avoid mutating the shared variable in two test cases, which causes test flakiness.
> fix: remove a false condition that sets the dynamic mode (#1059)

- e2e/nomostest/artifactregistry/image.go
- e2e/testcases/helm_sync_test.go
Updated TestHelmARTokenAuth to include code to auto-rotate expired service account keys and also repair a few edge cases, like no enabled secret versions, invalid secret version, latest secret version disabled/destroyed, etc. So as long as the service account exists and the secret exists, the code should be able to re-generate a valid key on-demand and add it as a new secret version.
Note: Because these steps are not atomic and might be run in parallel in the same project, it's possible that the test might fail due to concurrent regeneration, but it's unlikely due to the order of the steps. It's more likely that a duplicate key is ocationally generated, which shouldn't cause test failure. If this happens frequently, it might exceed the maximum 10 keys per account, but otherwise the keys …
> test: auto-rotate service account key & secret

- e2e/testcases/helm_sync_test.go
- e2e/testinfra/terraform/prow/service_accounts.tf
This change adds the GCP iam needed by the e2e test runner GSA, and adds
some logic to harden the secret rotation for certain edge cases.
Builds on https://github.com/GoogleContainerTools/kpt-config-sync/pull/1077
> test: address edge cases for e2e secret rotation

- e2e/testinfra/terraform/prow/service_accounts.tf
The email is invalid with id, and expects project_id. Also removes the redundant project prefix.
> fix: use project_id for GSA email

- e2e/testcases/helm_sync_test.go
Suppressing the user output also disabled output for the happy path where a version exists. This reverts the behavior back to how it was before with an error check on the output.
> fix: enable user output for version list

- manifests/cluster-selector-crd.yaml
- manifests/hierarchyconfig-crd.yaml
- manifests/namespace-selector-crd.yaml
- manifests/reposync-crd.yaml
- manifests/resourcegroup-crd.yaml
- manifests/rootsync-crd.yaml
The license headers for the manifests are generated as part of the presubmits, and need to be bumped for the new year.
> chore: bump manifest headers to 2024

- pkg/askpass/askpass.go
- pkg/askpass/askpass_test.go
This should help avoid the credentials expiring before git has a chance to use them.
Fixes: b/316600701
> fix: Add 5m buffer time to askpass

- scripts/install-helm.sh
- scripts/install-kustomize.sh
This isn't a problem when you lint in the container with the right linter version, but is when you have a different version installed locally. I'd like it to work on my machine without needing to always lint in a container.
> chore: ignore self-assignment lint for validation

- manifests/cluster-selector-crd.yaml
- manifests/hierarchyconfig-crd.yaml
- manifests/namespace-selector-crd.yaml
- manifests/reposync-crd.yaml
- manifests/resourcegroup-crd.yaml
- manifests/rootsync-crd.yaml
The license headers for the manifests are generated as part of the presubmits, and need to be bumped for the new year.
(This is a workaround for a known automation bug that violates Google copyright update policy. Bug is in the backlog.)
> v1.17 cherry-pick: chore: bump manifest headers to 2024 (#1092)

- manifests/templates/admission-webhook.yaml
The field was added into the CS manifest in CS 1.13.0 (http://tg/1499888) to reduce errors and log spam: https://github.com/GoogleContainerTools/kpt-config-sync/blob/v1.13.0/manifests/templates/admission-webhook.yaml.
This is no longer needed since the behavior of cert-controller has been improved in
https://github.com/open-policy-agent/cert-controller/pull/48, and the cert-controller library has been updated in Config Sync in https://github.com/GoogleContainerTools/kpt-config-sync/pull/146.
Another reason to remove this field is that it causes nomos-operator to update the validatingwebhookconfigurations object constantly (b/316959632).
> Remove the `webhooks` field from the validatingwebhookconfigurations object

- e2e/testcases/override_log_level_test.go
- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/resource_override.go
- pkg/api/configsync/v1beta1/resource_override.go
- pkg/reconcilermanager/controllers/reconciler_container_log_level.go
- pkg/reconcilermanager/controllers/reconciler_container_log_level_test.go
The zap log levels become more verbose as the log level decreases, which is the inverse of how our other log levels operate. This change reverses the order of our logLevel API when translating it to a zap log level. This is intended to create more consistent API behavior between the different containers. The default continues to be INFO, which maps to the integer value of 5 in our new scheme.
> fix: reverse log level ordering for zap/otel-agent

- e2e/testcases/override_log_level_test.go
- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- manifests/templates/admission-webhook.yaml
- pkg/api/configsync/v1alpha1/resource_override.go
- pkg/api/configsync/v1beta1/resource_override.go
- pkg/reconcilermanager/controllers/reconciler_container_log_level.go
- pkg/reconcilermanager/controllers/reconciler_container_log_level_test.go
Cherry pick two last-minute changes for 1.17.1. 
Added the extra hydration-controller validation  commit to avoid merge conflicts.
> v1.17 cherry-pick: webhook fix & otel-agent log level fix

- pkg/reconcilermanager/controllers/reconciler_container_resources.go
The Config Sync Autopilot CI failures indicate the helm-sync container is hitting both OOMKilled and `signal: killed` (insufficient CPU) on Autopilot clusters.
- OOMKilled:
- autopilot regular: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-autopilot-regular/1745822836569673728
- autopilot stable: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-autopilot-stable/1745836426253045760
- insufficient CPU:
- autopilot rapid: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-autopilot-rapid/1745826108181319680
- autopilot rapid-latest: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-autopilot-rapid-latest/1745819564941250560
This commit increases the default …
> Increase the default memory/cpu requests for helm-sync on Autopilot clusters

- Makefile
The crane binary is used by some of the e2e tests, which can be run in a container which does not have glibc. Compiling with CGO causes an error when invoking the binary in such a container.
> ci: set CGO_ENABLED=0 for local crane binary

- e2e/nomostest/new.go
- e2e/nomostest/ntopts/multi_repo.go
- e2e/testcases/private_cert_secret_test.go
- e2e/testcases/ssh_known_hosts_test.go
This name avoids a double negative which helps readability.
> refactor: rename test opt to RequireLocalGitProvider

- cmd/helm-sync/main.go
- e2e/flags.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/multi_repo.go
- e2e/nomostest/registry_server.go
- e2e/nomostest/registryproviders/helm.go
- e2e/nomostest/registryproviders/local.go
- e2e/nomostest/registryproviders/registry_provider.go
- e2e/testcases/private_cert_secret_test.go
- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/v1alpha1/helmconfig.go
- pkg/api/configsync/v1beta1/helmconfig.go
- pkg/helm/helm.go
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/secret.go
- pkg/reconcilermanager/controllers/util.go
- pkg/reconcilermanager/controllers/util_test.go
This change adds a caCertSecretRef API field for the helm api which is analogous to the existing git/oci api fields. This can be used by users to provide a CA certificate for verifying the authenticity of the helm repository.
> feat: add CA cert support for helm-sync

- e2e/nomostest/client.go
- e2e/testcases/workload_identity_test.go
`workload_identity_test.go` defines a set of sub tests in a table driven format. Each sub test enables parallel execution with `t.Parallel()`. A go routine is created for each sub test. However, when it launches the go routines, the test case variables (the `tc` variable in the for loop iterator) are evaluated when the go routines run. Hence, by the time the go routine is actually executed, the for loop has completed, and each test ends up using the variables for the last test case.
To fix this issue, this commit rebinds the `tc` variable inside the loop. This creates a copy for the variable and go routine uses the local copy for execution.
It also adds the hubv1 schema because the test gets the Membership object to validate the Fleet workload identity credentials. loop
> test: fix test failures caused by sub tests running in parallel

- e2e/testcases/otel_collector_test.go
- e2e/testdata/otel-collector/otel-cm-kustomize-rejected-labels.yaml
- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
Remove the configsync.sync labels from Monarch pipeline for Kustomize metrics.
> Aggregate kustomize metrics labels

- e2e/testinfra/terraform/common/service_accounts.tf
- e2e/testinfra/terraform/prow/service_accounts.tf
The new k8sserviceaccount requires reader permissions to be granted to the KSA, along with the workload identity pool. This commit adds IAM settings as a one-off config.
> Add required IAM settings for the test infra

- build/prow/e2e/Dockerfile
The package name has transitioned to cli instead of sdk, and the sdk package is currently broken.
> fix: use google-cloud-cli package instead of sdk

- build/prow/e2e/Dockerfile
The package name has transitioned to cli instead of sdk, and the sdk package is currently broken.
> fix: use google-cloud-cli package instead of sdk (#1130)

- e2e/testcases/workload_identity_test.go
`workload_identity_test.go` should use the `imageDigestFuncByName` function to fetch the image digest.
> test: fix test failures with invalid image digest

- e2e/nomostest/config_sync.go
- e2e/nomostest/gitproviders/repository.go
- e2e/nomostest/ntopts/new.go
- e2e/nomostest/registry_server.go
- e2e/nomostest/registryproviders/helm.go
- e2e/nomostest/registryproviders/image.go
- e2e/nomostest/testkubeclient/object.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/oci_sync_test.go
- e2e/testcases/private_cert_secret_test.go
- e2e/testcases/stress_test.go
- e2e/testcases/workload_identity_test.go
Currently, it calls for a `UseHelmChart` function before building and pushing a Helm chart. The function resides inside the gitproviders package, which copies the test helm chart directory to the git local directory. Ideally, if the source type is changed from Git to Helm, it is not necessary to update the git repository.
This commit refactors the code to separate the helm repo dir from the git repo dir. When building and pushing a helm chart, it is optional to provide a test helm chart dir, any K8s objects, or a chart version.
It also makes similar changes to the oci provider.
> test: refactor helm provider to not depend on gitproviders

- manifests/templates/admission-webhook.yaml
- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
This restricts some of the default security context fields to follow principle of least privilege.
> fix: use more limited securityContext for pods

- e2e/nomostest/git-server.go
- e2e/nomostest/registry_server.go
- e2e/testdata/prometheus/prometheus.yaml
Autopilot now allows setting the safe-to-evict annotation to request an extended runtime of Pods. This change sets the annotation on each of the test components which use ephemeral storage, which should reduce flakiness. These Deployments are deleted at the end of test execution, which will allow scale down.
> test: prevent eviction of test pods

- Makefile.e2e
- docs/testing.md
This simplifies the naming of some of the e2e-kind test targets and updates the dev/testing docs with the current entrypoints.
> test: rename test-e2e-kind targets and dev docs

- Makefile.build
The test scaffolding uses
https://github.com/jkarlosb/git-server-docker/blob/v1.0.0/Dockerfile to set up a test-git-server. However, that repo uses git 2.8.3, which doesn't support the `--initial-branch` option for `git init`.
We need to set up a different default branch rather than `master`. This commit updates the Dockerfile by updating the alpine base image from 3.4 to 3.19, which comes with git 2.43.0.
It also updates the image tag by appending the commit hash.
> chore: update the base image of the test-git-server

- e2e/nomostest/new.go
- e2e/nomostest/ntopts/multi_repo.go
- e2e/nomostest/ntopts/new.go
- e2e/nomostest/registry_server.go
- e2e/nomostest/registryproviders/artifact_registry.go
- e2e/nomostest/registryproviders/local.go
- e2e/nomostest/registryproviders/registry_provider.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/oci_sync_test.go
- e2e/testcases/stress_test.go
The gcloud auth token only lasts 1 hour, so we need to re-auth for each test that uses helm or oci.
> e2e: Add registry login/logout to test setup

- e2e/nomostest/git-server.go
- e2e/testcases/git_sync_test.go
`git-sync` v4.1.0 couldn't pull the latest commit from a branch when the branch has multiple remotes and the branch in different remotes are out of sync.
This commit adds a test to confirm the behavior. A subsequent commit will update git-sync to v4.2.0 to fix this issue.
> test: add a test to confirm the git-sync not pulling latest issue

- Makefile
- e2e/testcases/git_sync_test.go
- manifests/templates/reconciler-manager-configmap.yaml
There is a bug in git-sync v4.1.0. When branches in different remotes
are out of sync, `git-sync` fetches the commit SHA from the last line,
which may not be the latest. This leads to an issue that Config Sync
couldn't pull the latest commit from HEAD.
The issue was fixed in v4.2.0 by
https://github.com/kubernetes/git-sync/pull/845.
This commit updates git-sync to v4.2.1 to include the fix.
It also bumps the debian-base to latest version for CVE fixes.
b/325341042
> fix: update git-sync to v4.2.1 to fix a pulling issue

- pkg/reconcilermanager/controllers/rootsync_controller.go
Config Sync doesn't generate a copy of root Secret, so no need to validate the generated secret name length.
b/326430718
> fix: stop validating root secrets (#1140)

- e2e/testcases/git_sync_test.go
Gitlab doesn't allow pushing a branch with `refs/remotes/upstream/*`. It failed with a `deny updating a hidden ref` error. This commit changes the remote branch to just `upstream/main`, which is `refs/heads/upstream/main`.
> test: update e2e test to fix gitlab push error (#1153)

- e2e/nomostest/nt.go
- e2e/nomostest/registry_server.go
- e2e/nomostest/registryproviders/artifact_registry.go
- e2e/nomostest/registryproviders/local.go
- e2e/nomostest/registryproviders/registry_provider.go
A recent refactor updated the cleanup logic to only delete images in cleanup for local registries. The registry state needs to be reset regardless of the registry type.
> test: fix registry cleanup to delete images after

- Makefile
- Makefile.build
- Makefile.e2e.ci
- Makefile.oss.prow
The infrastructure-public-image prefix advertises that these images are intended for use by end to end testing infrastrucutre.
> ci: tag all infra images with proper prefix

- Makefile.e2e.ci
This was accidentally removed in a previous PR
> fix: build-cli in postsubmit

- e2e/testinfra/terraform/prow/service_accounts.tf
The test runner GSA now needs permission to manage CSR repositories.
> ci: grant test runner CSR admin

- e2e/nomostest/config_sync.go
- e2e/nomostest/ssh.go
- e2e/testcases/composition_test.go
- e2e/testcases/git_sync_test.go
- e2e/testcases/invalid_auth_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/proxy_test.go
- e2e/testcases/reconciler_manager_test.go
- e2e/testinfra/terraform/modules/service_account/service_account.tf
https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2228 changes the default git provider from local to csr, which also changes the defalt git auth from ssh to gcpserviceaccount, which causes a bunch of testing failures and missing permissions.
This commit updates the tests to set the secret for non-csr git providers and also adds the missing IAM bindings.
> test: fix CI failures when running with --git-provider=csr

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/new.go
- e2e/testcases/cli_test.go
- scripts/e2e.sh
The tests that use the test wrapper directly instead of the nomostest entrypoint were not properly being skipped. This moves the skip logic to the shared entrypoint.
> test: properly skip tests that use test wrapper

- e2e/nomostest/gitproviders/bitbucket.go
Bitbucket failed to delete Git repositories in the old workspace: https://community.atlassian.com/t5/Bitbucket-questions/Unable-to-delete-Git-repositories-due-to-Repository-currently/qaq-p/2654436.
As a workaround, we created a new workspace. This commit updates the CI to create repos in the new workspace.
> test: use a new Bitbucket workspace

- pkg/metadata/annotations.go
- pkg/webhook/configuration/update.go
The annotation was added as a workaround to disable updating webhook configuration before preventDrift field was made available.
Users who might be relying on this annotation can switch to using the [preventDrift field](https://cloud.google.com/anthos-config-management/docs/how-to/prevent-config-drift).
> Remove unused annotation webhook-configuration-update

- Makefile
```
mikebz-ct src/kpt-config-sync λ make vulnerability-scan
./scripts/vulnerabilities.sh
++++ Parsing image tags from rendered manifests at: .output/staging
Scanning............
IMAGE                                                                                     VULNERABILITIES
gcr.io/config-management-release/git-sync:v4.2.1-gke.3__linux_amd64                       0
gcr.io/config-management-release/otelcontribcol:v0.91.0-gke.9                             0
gcr.io/mikebz-ex1/configsync/admission-webhook:v1.17.0-104-gb68be116-dirty                0
gcr.io/mikebz-ex1/configsync/gcenode-askpass-sidecar:v1.17.0-104-gb68be116-dirty          0
gcr.io/mikebz-ex1/configsync/helm-sync:v1.17.0-104-gb68be116-dirty                        0 …
```
> base image update for golang and debian bookworm

- pkg/parse/root.go
- pkg/reconciler/reconciler.go
- pkg/validate/scoped/hydrate/namespace_hydrator.go
- pkg/validate/scoped/hydrate/namespace_hydrator_test.go
- It only initializes `nsControllerState` when dynamicNSSelectorEnabled is true, so that pkg/parse/run.go can stop `nsEventTimer` when nsControllerState is nil.
- When namespace_hydrator selects dynamic/on-cluster Namespaces, it filters out terminating Namespaces because Kubernetes doesn't allow creating new content in terminating Namespaces.
> Improvements for the NamespaceSelector dynamic mode

- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
Change log https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.99.0
No breaking change applied to components used by Config Sync since 0.91.0.
Enhancements found for opencensusreceiver, filterprocessor, resourcedetectionprocessor.
> [chore] Bump otelcontribcol to 0.99.0-gke.1

- e2e/testcases/cli_test.go
- pkg/applier/applier.go
- pkg/applier/applier_err_test.go
- pkg/applier/applier_test.go
- pkg/applier/destroyer_test.go
- pkg/diff/precedence_test.go
- pkg/hydrate/controller_test.go
- pkg/kinds/convert_test.go
- pkg/kinds/lookup_test.go
- pkg/remediator/watch/manager_test.go
- pkg/status/multierror.go
- pkg/testing/testerrors/testerrors.go
- pkg/util/watch/options_test.go
- pkg/validate/objects/tree_test.go
- pkg/validate/raw/validate/cluster_selector_validator_test.go
- pkg/validate/raw/validate/disallowed_fields_validator_test.go
- Fix Applier/Destroyer.addError from wrapping/appending nil errors
- Add status.Wrap for wrapping status.Errors without an existing MultiError.
- Fix status.Append to avoid wrapping errors that are already a MultiError
- Add testerrors.AssertEqual to simplify testing status.Errors. Ideally we would just fix statis.Error.Is, but that would require fixing all our test assertions. This approach is a bit easier, so we can fix assertions a little at a time to make them more strict.
- Backfilled unit tests for ErrorForResourceWithResource
> Unwrap single status.MultiErrors

- pkg/status/error_builder.go
- pkg/status/error_impl.go
- pkg/status/management_conflict_error.go
- pkg/status/message_error_impl.go
- pkg/status/path_error_impl.go
- pkg/status/resource_error_impl.go
- pkg/status/wrapped_error_impl.go
- pkg/testing/testerrors/testerrors.go
- errors.Is performs a basic equality comparison on the input errors which panics if the errors are not comparable. This effectively requires errors to use pointers so that the pointer can be used for equality comparison.
- Update all status errors to use pointers. This has the added benefit of not repeatedly copying error field values every time an error is returned to a function caller.
- Update testerrors.AssertEqual to support asymetric equality comparison, which is performed by go-cmp.Equal when using the EquateErrors option.
> Fix status errors to work with errors.Is

- pkg/applier/applier_test.go
- pkg/hydrate/controller.go
- pkg/parse/repository_scope_test.go
- pkg/parse/root_test.go
- pkg/parse/run_test.go
- pkg/reconciler/finalizer/reposync_finalizer_test.go
- pkg/reconciler/finalizer/rootsync_finalizer_test.go
- pkg/remediator/reconcile/reconciler_test.go
- pkg/remediator/reconcile/worker_test.go
- pkg/remediator/watch/manager_test.go
- pkg/status/multierror.go
- pkg/status/multierror_test.go
- pkg/syncer/client/client_test.go
- pkg/util/clusterconfig/crd_test.go
- pkg/util/mutate/mutate_test.go
- pkg/util/retry.go
- Use testutil.AssertEqual in more places to validate both the error type and the error message.
- Update test expectations with more correct errors
- Fix a case of error wrapping with %v instead of %w
- Remove TestRoot_ParseErrorsMetricValidation, which used to test a metric that has been removed.
- Fix TestSortErrors which was expecting an incorrect ordering.
- Simplify status.Append to only allocate a slice and multiError when necessary.
- Add RetriableError.Is to make errors.Is work
> Test errors more strictly

- Makefile
just decided to update this while I was looking at other CVE fixes.
> chore: bumping up to golang:1.21.9-bookworm

- e2e/nomostest/clusterversion/cluster_version.go
- e2e/nomostest/clusterversion/cluster_version_test.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/testcases/custom_resource_definitions_test.go
- e2e/testcases/custom_resources_test.go
- e2e/testcases/multiversion_test.go
- Get the cluster version from the discovery client, parse it, and save it in the NT environment for use by tests.
- Update the v1beta1 CRD/RBAC check to use NT.ClusterVersion
- Update tests using the v1beta1 check to skip their test, not just return as successful.
- In the future, we can use the cluster version to check for autopilot resource bursting. But since resource bursting is temporarily disabled by default, we can't validate it today.
> Add e2e NT.ClusterVersion detection

- Makefile
This updates the golang base image to a trusted base image built by google.
> chore: use trusted golang base image

- e2e/testcases/managed_resources_test.go
The 30 second wait time used by these assertions works most of the time, but can be brittle in certain scenarios - for example if the reconciler Pod is rescheduled.
> test: use longer waits for managed field tests

- e2e/testcases/stress_test.go
This is intended to help with debugging when this predicate fails.
> test: print RootSync for truncateSourceError

- e2e/nomostest/new.go
This instantiates the base RootSync using SSA, which ensures that subsequent SSA calls will use the same field manager and update fields appropriately. This fixes the current TestStressLargeRequest failures.
This also ensures the RootSync spec is reset for every test, which is a desirable property.
> test: use SSA to create parent RootSync

- e2e/nomostest/new.go
This instantiates the base RootSync using SSA, which ensures that subsequent SSA calls will use the same field manager and update fields appropriately. This fixes the current TestStressLargeRequest failures.
This also ensures the RootSync spec is reset for every test, which is a desirable property.
> test: use SSA to create parent RootSync (#1227)

- scripts/vulnerabilities.sh
The 'gcloud container images describe' command returns two entries for the discovery_summary field. We only need the status from 'projects/goog-analysis/notes/PACKAGE_VULNERABILITY'. This commit adds a filter to ignore the COMPLIANCE scan result.
Example output:
```
{
"discovery_summary": {
"discovery": [
{
"createTime": "2024-05-27T01:18:40.728858Z",
"discovery": {
"analysisStatus": "FINISHED_SUCCESS",
"continuousAnalysis": "ACTIVE"
},
"kind": "DISCOVERY",
"name": "projects/config-management-release/occurrences/400738d4-d91e-46cc-abae-8bfb265a8f2e",
"noteName": "projects/goog-analysis/notes/COMPLIANCE",
"resourceUri": "https://gcr.io/config-management-release/otelcontribcol@sha256:2f93890991d10870bf0a04586522db3ced65a152ca3f0f30aa9961f82d72aea7",
"updateTime": …
```
> chore: filter vulnerability status by the analysis type

- pkg/metrics/metrics.go
- pkg/metrics/views.go
- pkg/resourcegroup/controllers/metrics/metrics.go
- pkg/resourcegroup/controllers/metrics/views.go
Some Config Sync metrics were appended _total suffix in the view file where the metric name finalizes, which creates confusion.
This change puts the naming in one place to reduce confusion.
> [metric] #1 Turn metric names to const

- pkg/testing/testmetrics/testexporter.go
This validation would panic if the got array was larger than the want array. This updates the validation logic so that it handles this case without panicking and returns a diff.
> test: fix panic in metric validation

- pkg/applier/applier.go
- pkg/applier/applier_test.go
- pkg/applier/destroyer_test.go
- pkg/applier/fake/applier.go
- pkg/applier/stats/stats.go
- pkg/parse/root_test.go
- pkg/parse/updater.go
- pkg/reconciler/finalizer/base_finalizer.go
- pkg/reconciler/finalizer/finalizer.go
- pkg/reconciler/finalizer/reposync_finalizer.go
- pkg/reconciler/finalizer/reposync_finalizer_test.go
- pkg/reconciler/finalizer/rootsync_finalizer.go
- pkg/reconciler/finalizer/rootsync_finalizer_test.go
Use an injected event handler function to avoid needing to cache errors in the supervisor. Instead, cache errors in the Updater, which already has a lock for this.
This event handler simplifies the Applier/Destroyer API and makes it easy to add more events in the future, like for inventory updates.
Dependencies:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1204
> Add event handler to Applier/Destroyer

- e2e/testcases/otel_collector_test.go
- e2e/testdata/otel-collector/otel-cm-full-gcm.yaml
- go.mod
- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
The metric name was changed to `current_declared_resources` using the metricstransform processor without communicating in the documentation / release note and the intention was unclear.
This change reverts the name change and adds e2e test around all the [available metrics](http://cloud/kubernetes-engine/enterprise/config-sync/docs/how-to/monitoring-config-sync) in GCM. The check skips the counter metrics for now as they have no data when no error condition has happened.
> [metric] #2 Revert declared_resources metric name

- e2e/testcases/otel_collector_test.go
- pkg/declared/resources.go
See the falsely closed PR https://github.com/GoogleContainerTools/kpt-config-sync/pull/1219 for context.
> [metric] #3 Reset the declared_resources metric when at a new commit [restored]

- e2e/nomostest/reset.go
https://community.atlassian.com/t5/Bitbucket-questions/Re-Re-Unable-to-delete-Git-repositories-due-to-Reposit/qaq-p/2719161/comment-id/104918#M104918 suggests creating repos incrementally rather than all at once.
This commit logs the creation timestamp to confirm whether these test repos are created all around the same time.
> test: log the repo creation timestamp

- pkg/parse/updater.go
Errors() was calling applyErrors() and both were trying to lock the same mutex. Since nothing else is calling applyErrors() any more, we can just remove it.
Flaky deadlock was caused by https://github.com/GoogleContainerTools/kpt-config-sync/pull/1199, so this does not need cherry-picking to v1.18
> fix: deadlock in Updater.Errors()

- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/root_test.go
- pkg/parse/run_test.go
- pkg/parse/source_test.go
Mutexes do not need a pointer when used as a field in a struct that is used with a pointer. Mutexes also don't need initialization when not a pointer. So this makes it a little easier to construct pointer.Options.
> Refactor parser.Options to use a normal mutex

- cmd/nomos/migrate/configmanagement.go
- cmd/nomos/migrate/migrate.go
- cmd/nomos/migrate/monorepo.go
- cmd/nomos/status/client.go
- cmd/nomos/util/configmanagement.go
- e2e/nomostest/config_sync.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/testpredicates/predicates.go
- e2e/testcases/cli_test.go
- e2e/testdata/configmanagement/1.18.0/config-management-operator.yaml
- pkg/api/configsync/register.go
- pkg/kinds/kinds.go
This change updates the nomos migrate command to support migrating from a ConfigManagement installation to a standalone Config Sync installation. This builds on the existing logic, such that first it will migrate from mono-repo to multi-repo if applicable.
> feat: add OSS migration logic

- pkg/parse/run_test.go
* Removing this test as it doesn't actually test the backoff in the reconciler and the test is not deterministic
> test: remove flaky `TestBackoffReimportCount`

- cmd/junit-report/resetfailure/reset_failure.go
- e2e/testcases/cli_test.go
- scripts/e2e.sh
The output currently breaks the XML parser used by the junit reporting.
> ci: omit nomos migrate output from test logs

- e2e/testcases/otel_collector_test.go
The fix https://github.com/GoogleContainerTools/kpt-config-sync/pull/1232 only affects declared_resources from Config Sync.
The metric from RG controller may take longer to be ready. Skip checking for those target values for now.
> test: Only check declared_resources metric

- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
> chore: Bump otelcontribcol to 0.102.0-gke.4

- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
> chore: Bump otelcontribcol to 0.102.0-gke.4 (#1270)

- e2e/testcases/otel_collector_test.go
- pkg/declared/resources.go
The current OpenCensus library keeps a metric stream that is uniquely identified by commit alive even though no new values are issued.
This makes the Otel Collector metricstransform processor receives all time value when calculating the max and gives false output.
The temporary work around is to reset the stream of previous commit to 0 when parser sees new commit.
The cherry-pick was modified to accommodate the data structure of Resources that v1.18 currently has.
b/321875474
> [metric] Reset declared_resource to 0 when commit updates with test fix (#1232)

- pkg/applier/management_conflict_err.go
- pkg/parse/namespace.go
- pkg/parse/root.go
- pkg/parse/root_test.go
- pkg/parse/run.go
- pkg/parse/run_test.go
- pkg/parse/sync_status_cache.go
- pkg/parse/updater.go
- pkg/reconciler/reconciler.go
- pkg/remediator/remediator.go
- pkg/status/management_conflict_error.go
- Update KptManagementConflictError to use an "UNKNOWN" old manager so it can return a ManagementConflictError. The UNKNOWN string is not shown to users. It just acts as a placeholder to return from the ConflictingManager() method. The previously added de-dupe code in conflict.Handler prefers errors with real manager values. So when the remediator and updater return similar errors, only the one with both managers is reported in the RSync status.
- Share the conflict.Handler between the Remediator & Updater so it can handle deduping at runtime, instead of when updating the status.
> Dedupe management conflict errors

- pkg/client/restconfig/config.go
- pkg/client/restconfig/restconfig.go
- pkg/client/restconfig/restconfig_test.go
The rest config precedence was changed to prioritize the kubectl config over the in cluster config. This was only checking if KubeConfigPath returns a path rather than whether a file exists at that path.
It has been reported that certain k8s distributions set the user config for the container, in which case KubeConfigPath will return a home directory path for that user. This causes the process to attempt to use a local file config instead of the in cluster config, which fails.
This change adds an additional check that the kube config file exists at the specified path, which is intended to fix the above scenario.
Fixes: https://github.com/GoogleContainerTools/kpt-config-sync/issues/1273
> fix: only use local config if file exists

- Makefile
- Makefile.build
- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
This moves the image definitions for git-sync and otelcontribcol to the Makefile, such that all sub-dependency versions defined in one place.
> refactor: parametrize git-sync and otel version

- e2e/nomostest/wait_for_sync.go
- e2e/testcases/hydration_test.go
Also use Fatal instead of Error to make it easier to debug errors without extra logs.
> e2e: update hydration tests to watch for errors

- pkg/remediator/fake/remediator.go
- pkg/remediator/remediator.go
The conflict and fight handlers are injected now, so these methods are unused.
> cleanup: remove unused methods from remediator

- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/run.go
- pkg/parse/updater.go
- pkg/remediator/fake/remediator.go
- pkg/remediator/remediator.go
- pkg/remediator/watch/manager.go
- Fix remediator error updates not being published after parsing has started for a new commit. Normally parsing is quick, but if there was an error, this state would often continue until the error was fixed by the user in the source.
- Modify setSyncStatus to take a commit, so we can avoid reverting the status.sync.commit after parsing has started and modified state.cache.source.commit.
- Add Remediator.Remediating() to avoid updating the sync status before syncing has succeeded or while remediating is paused during a sync attempt.
> fix: remediator error reporting after new commit

- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/run.go
- pkg/parse/updater.go
- pkg/remediator/fake/remediator.go
- pkg/remediator/remediator.go
- pkg/remediator/watch/manager.go
This reverts commit 3e0915218d44dc238bb3a7b21e66c9e999e50821.
Reason for revert: This introduced frequent test failures for:
- TestHydrateKustomizeComponentsChanges
- TestHydrateHelmOverlay
> Revert "fix: multiple sync status update bugs (#1283)"

- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/root_test.go
- pkg/parse/run.go
- pkg/parse/updater.go
- pkg/remediator/fake/remediator.go
- pkg/remediator/remediator.go
- pkg/remediator/watch/manager.go
- Update status.source after fetch before rendering if the commit
changed. This allows using status.source.commit to see what
commit has been fetched even if rendering fails.
This also causes the Syncing condition to be updated at the same
time, which tells the user the remediator is working on a new
commit.
- Update status.sync periodically after a new commit has been
published to status.source.commit or status.rendering.commit.
This allows continuing to update remediator errors after a new
commit has been fetched. Normally this isn't a long time, but it
can be if there's a source or rendering error requiring change
by the user.
- Update SetSyncStatus to only update the Syncing condition if
the reconciler hasn't fetched a new commit. This prevents
periodic updates from overwriting the …
> fix: multiple status update bugs 

- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/root_test.go
- pkg/parse/run.go
- pkg/parse/run_test.go
- pkg/parse/state.go
- pkg/parse/status.go
Prior to this change, the reconcilerState in the parser package contained both status reported to the RSync and internal state used to keep track of progress.
With this change, the status persisted to the RSync is now under the ReconcilerStatus struct, under reconcilerState. This seperates the two different domains in preperation for adding more stage-specific caching for RSync spec, which is used to populate the RSync status.
ReconcilerStatus uses primarily public fields, because it helps distinguish between fields intended for external manipulation and fields that should only be manipulated by methods on the struct, even if the manipulator is in the same package. Hopefully, we can expand this convention in the future, but for now it's limited in scope to keep the size of this PR …
> Refactor reconciler status caching

- cmd/helm-sync/main.go
- cmd/oci-sync/main.go
- pkg/parse/state.go
- pkg/util/retry.go
This adds exponential backoff to the oci-sync when it encounters repeated errors. This makes the behavior comparable to the behavior for helm-sync. The code is refactored to use a common backoff creation function and a minimum cap is defined for the sync containers.
> feat: error backoff for oci-sync

- pkg/parse/cache.go
- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/root_test.go
- pkg/parse/run.go
- pkg/parse/run_test.go
- pkg/parse/source_test.go
- pkg/parse/state.go
- pkg/parse/status.go
- pkg/reconciler/reconciler.go
- Update TestRun & TestRoot_Parse to validate the RootSync status
- Change SourceStatus, RenderingStatus, and SyncStatus to pointers and add DeepCopy methods, for easier generation of test permutations.
- Remove `cacheForCommit.errs`, which was only being used for testing errors in TestRun. Errors are now tested from the RSync status.
> Inject Parser.Clock for testing

- Makefile
- Makefile.build
- cmd/helm-sync/main.go
- cmd/oci-sync/main.go
- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
- pkg/client/restconfig/config.go
- pkg/client/restconfig/restconfig.go
- pkg/client/restconfig/restconfig_test.go
- pkg/hydrate/tool_util.go
- pkg/parse/state.go
- pkg/util/retry.go
```
$ git log --oneline HEAD...upstream/main
71ac1c9f (upstream/main, origin/main, origin/HEAD, main) [WIP] Inject Parser.Clock for testing (#1299)
9bea5a9d feat: error backoff for oci-sync (#1298)
0e2cbffd Refactor reconciler status caching (#1296)
3c4415c8 chore: bump git-sync to v4.2.3-gke.2__linux_amd64 (#1295)
2f2abfb7 test: clean up root reconciler ClusterRoleBindings (#1294)
f1adb5e8 fix: multiple status update bugs (#1290)
c4764b8f chore: bump otelcontribcol to v0.102.0-gke.5 (#1293)
75391db3 test: increase helm-sync memory for TestPublicHelm (#1288)
0e553996 refactor: use SourceFormat in RSync spec (#1292)
2776151b test: wait for ACM operator to become ready (#1291)
6ca57cf3 refactor: use SourceType type in RSync spec (#1289)
adfc8f6d e2e: cleanup hydration tests (#1287)
9df16632 …
```
> Cherrypick 1.18.3

- pkg/parse/cache.go
- pkg/parse/namespace.go
- pkg/parse/opts.go
- pkg/parse/root.go
- pkg/parse/root_test.go
- pkg/parse/run.go
- pkg/parse/source.go
- pkg/parse/source_test.go
- pkg/parse/status.go
- Fix reconciler ignoring/erasing status from previous reconciler
instances by priming the in-memory cache from the RSyncs status.
Example: status.sync.commit
Exception: errors are not parsable and may still be lost.
Dependencies:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1283
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1280
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1282
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1290
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1296
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1299
> Fix sync status lost on reconciler pod replacement

- Makefile
- Use "make" to run in docker
- Use "make all-local" to run locally
This should make it easy for us to all get the same result when running tests locally, even if we have subtly different versions of dependencies installed locally or have the repo checked out in different locations.
> Run make in buildenv container by default

- Makefile.reconcilermanager
- manifests/cluster-selector-crd.yaml
- manifests/hierarchyconfig-crd.yaml
- manifests/namespace-selector-crd.yaml
- manifests/reposync-crd.yaml
- manifests/resourcegroup-crd.yaml
- manifests/rootsync-crd.yaml
Note: controller-gen 0.13.0 encounters a seg fault on Go 1.22. This change is needed in order to upgrade the Go version.
> chore: bump controller-gen to 0.15.0

- Makefile
- Makefile.build
- Makefile.e2e.ci
- Makefile.oss.prow
Prior to this change, only the buildenv image was published on
postsubmit and required manually bumping the buildenv image tag. This
makes two key changes:
- Forms the image tag using the image inputs (dependencies), such that a
new image will be published whenever one of the inputs changes. For
example when the Go base image is updated, the postsubmit will publish
a new image.
- Adds steps to publish both the gke-e2e and vulnerability-scanner
images during postsubmit, using the same logic as buildenv.
> ci: publish all infra images in postsubmit

- Makefile
Builds on https://github.com/GoogleContainerTools/kpt-config-sync/pull/1309 to simplify the process of bumping Go build environments
> ci: bump go environment to 1.22

- pkg/syncer/syncertest/fake/cache.go
This new method is required to satisfy the Informers interface in new versions of controller-runtime. It allows removing and stopping an informer from a set of informers. The individual informers are stopped using informer-specific context wrappers with cancel funcs.
This blocks upgrading our controller-runitme dependency.
Ref: https://github.com/kubernetes-sigs/controller-runtime/pull/2285
> Add fake.Cache.RemoveInformer

- cmd/nomos/migrate/migrate.go
ACM operator will soon report an error when monorepo mode is enabled. This change allows nomos migrate to still operate for new versions of ACM operator.
Alternatively we could filter by specific error message, however currently the only errors set by ACM operator are related to the git config issues. This solution is simpler and less brittle on account of hard coded string comparison.
> feat: allow nomos migrate to continue on error

- e2e/nomostest/clean.go
- e2e/nomostest/testpredicates/predicates.go
If uninstall fails or times out, continue with existing more aggressive cleanup. This may take longer, but should give Config Sync a chance to clean up objects following reverse dependency ordering. Hopefully, this will help avoid race conditions and deadlocks.
> cherry-pick: e2e: attempt to uninstall packages in cleanup (#1231)

- pkg/remediator/reconcile/worker.go
- pkg/remediator/reconcile/worker_test.go
This change handles future cases where watch filtering by label causes delete events when the required label is removed.
This blocks watch filtering: https://github.com/GoogleContainerTools/kpt-config-sync/pull/1301
> Remediate watch filter label removal

- cmd/nomos/nomos.go
There currently is not a clean way to programmatically capture the version of the nomos CLI. The nomos version command also fetches the config sync version installed on the cluster from the kube context.
This provides an easy way to simply print the version of the CLI.
> feat: add --version flag to nomos CLI

- .golangci.yaml
The staticcheck go field is deprecated. It should be set in the run.go field, however this field defaults to the version in go.mod. So no need to define the go version in this file.
> ci: fix go lint deprecated field

- cmd/nomos/status/client.go
- cmd/nomos/version/version.go
- cmd/nomos/version/version_test.go
- pkg/bugreport/bugreport.go
- pkg/client/restconfig/config.go
- pkg/client/restconfig/config_test.go
The rest config creation can be expensive since it performs an API call with UpdateQPS. This can take an especially long time if you have a large kubeconfig that contains stale configs (e.g. cluster deleted) since it will wait for API timeout.
> feat: filter contexts before creating rest configs

- cmd/oci-sync/main.go
- e2e/testcases/oci_sync_test.go
- pkg/oci/fetcher.go
- pkg/oci/fetcher_test.go
If the image reference in the RSync spec contains a fully specified image with digest, it can be assumed that the image is immutable. Thus, after a single successful sync the oci-sync container does not need to continue polling.
This is implemented as a long sleep for now, since exiting the container would cause a crashloop. If oci-sync is integrated as a k8s sidecar container, then we can change this to exit.
> feat: only sync once for oci image with digest

- pkg/parse/updater.go
- pkg/remediator/fake/remediator.go
- pkg/remediator/remediator.go
- pkg/remediator/watch/listwatch.go
- pkg/remediator/watch/manager.go
- pkg/remediator/watch/manager_test.go
This fix starts new watches before applying, to ensure that conflicts on existing objects are caught by the remediator immediately after the applier mutates an object and before the whole apply set has succeeded and reconciled.
This is only a partial fix. It doesn't work for custom resources which are applid with their CRD in the same ApplySet. To resolve that case, we will need to asynchronously start watches when the resource is available, which we can add later.
> Fix remediator to catch conflicts during apply

- e2e/nomostest/clusters/kind.go
This updates the ClusterConfiguration used to provision kind clusters to mount etcd to a volume backed by tmpfs. This provides memory backed storage for faster i/o.
See: https://github.com/kubernetes-sigs/kind/issues/845#issuecomment-1261248420
> test: update kind to use in-memory etcd

- e2e/testcases/multi_sync_test.go
- pkg/applier/management_conflict_err.go
- pkg/core/decorate.go
- pkg/parse/root.go
- pkg/parse/root_test.go
- pkg/parse/run.go
- pkg/status/management_conflict_error.go
Use the same message for conflicts detected by the current reconciler and a remote reconciler. Who detected the conflict is irrelevent to the user.
Clarify the error message to make sense for non-git sources of truth.
Depends on: https://github.com/GoogleContainerTools/kpt-config-sync/pull/1345
> Simplify management conflict error

- e2e/testcases/cli_test.go
- pkg/bugreport/bugreport.go
config-management-operator has not been installed in the kube-system namespace since before 1.9.0. 1.9.0 was released in 2021, so it should not be necessary to include kube-system logs in current versions of nomos bugreport.
See: https://cloud.google.com/kubernetes-engine/enterprise/config-sync/docs/release-notes#September_23_2021
> feat: remove kube-system from nomos bugreport

- e2e/testcases/cli_test.go
- pkg/bugreport/bugreport.go
- pkg/bugreport/constants.go
PoCo is no longer included with ACM, so there is no longer a need to bundle the PoCo logs with nomos bugreport.
> feat: remove PoCo from nomos bugreport

- cmd/nomoserrors/examples/examples.go
- e2e/testcases/custom_resources_test.go
- pkg/remediator/reconcile/reconciler_test.go
- pkg/syncer/client/client.go
- pkg/syncer/client/client_test.go
- pkg/syncer/client/retriable_errors.go
- pkg/syncer/reconcile/apply.go
- Update remediator to record NoMatchErrors as a resource conflict.
These are reported as metrics and cause retry, but are still not
reported as sync errors, for now.
- Update comments in TestCRDDeleteBeforeRemoveCustomResourceV1
to explain why a conflict is expected and which ones might be
encountered due to race condition.
> fix: remediator ignores no resource/kind match

- e2e/testcases/multi_sync_test.go
- pkg/parse/run.go
- pkg/parse/updater.go
- pkg/remediator/conflict/handler.go
- pkg/remediator/remediator.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/manager.go
- pkg/syncer/syncertest/fake/conflict_handler.go
- Change the run loop retry handler to check the conflict handler for errors, instead of using a flag in the remediator watchers. This fixes a bug where the applier may only be triggered once after a conflict, even if the conflict was not resolved.
- Change the remediator to treat namespace reconcilers the same as root reconcilers when reporting a management conflict error. This fixes a bug which could happen when the applier succeeded and then a new conflict was discovered, which wouldn't report the conflict until the next resync or source change.
- Use a RWMutex in the conflict handler, to allows parallel reads.
- Change the remote reporting (RootSync -> RootSync) of conflict status errors to read the errors from the conflict handler, instead of the applier errors. This just simplifies …
> fix: RepoSync management conflict reporting

- pkg/remediator/conflict/handler.go
- pkg/remediator/reconcile/reconciler.go
- pkg/remediator/reconcile/reconciler_test.go
- pkg/remediator/reconcile/worker.go
- pkg/remediator/reconcile/worker_test.go
- pkg/remediator/remediator.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/syncer/syncertest/fake/conflict_handler.go
- Change the remediator worker to detect management conflicts.
This fixes a bug when using watch filtering where conflicts
may be ignored for objects that were "deleted" by having the
required label removed after being successfully applied by
the applier but before being remediated.
- Change the remediator worker to clear management conflicts.
This fixes a bug where the conflict error might be prematurely
removed from the status and then not actually resolved,
causing the error to flap.
Depends on https://github.com/GoogleContainerTools/kpt-config-sync/pull/1354
> fix: remediator management conflict detection

- e2e/testcases/cli_test.go
These CRDs were not being removed and left lingering on the cluster after the test.
This is causing a side effect for the nomos bugreport test which is outputting files for these CRDs.
> test: cleanup monorepo CRDs after migrate test

- e2e/testcases/cli_test.go
- pkg/bugreport/bugreport.go
- The resource-group-controller logs were only collected when the config-management label was on the Namespace. This meant they were only collected when the operator-applied label was on the Namespace. Now it will consistently collect the ResourceGroup logs whenever the configmanagement "system" label is on the Namespace. This fixes a flake that could happen if the bugreport test ran after the nomos migrate test, and also improves the behavior.
- Update test expectations to expect the askpass logs if the gcenode auth type is in use. This fixes a test failure on the CSR tests.
> fix: bugreport logs for resourcegroup and askpass

- e2e/testcases/cli_test.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
The askpass sidecar is also present for the gcpserviceaccount git auth type, and thus the logs are expected.
> test: also expect askpass for gcpserviceaccount

- e2e/testcases/managed_resources_test.go
- e2e/testcases/preserve_fields_test.go
- pkg/applier/applier_test.go
- pkg/applier/clientset.go
- pkg/applyset/applyset.go
- pkg/core/decorate.go
- pkg/kinds/resources.go
- pkg/metadata/applyset.go
- pkg/parse/annotations.go
- pkg/parse/annotations_test.go
- pkg/parse/root_test.go
- pkg/reconciler/reconciler.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/remediator/watch/filteredwatcher_test.go
- pkg/remediator/watch/manager.go
- pkg/remediator/watch/manager_test.go
- pkg/remediator/watch/watcher.go
- Add "applyset.kubernetes.io/part-of" label to managed objects
- Add "applyset.kubernetes.io/id" label to RootSyncs/RepoSyncs
- Add "applyset.kubernetes.io/tooling" annotation to RootSyncs/RepoSyncs
- Error if the RSync already has a tooling annotation for a different tool (unlikely, but required by KEP).
- Generate ApplySet IDs using kubectl code for compatibility.
- Update TestKubectlCreatesManagedNamespaceResourceMultiRepo & TestAddUpdateDeleteLabels with new labels & annotations
go/config-sync-watch-filter
In the KEP, the labels and annotations begin with `applyset.k8s.io`. However, when implemented in kubectl, this was changed to `applyset.kubernetes.io`. The reason for this is unclear. But we decided compatibility with kubectl was more important, since it's the only other known …
> Add watch filtering by applyset label

- e2e/testcases/custom_resources_test.go
This test has become increasingly flaky. Increasing the reconciler log level should help surface more of the reconciler logs when the test fails.
> test: improve logging for flaky TestCRD test

- e2e/nomostest/new.go
- e2e/nomostest/testing/ntb.go
- e2e/nomostest/testing/wrapper.go
- e2e/nomostest/testlogger/testlogger.go
- e2e/nomostest/wait_for_sync.go
The Wrapper struct was unnecessary and broke the Helper method of the testing struct. The Helper method inspects the stack trace and adds the caller as a helper function, but this breaks when the Helper call is invoked in a nested helper function.
With this change the Helper calls work as expected and the correct line numbers are logged.
> test: fix logging to print correct line numbers

- pkg/diff/precedence.go
- pkg/diff/precedence_test.go
- pkg/importer/metrics.go
- pkg/importer/reader/parse_file.go
- pkg/webhook/validate_test.go
The importer Deployment is related to the legacy architecture which has been deprecated and removed.
> clean up stale references to the importer

- e2e/testcases/custom_resources_test.go
- pkg/remediator/reconcile/reconciler.go
- pkg/syncer/client/client.go
- pkg/syncer/client/client_test.go
- Refactor the syncer Client and clientApplier to handle errors more consistently.
- Handle both NotFound and NoMatchFound errors everywhere they can be returned by the controller-runtime client.
> fix: syncer client not handling resource not found

- docs/testing.md
The previous instructions broke with the introduction of unit tests under the e2e subdirectory. This fixes the instructions and adds a quickstart section to help new developers.
> docs: fix e2e test docs and add quickstart

- pkg/parse/updater.go
- pkg/remediator/watch/manager.go
- pkg/remediator/watch/manager_test.go
- pkg/syncer/client/retriable_errors.go
- Now that UpdateWatches checks for the resource to exist before starting the watch, it can prevent remediator unpause. This is intentional, but it caused TestCRDDeleteBeforeRemoveCustomResourceV1 to become flaky, due to the resource conflict metric not always being recorded, after deleting a non-managed CRD required for a managed CR.
- This fix adds a new resource conflict error type for watches and records a conflict metric if it's returned by UpdateWatches.
> fix: CRD deletion race not reporting conflict

- pkg/diff/precedence.go
- pkg/diff/precedence_test.go
- pkg/webhook/validate_test.go
- Root reconciler's remediator should not delete objects that have been adopted by another manager. This allows a namespace reconciler to adopt objects previously managed by a root reconciler without deleting the object first.
- This fixes a race condition that was causing TestConflictingDefinitions_RootToNamespace to be flaky.
Release Note:
- Fixed a bug where RootSync reconcilers could delete objects managed by RepoSync reconcilers. This simplifies the adoption process of handing off objects between reconcilers.
> fix: remediator deleting objects after adoption

- pkg/syncer/client/client.go
- pkg/syncer/client/client_test.go
- pkg/syncer/reconcile/apply.go
If the CRD does not exist, the create/apply call may return IsNotFound error. This should be treated as a conflict so that the conflict metric is recorded.
Follow up to https://github.com/GoogleContainerTools/kpt-config-sync/pull/1365
> fix: treat IsNotFound as conflict on Create

- Makefile
- manifests/base/kustomization.yaml
- manifests/otel-agent-reconciler-cm.yaml
- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
Upgrading to latest for vulnerability fix.
To upgrade to otelcontribcol 0.106.0 we need to mitigate two breaking changes in https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.104.0.
The opencensus receiver depends on 0.0.0.0 so disabling feature gate component.UseLocalHostAsDefaultHost.
With style `$FOO` deprecation, all env vars are changed to match the style. This brings a problem in the otel-agent container start when reconciler-manager and resource-group-controller do not initialize the following env vars:
- `configsync_sync_kind`
- `configsync_sync_name`
- `configsync_sync_namespace`
So splitting the otel-agent config between the reconciler and controllers.
> Update otelcontribcol to v0.106.0-gke.2

- Makefile
- pkg/hydrate/tool_util.go
> Bump Helm version to v3.15.3-gke.0

- e2e/nomostest/clusterversion/cluster_version.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/reconciler_manager_test.go
New versions of GKE autopilot support burstable Pods, which invalidates some of the previous test expectations for container resources on autopilot. This change adds a check for autopilot resource bursting and updates test expectations accodirngly.
> test: update test expectations for autopilot bursting

- pkg/parse/updater.go
- pkg/remediator/fake/remediator.go
- pkg/remediator/remediator.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/manager.go
- pkg/remediator/watch/manager_test.go
- pkg/remediator/watch/watcher.go
This is intended to fix a scenario where watched CRD is deleted and the watch ends and attempts to restart. In this scenario a conflict metric may not have been reported if the watch fails before receiving a deleted event.
Follow up to https://github.com/GoogleContainerTools/kpt-config-sync/pull/1366
> fix: conflict metric on watched resource not found

- e2e/nomostest/nt.go
detectGKEAutopilot is called later, so the IsGKEAutopilot variable is not set. This switches to use the command line flag instead.
> test: fix autopilot bursting check

- e2e/nomostest/reset.go
- e2e/testcases/helm_sync_test.go
If the RSync is modified between the List call and the Update call, then the Update fails. Using MergePatch to inject the annotation makes the reset more robust.
Example failure: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-autopilot-rapid/1821388389237133312
> test: fix reset enabling deletion propagation after update

- manifests/templates/resourcegroup-manifest.yaml
This is to align the feature behavior with reconciler & reconciler-manager.
Currently we see no difference without the flag as
- there are no test coverage on resourcegroup controller metrics
- the naming convention obeys Prometheus rules so no trimming is happening
> Align otel-agent feature gate in resource group controller

- e2e/nomostest/clean.go
- e2e/nomostest/clusterversion/cluster_version.go
- e2e/nomostest/clusterversion/cluster_version_test.go
- e2e/nomostest/nt.go
The previous logic was not fully correct, for example it would consider 1.31.0 to be less than 1.30.2. This makes the logic a proper semver comparison, which should prevent breakage when newer cluster versions are tested in the future.
> test: fix cluster version comparison

- e2e/nomostest/registryproviders/artifact_registry.go
Some side effects have been noticed in the periodic jobs, such as an image never getting deleted if the cleanup fails on a prior execution. As an example this can cause TestHelmLatestVersion to become flaky, since the 3.0.0 helm chart already exists before the test starts.
Tearing down the entire GAR repository allows the periodic jobs to self heal side effects after a failed cleanup.
Example failure: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-regular/1823419274467741696
> test: delete GAR repositories on teardown

- e2e/nomostest/config_sync.go
- e2e/nomostest/wait_for_sync.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/proxy_test.go
- e2e/testcases/reconciler_manager_test.go
RootSyncs are always in the c-m-s namespace, so the namespace argument is redundant. This makes the function consistent with the other WaitForRootSync* functions.
> refactor: WaitForRootSyncStalledError ns arg

- e2e/nomostest/config_sync.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/ntopts/multi_repo.go
- e2e/nomostest/prometheus_metrics.go
- e2e/nomostest/syncsource/syncsource.go
- e2e/testcases/admission_test.go
- e2e/testcases/cli_test.go
- e2e/testcases/cluster_selectors_test.go
- e2e/testcases/composition_test.go
- e2e/testcases/gcenode_test.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/invalid_git_branch_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/namespace_repo_test.go
- e2e/testcases/namespace_strategy_test.go
- e2e/testcases/no_ssl_verify_test.go
- e2e/testcases/oci_sync_test.go
- e2e/testcases/override_git_sync_depth_test.go
- e2e/testcases/override_log_level_test.go
- e2e/testcases/override_resource_limits_test.go
- e2e/testcases/override_role_refs_test.go
- e2e/testcases/private_cert_secret_test.go
- e2e/testcases/reconciler_finalizer_test.go
- e2e/testcases/reconciler_manager_test.go
- e2e/testcases/ssh_known_hosts_test.go
- e2e/testcases/workload_identity_test.go
- pkg/core/id.go
- Combine RootRepos and NonRootRepos to use syncsource.Set.
- Rename NT.New options to be more clear about what they do.
- Move RootSyncID and RepoSyncID to the core package, to allow use in ntopts without import cycle.
> e2e: simplify RSync test setup

- e2e/nomostest/wait_for_sync.go
- e2e/testcases/sync_ordering_test.go
This test is currently one of the longest running tests, with a typical runtime of ~14m30s. The majority of this time is spent on the scenario where Pods should not reconcile, because the reconcileTimeout is very long for the test. Shortening the reconcile timeout for this specific scenario drastically reduces the runtime of the test.
This reduces the runtime from the order of ~14m30s to ~5m.
> test: improve runtime of TestDependencyWithReconciliation

- e2e/nomostest/config_sync.go
- e2e/nomostest/new.go
- e2e/testcases/managed_resources_test.go
This speeds up the polling periods used by both the *-sync containers and the reconcilers.
> test: reduce polling periods for e2e tests

- Makefile.e2e
After recent optimizations to the e2e tests, the runtimes between test groups has become increasingly unbalanced. This change is intended to reduce the variance.
> chore: rebalance e2e test groups

- Makefile
- e2e/flags.go
- e2e/nomostest/gitproviders/bitbucket.go
- e2e/nomostest/gitproviders/github.go
- e2e/nomostest/ntopts/new.go
- e2e/nomostest/ntopts/test_type.go
- e2e/testcases/github_test.go
- manifests/reposync-crd.yaml
- manifests/rootsync-crd.yaml
- pkg/api/configsync/register.go
- pkg/api/configsync/v1alpha1/gitconfig.go
- pkg/api/configsync/v1beta1/gitconfig.go
- pkg/reconcilermanager/controllers/constants.go
- pkg/reconcilermanager/controllers/gitsync_env.go
- pkg/reconcilermanager/controllers/gitsync_env_test.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/reconcilermanager/controllers/validate_secret.go
- pkg/reconcilermanager/controllers/validate_secret_test.go
- pkg/validate/raw/validate/source_spec_validator.go
This change adds support for a new git-sync auth type named githubapp. The auth type maps GitHub App configuration from the Secret referenced by secretRef to environment variables in the git-sync container. The git-sync version is upgraded to a new version that supports these new environment variables and GitHub app based authentication.
End to end tests are implemented as one off tests similar to the kcc/gcenode tests. This is because these tests are inherently non-hermetic and require secrets which are generally not accessible when running the tests locally or in presubmits. This could alternatively be implemented as a gitprovider interface, however that was decided against for the initial implementation to reduce scope. These tests will be executed by the prowjob added in …
> feat: add github app auth to git-sync api

- e2e/nomostest/config_sync.go
- e2e/nomostest/ssh.go
- e2e/testcases/composition_test.go
- e2e/testcases/reconciler_manager_test.go
It is possible to run the tests as a combination of git-provider=csr and oci-provider=local. In this case the CA certs for the registry server need to be created in the RepoSync namespace.
> test: fix logic to create ca certs when git=csr

- e2e/nomostest/config_sync.go
- e2e/nomostest/ssh.go
- e2e/testcases/composition_test.go
- e2e/testcases/reconciler_manager_test.go
It is possible to run the tests as a combination of git-provider=csr and oci-provider=local. In this case the CA certs for the registry server need to be created in the RepoSync namespace.
> [cherry-pick] test: fix logic to create ca certs when git=csr (#1412)

- e2e/nomostest/clean.go
- e2e/nomostest/config_sync.go
- e2e/testcases/multi_sync_test.go
- Use RepoSyncObjectV1Beta1 & SetRSyncTestDefaults so RepoSyncObjectV1Beta1Git can be made private.
- Use Must, where possible
- Fix DeleteObjectsAndWait to handle NotFound on Merge
> e2e: Clean up TestControllerValidationErrors

- e2e/nomostest/config_sync.go
- e2e/nomostest/config_sync_sources.go
- e2e/nomostest/new.go
- e2e/nomostest/nt.go
- e2e/nomostest/syncsource/syncsource.go
- e2e/nomostest/wait_for_sync.go
- e2e/testcases/cli_test.go
- e2e/testcases/gcenode_test.go
- e2e/testcases/github_test.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/invalid_git_branch_test.go
- e2e/testcases/kcc_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/oci_sync_test.go
- e2e/testcases/override_git_sync_depth_test.go
- e2e/testcases/policy_dir_test.go
- e2e/testcases/private_cert_secret_test.go
- e2e/testcases/proxy_test.go
- e2e/testcases/stress_test.go
- e2e/testcases/workload_identity_test.go
- Add Branch & Revision to GitSyncSource to configure root-sync
and other test setup RSyncs.
- Add SetExpectedSyncSource & UpdateExpectedSyncSource
- Add ExpectedCommit, ExpectedChartVersion, & ExpectedImageDigest
- Add ExpectedDirectory for OCI and Git
- Remove WithRootSha1Func & WithRepoSha1Func.
Use one of the Expected- fields in the SyncSource instead.
- Update test setup to provision RSyncs without overwriting any
existing SyncSource expectations.
Dependencies: 
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1413
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1414
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1416
> e2e: refactor sync expectations

- Makefile.e2e
This argument is already unused when running the tests in kind clusters, but this makes the intent more clear. The e2e tests should/do not require a GCP project to run with kind.
> ci: remove GCP_PROJECT arg from test-e2e-kind

- e2e/testcases/workload_identity_test.go
This line was removed in a previous change, which leads to a segfault because the sha1Func is nil when accessed.
Fixes breaking change from https://github.com/GoogleContainerTools/kpt-config-sync/pull/1410
For example: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-rapid/1831339095763193856
> test: fix sha1Func for oci workload identity test

- Makefile
This addresses CVEs in the previous image
> chore: bump otelcontribcol to 0.103.0-gke.4

- e2e/testcases/stress_test.go
Sets the `Directory` instead of the `Revision` to "configs" and removes `SecretRef` from the RootSync spec in TestStressLargeRequest
This fixes a breaking change introduced by https://github.com/GoogleContainerTools/kpt-config-sync/pull/1410
Example failure: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-rapid-latest-stress/1831422149634560000
> test: Fix RootSync spec in TestStressLargeRequest

- Makefile
This addresses CVEs in the previous image
> [cherry-pick] chore: bump otelcontribcol to 0.103.0-gke.4 (#1422)

- e2e/testcases/kcc_test.go
The arguments are in the wrong order, causing the directory argument to be used as the revision instead. This was introduced by a previous refactor.
This fixes a breaking change introduced by https://github.com/GoogleContainerTools/kpt-config-sync/pull/1410
Example failure: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-regular-kcc/1831814738229596160
> test: fix git dir for kcc test RootSync

- Makefile
This includes some CVE fixes from the prior version
> chore: bump git-sync to v4.2.4-gke.4

- Makefile
This includes some CVE fixes from the prior version
> [cherry-pick] chore: bump git-sync to v4.2.4-gke.4 (#1427)

- Makefile.e2e
These legacy aliases are no longer in use and can be removed
> chore: clean up unused e2e-kind make targets

- cmd/reconciler-manager/main.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
This argument has been long unused by the OtelReconciler, and can be removed without any functional changes.
> refactor: clean up unused clusterName in otelreconciler

- e2e/nomostest/config_sync_sources.go
- e2e/nomostest/wait_for_sync.go
- e2e/testcases/composition_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/oci_sync_test.go
- e2e/testcases/override_role_refs_test.go
- e2e/testcases/profiling_test.go
- Update WatchForSync to take a SyncSource, instead of Sha1Func,
sha1 Predicate, and SyncPathPredicatePair. These are replaced by
SyncSource.Path() and SyncSource.Commit() which handle defaulting
and using the spec value if an expectation was not explicitly set.
- Update SyncSource expectation functions to be test helpers
- Refactor TestComposition to update expecations and use
WatchForAllSyncs instead of a custom watch wrapper.
- Refactor a few tests that were using WatchForSync directly to
pass in a SyncSource with expectations updated.
Dependencies:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1430
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1435
> e2e: Update WatchForSync to take a SyncSource

- e2e/testcases/lifecycle_directives_test.go
- e2e/testcases/namespaces_test.go
- e2e/testcases/reconciler_finalizer_test.go
- e2e/testcases/sync_ordering_test.go
- pkg/applier/applier.go
- pkg/applier/clientset.go
- pkg/metadata/metadata.go
- pkg/metadata/metadata_test.go
- pkg/reconciler/reconciler.go
- pkg/syncer/reconcile/apply.go
- pkg/syncer/syncertest/fake/applier.go
This change removes the `applyset.kubernetes.io/part-of` label from managed objects when they are abandoned.
Supported Use Cases:
- Unmanage object
- `configmanagement.gke.io/managed: disabled`
- `client.lifecycle.config.k8s.io/deletion: detach`
- `cli-utils.sigs.k8s.io/on-remove: keep`
- The Config Sync Applier/Destroyer calls RemoveConfigSyncMetadata if object HasConfigSyncMetadata when a Delete Skipped event is received (deletion detach or keep on remove).
- The Config Sync Remediator calls RemoveConfigSyncMetadata when an Abandon operation is requested (managed disabled or deletion detach).
- Uninstall package
- `configsync.gke.io/deletion-propagation-policy: Foreground`
- This use case invokes the Destroyer, which handles the unmanage annotations the same way the Applier does. …
> fix: Remove ApplySet part-of label on abandon

- e2e/nomostest/testresourcegroup/resourcegroup.go
- pkg/resourcegroup/controllers/root/root_controller.go
- pkg/resourcegroup/controllers/root/root_controller_test.go
This fixes #1297.
I didn't see any tests for the full NewController function, and decided setting one up was overkill for this change; we should be able to trust here that controller-runtime can properly add and apply a provided predicate, so as long as that predicate works as expected, so whould the watch configuration.
The new tests exhaustively specify the behavior of the new predicate, so that for every type of event, it matches if (and only if) the label `app.kubernetes.io/managed-by` is set to `configmanagement.gke.io`; this is what Config Sync already does to all objects it creates.
> Only watch ResourceGroups with the correct owner label

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
Bursting on Autopilot requires clusters to meet the following conditions:
- You originally created the cluster with GKE version 1.26 or later.
- The cluster is running GKE version 1.30.2-gke.1394000 or later.
When upgrading an Autopilot cluster to a supported version, GKE upgrades the worker nodes to match the control plane version over time. A control plane restart is required to enable bursting, and must happen after all the nodes run a supported version.
There isn't a good way to check the control plane restart, this commit only guarantees that all node versions are 1.30.2-gke.1394000 or later when nt.ClusterSupportsBursting is true.
Link: https://cloud.google.com/kubernetes-engine/docs/how-to/pod-bursting-gke#availability-in-gke
b/369006133
b/370402111
> test: fix the autobursting detection

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
Bursting on Autopilot requires clusters to meet the following conditions:
- You originally created the cluster with GKE version 1.26 or later.
- The cluster is running GKE version 1.30.2-gke.1394000 or later.
When upgrading an Autopilot cluster to a supported version, GKE upgrades the worker nodes to match the control plane version over time. A control plane restart is required to enable bursting, and must happen after all the nodes run a supported version.
There isn't a good way to check the control plane restart, this commit only guarantees that all node versions are 1.30.2-gke.1394000 or later when nt.ClusterSupportsBursting is true.
Link: https://cloud.google.com/kubernetes-engine/docs/how-to/pod-bursting-gke#availability-in-gke
b/369006133
b/370402111
> test: fix the autobursting detection (#1443)

- pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
Go Testing doesn't handle panics in goroutines well. So test fatals need to happen from the main thread. But errors can still happen in goroutines. So change the controller-manager stopping to assert instead of require no errors.
> test: fix flaky controller-manager tests

- pkg/parse/updater.go
- pkg/reconciler/finalizer/base_finalizer.go
- pkg/remediator/conflict/handler.go
- pkg/remediator/reconcile/reconciler.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/manager.go
- pkg/resourcegroup/controllers/watch/manager.go
- Simplify & fix applier/destroyer logs on success & failure
- Add the component in front of a few logs to make it clear where in the code the log came from, to simplify debugging.
- Log resource conflicts as warnings with explainations of how remediation will retry.
- Only log the keys from the GVK maps in the remediator manager.
- Fix remediator shutdown log to go to info instead of warning.
> chore: cleanup some logs

- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/manager.go
The watch.Runnable interface doesn't need to know how to clear management conflicts, because the watch.Manager already has access to the conflict.Handler. So just clear the conflicts in AddWatches, where it also deals with other conflicts. AddWatches also knows that the watch is no longer needed, whereas stopWatch only knows that it needs to be stopped.
> chore: remove ClearManagementConflictsWithKind

- cmd/reconciler-manager/main.go
- e2e/testcases/custom_resources_test.go
- manifests/base/kustomization.yaml
- manifests/ns-reconciler-cluster-scope-cluster-role.yaml
- pkg/reconciler/reconciler.go
- pkg/reconcilermanager/controllers/build_names.go
- pkg/reconcilermanager/controllers/crd_controller.go
- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/remediator/remediator.go
- pkg/remediator/watch/listwatch.go
- pkg/remediator/watch/manager.go
- pkg/remediator/watch/manager_test.go
- pkg/remediator/watch/mapper_wrapper.go
- pkg/util/customresource/customresource.go
- pkg/util/customresource/customresource_test.go
Prior to this change, the remediator watches were only being started
for new custom resources after the apply attempt had fully completed.
This left some time after the object was applied that the remediator
could miss events made by third-parties. Normally, this would be fine,
because the remediator would revert any change after the watch was
started. But if a DELETE event was missed, the object wouldn't be
recreated until the next apply attempt.
This change adds a CRD Controller to the remediator that watches CRDs
and executes any registered handlers when the CRD is established,
unestablished, or deleted. The remediator now registers CRD handlers
for each resource type it watches, starting watchers as soon as
possible, without waiting for the next apply attempt.
This change also adds a …
> fix: remediator missing custom resource events

- cmd/reconciler-manager/main.go
- pkg/reconciler/reconciler.go
- pkg/reconcilermanager/controllers/crd_controller.go
- pkg/remediator/remediator.go
- pkg/remediator/watch/listwatch.go
- pkg/remediator/watch/manager.go
- pkg/remediator/watch/manager_test.go
- pkg/remediator/watch/watcher.go
- pkg/util/watch/mapper.go
Use a common ResettableRESTMapper, shared between controllers and reset automatically by the CRDMetaController when a CRD is updated and the new state is different than what known by the RESTMapper.
Followup after https://github.com/GoogleContainerTools/kpt-config-sync/pull/1441
> chore: share mapper between controllers

- cmd/nomos/migrate/configmanagement.go
- cmd/nomos/util/configmanagement.go
- e2e/testcases/cli_test.go
This requires for the user to disable HNC before removing Config Management, so that ACM helps with the uninstallation of HNC before it is absent from the cluster. This is intended to streamline the experience of migrating to OSS HNC.
> feat: stall nomos migrate if HNC is enabled

- build/prow/e2e/Dockerfile.dockerignore
- e2e/testcases/cli_test.go
- installation/uninstall_configmanagement.sh
This is an alternative approach to uninstalling Config Management and the operator. This is intended as a simple/portable alternative to using the nomos migrate command.
> feat: add bash script for uninstalling ACM

- Makefile
- installation/README.md
- installation/kustomization.yaml
- scripts/test-kustomization.sh
- test/kustomization/expected.yaml
- test/kustomization/kustomization.yaml
This provides a new approach for customizing and installing Config Sync with many of the same features that ConfigManagement provides without the need to install another operator layer. A subsequent change will add tooling to package the kustomization file as a release artifact.
> feat: add kustomize tooling for custom CS install

- Makefile.build
This adds a make target that package the kustomization bundle into a tarball when the manifests are built. This will be published as a versioned release artifact for each release.
> ci: add tooling to package kustomization bundle

- pkg/declared/resources.go
- pkg/parse/event_handler.go
- pkg/parse/opts.go
- pkg/parse/parser.go
- pkg/parse/reconciler.go
- pkg/parse/repo_sync_client.go
- pkg/parse/repo_sync_parser.go
- pkg/parse/root_reconciler_test.go
- pkg/parse/root_sync_client.go
- pkg/parse/root_sync_client_test.go
- pkg/parse/root_sync_parser.go
- pkg/parse/run.go
- pkg/parse/run_test.go
- pkg/parse/source_test.go
- pkg/parse/state.go
- pkg/parse/sync_status_client.go
- pkg/parse/updater.go
- pkg/reconciler/reconciler.go
- Split the Parser interface into Parser & SyncStatusClient.
- Replace the root & namespace structs with seperate implementations of the Parser & SyncStatusClient interfaces.
- Create a new common reconciler struct which composes the Parser & SyncStatusClient interfaces. The reconciler struct can now hold common methods, and the current ReconcilerState, which encompases spec, status, and cache for all reconciler phases, not just the parser.
- Add a new Reconciler interface, for use by the EventHandler and DefaultRunFunc. We may want to move DefaultRunFunc to be a reconciler method in the future, but this would relocate all the run code, so we can do it in a seperate change.
- Move the Mutex out of the Options and into the Reconciler. Options should generally not be mutated after …
> chore: Extract Reconciler from Parser

- Makefile
We have been using an internal fork for the githubapp feature. Now this feature is officially included in OSS git-sync v4.3.0. This commit switches to the OSS project for continuous update.
b/376738669
> Switch to use the OSS git-sync with githubapp support

- cmd/reconciler/main.go
- pkg/api/configsync/register.go
- pkg/parse/event_handler.go
- pkg/parse/events/builder.go
- pkg/parse/events/events.go
- pkg/parse/events/funnel_test.go
- pkg/parse/root_reconciler_test.go
- pkg/parse/run.go
- pkg/parse/run_test.go
- pkg/reconciler/reconciler.go
- Consolidate resetPartialCache calls into the DefaultRunFunc.
This makes the run func act more like a controller.
- Align the event names, trigger names, and period names.
FullSync means parse from the filesystem and update the cluster,
even if nothing changed.
Sync means only parse from filesystem and update the cluster if
there was a source change, like repo, commit, or syncDir change.
> chore: Clean up sync event naming & cache resets

- Makefile.build
This is intended to be a less generic name
> ci: rename the kustomize tarball to config-sync.tar.gz

- pkg/parse/event_handler.go
- pkg/parse/events/publisher.go
- Reset the retry backoff when syncing is skipped due to
prior successful sync and there are no conflicts or watch updates.
This ensures the retry event will still fire to check for new
conflicts and watch update requests from the remediator.
- Add logging with more details for debugging, but at level 3, to
avoid spamming customer logs.
> fix: ignored conflicts and watch updates

- Makefile
This is the latest patch version and contains some low severity CVE fixes.
> chore: bump otelcontribcol to 0.103.0-gke.5

- Makefile
This includes some low severity CVE fixes
> chore: bump git-sync to latest version

- pkg/parse/run.go
The setSourceStatusErr here was being re-initialized inside an if statement, which means it would always be nil outside the if statement.
This fix allows the source status update error to be returned and logged correctly when the checkpoint is invalidated.
The bug this fixes is relatively minor, because SetSourceStatus has its own internal retries. So it's unlikely that SetSourceStatus will return an error unless something is seriously wrong. However, if it does happen, it needs to be logged because the RSync status won't have been updated.
> fix: surface source status update error

- pkg/hydrate/controller.go
- pkg/parse/reconciler.go
- pkg/parse/run.go
- pkg/parse/state.go
- pkg/status/transient_error.go
- The new Render method handles checking the done file written by the hydration-controller sidecar.
- The code has been cleaned up a bit to handle errors as soon as possible, following the Return Early Pattern, which reduces cyclomatic complexity and improves readability.
- To avoid the Render method calling state.invalidate(errs) directly, the Render method now returns a TransientError when rendering is still in-progress. This is caught by state.invalidate and handled by logging at the info level, instead of as an error. It still causes a retry
- Added a RenderedCommit method that returns read errors instead of just logging them. This is used by the Render method, which should error if the done file cannot be read, unless it was not found. The original doneCommit now wraps RenderedCommit …
> chore: extract reconciler.Render method

- pkg/parse/event_handler.go
- pkg/parse/run.go
- pkg/parse/state.go
- Rename ReconcilerState methods to reflect the reconcile stages they are called after, rather than the state that they change. This makes it cleared when the methods should be called and documents what the state change does and why.
- Rework logging for the state transitions handled by the ReconcilerState methods.
- Wrap the checkpoint "lastApplied" syncPath in a struct that captures lastUpdateTime and lastTransitionTime, like a kubernetes condition. This makes it possible to tell both when the last sync suceeded or failed and also when it first suceeded for the current commit (as long as it hasn't since failed). For now, this is only visible in the logs, but we may want to expose it via the RSync status in the future.
Ideas for future cleanup:
- Add state transition methods for each …
> chore: ReconcilerState cleanup

- pkg/parse/reconciler.go
- pkg/parse/repo_sync_client.go
- pkg/parse/root_sync_client.go
- pkg/parse/run.go
- pkg/parse/status.go
- Use the standard if err != nil pattern for all calls to set status to return early, making the code easier to read and more consistent.
- Remove unused ReconcilerStatus.SyncingConditionLastUpdate
- Use variable names consistently in run.go: newSourceStatus, newRenderStatus, newSyncStatus, and statusErr.
> chore: cleanup reconciler set status method usage

- Makefile
bumping up the git-sync even though it's not clear that it's addressing any CVEs
> chore: git sync update to v4.3.0-gke.3__linux_amd64

- pkg/parse/reconciler.go
- pkg/parse/run.go
- pkg/parse/state.go
- Extract reconciler.Fetch & method to simplify DefaultRunFunc
- Rename checkpoint.sourcePath to syncPath to match rename elsewhere
- Clarify some inline comments
Dependencies:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1481
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1482
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1484
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1485
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1488
> chore: extract Reconciler.Fetch method

- pkg/parse/event_handler.go
- pkg/parse/reconciler.go
- pkg/parse/root_reconciler_test.go
- pkg/parse/run.go
- pkg/parse/run_test.go
- pkg/reconciler/reconciler.go
- Rename DefaultRunFunc as reconciler.Reconciler.
- Remove methods from the Reconciler interface only used by reconciler.Reconcile.
- Add Reconciler.UpdateSyncStatus to simplify event handling.
- Make reconciler methods private that no longer need to be exposed.
> chore: DefaultRunFunc -> reconciler.Reconcile

- pkg/parse/cache.go
- pkg/parse/root_reconciler_test.go
- pkg/parse/run.go
- pkg/parse/updater.go
- pkg/webhook/configuration/update.go
- Split reconciler.parseAndUpdate into parse and update methods.
- Move handling of non-blocking errors and webhook GVK updates out to the Reconcile method.
- Combine parse and parseSource methods.
- Wrap some of the cache fields in a parseResult, to make it clear that those fields are updated atomicly and make a namespace to simplify method names related to parsing.
- Move GVK set building to a parseResult.GVKs method, instead of passing all the objects to webhook.Update.
- Update some of the unit tests to test just the parse method.
I want to do more to clean up cacheForCommit, to add updateResult, and split sourceResult into fetchResult and renderResult, but this seems like enough for one PR.
> chore: split parse & update methods

- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
- pkg/resourcegroup/controllers/root/root_controller_test.go
- pkg/resourcegroup/controllers/runner/run.go
- pkg/resourcegroup/controllers/typeresolver/fake_discovery.go
- pkg/resourcegroup/controllers/typeresolver/typeresolver.go
- pkg/resourcegroup/controllers/typeresolver/typeresolver_test.go
- This change allows the resource-group-controller-manager to use cached resource group records when the records are stale due to unavailable APIService backends, like metrics-server, which often has only one replica.
- All other discovery errors will now also cause the TypeResolver controller to retry discovery, with logging and retry backoff handled by the controller manager.
- If discovery fails when the TypeResolver is first created, it will cause the process to error and exit. Then the container runtime should restart the container.
- This should prevent ResourceGroup status from marking all resources as NotFound when discovery fails.
Fixes: b/379943950
Note: This only fixes the problem in the resource-group-controller-manager, and only when Aggregated Discovery is enabled, which is …
> fix: tollerate stale resource group discovery

- cmd/nomos/status/status.go
* Removes the mentions of multi-repo 
* Added some more examples 
* Make the description more clear about usage against R*Syncs
> Improves the flag description of `nomos status`

- pkg/parse/event_handler.go
- pkg/remediator/reconcile/worker.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/manager.go
- pkg/status/error.go
These errors are often distracting red herrings that hinder debugging customer issues. They should only be logged to stdout as informative, not warnings or errors.
> fix: don't log context canceled as an error

- e2e/nomostest/clusters/gke.go
- Warnings printed to STDERR were being captured as in-progress operations, causing listOperations to error. This change fixes that issue by disabling human output for that command.
> fix: ignore gcloud operations list warnings

- pkg/auth/token_provider.go
This was causing oci-sync and helm-sync to deadlock and crash.
Bug introduced by https://github.com/GoogleContainerTools/kpt-config-sync/pull/1505
> fix: mutex unlocking in LoggingTokenProvider

- e2e/testcases/ignore_mutation_test.go
- e2e/testcases/managed_resources_test.go
- pkg/applier/applier.go
- pkg/applier/applier_test.go
- pkg/applier/fake/applier.go
- pkg/applier/utils.go
- pkg/applier/utils_test.go
- pkg/declared/resources.go
- pkg/declared/resources_test.go
- pkg/metadata/annotations.go
- pkg/metadata/metadata.go
- pkg/metadata/metadata_test.go
- pkg/parse/root_reconciler_test.go
- pkg/parse/updater.go
- pkg/remediator/reconcile/reconciler.go
- pkg/remediator/reconcile/reconciler_test.go
- pkg/remediator/watch/filteredwatcher.go
- pkg/remediator/watch/filteredwatcher_test.go
- pkg/syncer/reconcile/as_unstructured.go
- pkg/syncer/syncertest/reconcile.go
A cache has been added to Resources which stores the cluster state of all objects with the ignore-mutation annotation. The Applier uses the in-memory config with the declared CS metadata applied on top of it instead of only the declared object.
>  fix: the ignore mutation annotation in the applier

- e2e/nomostest/testpredicates/predicates.go
- e2e/testcases/hydration_test.go
- Validate the RSync status directly, instead of using an internal nomos CLI function which hides the errors and makes it difficult to debug test failures.
- Validate source, rendering, and sync status, not just rendering, to ensure no other errors are being returned.
- Validate Syncing status condition too.
Depends on https://github.com/GoogleContainerTools/kpt-config-sync/pull/1514
> e2e: Improve rendering status validation

- .aiexclude
From https://cloud.google.com/gemini/docs/codeassist/create-aiexclude-file#examples it seems that the trailing `/` might be necessary for it to exclude all files and subdirectories of `vendor/`
> Exclude vendor folder from AI review

- Makefile
This updates the Go version contained in the build/CI images in preparation for bumping the Go version in the module.
> chore: bump Go version used by build images

- manifests/cluster-selector-crd.yaml
- manifests/hierarchyconfig-crd.yaml
- manifests/namespace-selector-crd.yaml
- manifests/reposync-crd.yaml
- manifests/resourcegroup-crd.yaml
- manifests/rootsync-crd.yaml
The standard make target rebuilds the generated CRD manifests, which causes the copyright date to be updated to the current year. So this change updates the copyright date to match the expectation.
It would be ideal if the generation script only updated the copyright if the file had otherwise changed, but that's a more complicated change.
> Update manifest copyright to satisfy linter

- e2e/nomostest/config_sync.go
- e2e/testcases/composition_test.go
- e2e/testcases/multi_sync_test.go
- pkg/applier/applier.go
- pkg/applier/utils.go
- pkg/applier/utils_test.go
Change ObjMetaFromObject to use the Scheme to get the GVK from typed objects, instead of relying on the code to populate the GVK on all objects. This requires handling errors when the type is unknown.
This is a prerequisite for removing the GVK from typed objects.
> chore: use scheme to get GVK of typed objects

- pkg/syncer/differ/special_namespaces.go
The IsManageableSystemNamespace function currently requires typed namespace objects to have their GroupVersionKind set. This update adds checks for the v1.Namespace type to avoid that requirement.
This is part of a larger effort to not require typed objects to have their GVK set.
> chore: update IsManageableSystemNamespace

- pkg/importer/analyzer/validation/nonhierarchical/crd_name_validator.go
The old text mentioned the solution but not the problem. Using backticks instead of quotes also makes the error easier to read because they don't need to be escaped in yaml/json or logs.
> chore: improve the InvalidCRDName error message

- scripts/vulnerabilities.sh
It appears the API was updated for this json payload, it now includes a location subpath in the noteName value.
> ci: fix vuln scan jq to use location in noteName

- scripts/vulnerabilities.sh
It appears the API was updated for this json payload, it now includes a location subpath in the noteName value.
> [cherry-pick] ci: fix vuln scan jq to use location in noteName (#1533)

- docs/development.md
Fixes: https://github.com/GoogleContainerTools/kpt-config-sync/issues/1497
> Add gcloud auth requirement to docs

- e2e/nomostest/oci-image-verification-server.go
This sets the USE_GOOGLE_AUTHENTICATOR variable on the test oci signature verification webhook server, such that the google authenticator is only enabled when using GKE and GAR.
> test: set USE_GOOGLE_AUTHENTICATOR for oci sig server

- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
The next controller-runtime version requires each controller instantiation to have a unique name. By default the controller is given the name of the CRD type, e.g. rootsync/reposync.
Since each unit test instantiates a new controller, it needs a unique name.
> test: add controllerName to rsync unit tests

- e2e/testcases/basic_test.go
The RSync name/namespace lengths are constrained by labels which are added to objects created by Config Sync. These test cases document the current behavior.
> test: add e2e tests to verify the max RSync NN length

- e2e/testcases/basic_test.go
- e2e/testcases/multi_sync_test.go
- pkg/reconcilermanager/constants.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
This adds validation logic for the maximum RSync name/namespace length in the reconciler-manager. This constraint already existed due to labels which were mapped from the RSync name/namespace. This change just adds explicit validation so that the errors are caught earlier and a clear error message is emitted.
> feat: validate RSync length in reconciler-manager

- cmd/admission-webhook/main.go
- cmd/reconciler-manager/main.go
- cmd/reconciler/main.go
- pkg/reconciler/reconciler.go
- pkg/reconcilermanager/controllers/crd_controller.go
- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/helm_value_files.go
- pkg/reconcilermanager/controllers/logging_controller.go
- pkg/reconcilermanager/controllers/otel_base_controller.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/otel_sa_controller.go
- pkg/reconcilermanager/controllers/reconciler_base.go
- pkg/reconcilermanager/controllers/reconciler_base_test.go
- pkg/reconcilermanager/controllers/reconciler_finalizer_handler.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
- pkg/reconcilermanager/controllers/secret.go
- pkg/reconcilermanager/controllers/secret_test.go
- pkg/resourcegroup/controllers/handler/handler_test.go
- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
- pkg/resourcegroup/controllers/root/main_test.go
- pkg/resourcegroup/controllers/root/root_controller.go
- pkg/resourcegroup/controllers/runner/run.go
- pkg/resourcegroup/controllers/typeresolver/typeresolver.go
- pkg/resourcegroup/controllers/typeresolver/typeresolver_test.go
- pkg/resourcegroup/controllers/watch/filteredwatcher.go
- Use dot syntax in logr field key names, unless specifically referencing a resource field name. 
- Log API operations at level 3 before the call, and level 1 after the call, only if the operation was not skipped, to reduce noise.
- Make the before and after logs similar syntax (e.g. deleting, upserting, applying, patching)
- Don't log errors from controller Reconcile methods, unless they're not returned, because the controller-runtime will log the returned error for us.
- Use APIServerError even for controller errors, because it has help text for RBAC forbidden errors
- Use level 3 for controller Reconcile method start/finish logs to reduce noise
Depends on https://github.com/GoogleContainerTools/kpt-config-sync/pull/1553 & https://github.com/GoogleContainerTools/kpt-config-sync/pull/1565 …
> fix: reconfigure controllers to use klog via logr

- pkg/resourcegroup/controllers/resourcegroup/condition.go
- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
The ResourceGroup controller has been updating status conditions every time it reconciles, even when nothing changed but the LastTransitionTime.
This change fixes that problem by only updating the conditions if another condition field changed. This prevents the pre-existing semantic DeepEquals from always failing.
> fix: ResourceGroup unnecessary timestamp updates

- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
- pkg/resourcegroup/controllers/root/root_controller.go
- Fixed a bug that was causing the `status` field to remain `Current` after the object had successfully reconciled, even if the object later became `InProgress`, `Terminating`, or `Failed`. This will cause nomos status and the Cloud Console UI to correctly show the current status after initial reconciliation, rather than just the status based on the last time the Applier ran. 
- Fixed a bug that was causing the `status` field to become `Unknown` when the object is actually `Terminating` when the `actuation` is empty/unknown, `pending`, `skipped`, or `failed`. Now, the `Terminating` and `NotFound` statuses should be correctly exposed for previously applied objects, even if the object spec has not been updated to match the source of truth yet.
- Refactored ActuationStatusToLegacy to be …
> fix: ResourceGroup resource status bugs

- Makefile
This resolves some CVEs in the prior version
> chore: bump git-sync to v4.3.0-gke.11__linux_amd64

- Makefile
This resolves some CVEs in the prior version
> chore: bump otelcontribcol to v0.103.0-gke.8

- Makefile
This resolves some CVEs in the previous image
> chore: bump debian-base to bookworm-v1.0.4-gke.4

- pkg/resourcegroup/controllers/root/root_controller.go
This change fixes multiple bugs:
- Removed the `statusNeedsUpdate` filter to fix a bug (b/399896613) 
where object update events might be ignored, if they
occur while the ResourceGroup controller is computing the latest
status. This could cause the status in the ResourceGroup to
become stale until the next object update event or apply attempt.
- Removed the `Reconciling` condition filter, which is obsolete after
https://github.com/GoogleContainerTools/kpt-config-sync/pull/1571
Prior to deprecating the `Reconciling` condition, this filter was actually
contributing to the above bug  (b/399896613). That's why deprecation
was a dependency that needed to be fixed before this PR could be merged.
- Removed the `isStatusDisabled` early exit case, which becomes obsolete
after the other filters are …
> fix: ResourceGroup status updates missed

- e2e/testdata/hydration/compiled-json/helm-components/wordpress/secret_my-wordpress.json
- e2e/testdata/hydration/compiled/helm-components/wordpress/secret_my-wordpress.yaml
The helm chart referenced a Secret which is expected to be created out of band, but the Secret did not exist. This caused the package to never reconcile.
Replacing this with an inline wordpressPassword handles creation of the Secret by the helm chart so that it can reconcile.
> test: fix helm-components chart so that it reconciles

- e2e/nomostest/wait_for_sync.go
- e2e/testcases/profiling_test.go
This refactor adds flexibility to WatchForSync to accept options in addition to WatchOption. This is built on by a subsequent PR.
The usage of ResourceGroup predicates are removed because WatchForAllSyncs watches RSyncs, so these predicates were invalid.
> test: refactor WatchForSync to take opt struct

- e2e/nomostest/new.go
- e2e/nomostest/nt.go
There are some long lived containers, such as reconciler-manager, which will accumulate a large amount of logs over the duration of the test suite. When a test fails, it dumps the Pod logs and can result in a large quantity of logs which are not relevant to the failed test.
This truncates the logs based on the start time of the test, to ensure only relevant logs are included.
> test: truncate Pod logs for each test case

- e2e/nomostest/sync.go
- e2e/nomostest/testpredicates/predicates.go
- e2e/nomostest/testresourcegroup/resourcegroup.go
- e2e/nomostest/wait_for_sync.go
- e2e/testcases/basic_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/override_reconcile_timeout_test.go
- e2e/testcases/status_enablement_test.go
- pkg/resourcegroup/controllers/root/root_controller.go
- pkg/resourcegroup/controllers/status/status.go
- pkg/resourcegroup/resourcegroup.go
- pkg/resourcegroup/resourcegroup_test.go
This adds validation for the ResourceGroup status in the WatchForSync function, which is used extensively in the test framework to validate RSyncs and wait for them to finish syncing.
This will cause WatchForSync to now also wait for all synced objects to reconcile and for the ResourceGroup to be current. This is intended to provide test coverage for the resource-group-controller when integrated with Config Sync.
> test: add ResourceGroup assertions to WatchForSync

- e2e/nomostest/testkubeclient/client.go
- e2e/testcases/cluster_selectors_test.go
- e2e/testcases/custom_resource_definitions_test.go
- e2e/testcases/custom_resources_test.go
- e2e/testcases/multiversion_test.go
- e2e/testcases/resource_group_controller_test.go
Pulled out most these changed from https://github.com/GoogleContainerTools/kpt-config-sync/pull/1575, which should make it easier to see the coordination changes in that PR if this one merges first.
Dependencies:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1591
> test: cleanup ResourceGroup controller e2e tests

- Makefile
The gcloud image was updated to the latest version by updating the GCLOUD_IMAGE_VERSION variable in the Makefile. This change affects the following files:
- build/buildenv/Dockerfile
- build/prow/e2e/Dockerfile
- build/prow/vulnerability-scanner/Dockerfile
No other files needed to be changed because the GCLOUD_IMAGE_VERSION variable is used to set the image in all Dockerfiles.
> Update gcloud image to latest version

- e2e/testcases/status_enablement_test.go
- reflect.DeepEqual worked, but Semantic.DeepEqual is preferred for Kubernetes resources.
- Error with the YAML diff if the status is still set
> e2e: Use Semantic.DeepEqual to test empty status

- e2e/testcases/reconciler_manager_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
To avoid conflicts, you have to get the object from the cluster before each retry, to get the latest resource version. It's also good to rebuild the object, to reset the metadata, like UID and resourceVersion, to make sure you get the latest object from the cluster, not an old version.
Fixes: b/399904244
> test: fix uses of RetryOnConflict

- e2e/testdata/helm-charts/coredns/templates/configmap.yaml
- e2e/testdata/helm-charts/coredns/templates/service.yaml
- e2e/testdata/helm-charts/coredns/templates/serviceaccount.yaml
The ConfigMap and Service were always created in the default namespace, which resulted in the Deployment never being able to reconcile. This change ensures the other objects are created in the same namespace as the Deployment.
> test: fix coredns helm chart to reconcile

- e2e/testcases/stress_test.go
These stress tests either take too long to reconcile or do not reconcile, and therefore should skip ResourceGroup checks.
> test: skip resourcegroup checks in stress tests

- e2e/nomostest/testkubeclient/client.go
This makes it easier to tell what object was created when using Unstructured objects.
> test: make KubeClient print object kind and type

- e2e/flags.go
- e2e/nomostest/client.go
- e2e/testcases/main_test.go
- e2e/testcases/stress_test.go
For stress tests, use more smaller nodes:
- 3 -> 12 nodes
- n2-standard-8 -> n2-standard-4
- 50Gb -> 25Gb disks
This works around the 110 pod per node limit in GKE, allowing the test to schedule 1,000 pods. The pods are tiny and just sleep.
> test: Fix TestStressManyDeployments reconciling

- e2e/nomostest/sync.go
- e2e/nomostest/wait_for_sync.go
- e2e/testcases/status_enablement_test.go
- e2e/testcases/stress_test.go
- Conditions will be empty when status is disabled
- status.observedGeneration will be 0 when status is disabled
- Validate status.resourceStatuses with DeepEqual and log the yaml diff on error
Extracted:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1601
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1602
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1603
> test: fix ResourceGroup expectations

- Makefile
- e2e/testdata/otel-collector/otel-cm-full-gcm.yaml
- e2e/testdata/otel-collector/otel-cm-kustomize-rejected-labels.yaml
- e2e/testdata/otel-collector/otel-cm-monarch-rejected-labels.yaml
- manifests/base/kustomization.yaml
- manifests/otel-agent-reconciler-cm.yaml
- manifests/templates/otel-collector.yaml
- manifests/templates/reconciler-manager-configmap.yaml
- manifests/templates/reconciler-manager.yaml
- manifests/templates/resourcegroup-manifest.yaml
- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
- test/kustomization/expected.yaml
Updating otelcontribcol to latest to include fix of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35006 and other essential security updates in components like Prometheus exporter.
The upgrade covers a breaking change in otelcontribcol of defaulting to local host instead of 0.0.0.0, the feature is now stable and [feature gate](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30702) has been [removed](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36589), Config Sync should explicitly set endpoint to host 0.0.0.0 to expose port for external pod access. This applies to the metric receiver `opencensus`, and the exporter `prometheus`.
This update also separates the ConfigMap for the otel-agent, distinguishing the one …
> Update otelcontribcol to 0.118.0-gke.3

- e2e/testcases/reconciler_finalizer_test.go
- e2e/testcases/reconciler_manager_test.go
- pkg/core/scheme.go
- pkg/reconcilermanager/controllers/garbage_collector.go
- pkg/reconcilermanager/controllers/reposync_controller.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- Makes sure that the ResourceGroup is deleted when the RSync is deleted, regardless of the deletion propagation policy 
- b/382533338
> feat: Delete the ResourceGroup when the RSync is deleted

- e2e/nomostest/testpredicates/predicates.go
- e2e/nomostest/wait.go
- Include the full kstatus response in the error when the StatusEquals predicate fails, including the message and conditions.
- Update WaitForNamespace to use the StatusEquals predicate.
> test: log more details for unexpected status

- pkg/declared/namespace_safeguard_test.go
- pkg/remediator/reconcile/reconciler_test.go
- pkg/validate/raw/validate/source_spec_validator_test.go
- Removes reference to obsolete bug
- Cleans some tests up by validating errors by their exact type and message and not just their error code
> test: refactor some unit tests to use exact errors

- e2e/nomostest/sync.go
- e2e/nomostest/testpredicates/predicates.go
- e2e/nomostest/testresourcegroup/resourcegroup.go
Update resourceGroupHasReconciled to make it easier to debug the errors, by grouping all the status checks together, so there's one big diff when it fails.
Use ResourceGroupStatusEquals because it already handles removing the timestamps before comparison.
> test: refine ResourceGroup expectations

- e2e/testcases/status_enablement_test.go
- pkg/applier/applier.go
- pkg/applier/applier_test.go
- pkg/applier/destroyer_test.go
- pkg/applier/utils.go
- pkg/reconciler/reconciler.go
* refactor: streamline the supervisor constructor
This refactors the supervisor constructor to consolidate the
RepoSync/RootSync supervisors into a single constructor.
The AnnotateStatusMode step is also moved to a separate interface method
so that the constructor does not make api calls or return an error.
* fix: retry on conflict for annotating RG status mode
This wraps AnnotateStatusMode so that it handles conflict errors
gracefully instead of causing the reconciler to crash.
> refactor supervisor constructor

- e2e/nomostest/deletion_propagation.go
- e2e/testcases/otel_collector_test.go
- pkg/core/decorate.go
- pkg/core/decorate_test.go
- pkg/reconcilermanager/controllers/otel_base_controller.go
- pkg/reconcilermanager/controllers/reconciler_base.go
Return true when the labels or annotations were changed, to allow skipping update calls when there's no change.
> refactor: return bool from metadata methods

- e2e/nomostest/testpredicates/predicates.go
ResourceGroupStatusEquals was recently modified to print a diff when the status didn't match expectations. This helps debugging when the ResourceGroup status is small, but when it's large it can cause significant memory use, sometimes more than 30GB. This was causing some of the stress tests to be OOMKilled.
Note: OOMKill can still happen when --debug is used, because it still prints YAML diffs for each watch event.
Fixes: b/406880508
> test: fix stress test being OOMKilled

- pkg/util/log/stringer.go
- pkg/util/log/stringer_test.go
- Limit diffing to object yaml that is at most 256 KB. This should help keep diff memory use under 2 GB.
> e2e: fix OOMKill when testing with --debug

- e2e/testcases/sync_ordering_test.go
- e2e/testinfra/terraform/modules/service_account/service_account.tf
Tests on CSR require workload identity bindings to be created for every RSync. The new TestSplitRSyncsWithDeletion test case used new RSync names that did not have workload identity bindings.
This fixes the issue by changing the RSync names to reuse already provisioned workload identity bindings.
> test: fix TestSplitRSyncsWithDeletion on CSR

- Makefile
[CVE-2024-56406 ](https://github.com/advisories/GHSA-p6jf-pv8c-623c)
> chore: update Debian base image version to bookworm-v1.0.4-gke.7

- Makefile
Fixes [CVE-2024-56406 ](https://github.com/advisories/GHSA-p6jf-pv8c-623c)
> chore: Bump git-sync to v4.3.0-gke.16__linux_amd64

- Makefile
Fixes [CVE-2025-1386](https://github.com/advisories/GHSA-m454-3xv7-qj85)
> chore: Bump otelcontribcol to v0.118.0-gke.7

- e2e/testcases/otel_collector_test.go
Cloud Monitoring recently changed the error message to be lowercase (cl/745657726). Update our expectation to match.
> test: fix TestOtelCollectorDeployment expectation

- e2e/testinfra/terraform/common/services.tf
Enable Cloud Logging API to allow collection of postsync controller logs and support postsync_logging_test verification.
Tested in a dev project to confirm that enabling the Logging API via Terraform works as expected.
> Enable cloud logging API in CI projects

- e2e/testcases/postsync_logging_test.go
Ensure waitForLogEntryInCloudLogs continuously retries until timeout when searching Cloud Logging.
> Fix retry in postsync cloud logging tests

- Makefile
> chore: bump otelcontribcol to 0.118.0-gke.9

- Makefile.build
Postsync status watch controller supports multi-arch builds by using a dedicated builder. This PR ensures the Docker builder is cleaned up afterward to prevent interference with other image builds.
> Remove buildx builder instance after image push

- e2e/nomostest/clusters/gke.go
- e2e/nomostest/retry/retry.go
The test scaffolding previously waited for cluster readiness by waiting for all operations to be complete, but that evidently is no longer sufficient to wait for cluster readiness. This change adds an additional check to make sure the cluster has the RUNNING status before handing off the cluster to the test framework.
> test: wait for GKE cluster readiness

- build/prow/e2e/Dockerfile
- cmd/junit-report/resetfailure/reset_failure.go
- go.mod
- go.sum
- scripts/e2e.sh
- vendor/github.com/jstemmer/go-junit-report/v2/gtr/gtr.go
- vendor/github.com/jstemmer/go-junit-report/v2/junit/junit.go
- vendor/modules.txt
This hack is no longer required as https://github.com/jstemmer/go-junit-report/issues/169 was fixed
> test: Revert parsing hack for go-junit-report

- build/prow/e2e/Dockerfile
- cmd/junit-report/resetfailure/reset_failure.go
- go.mod
- go.sum
- scripts/e2e.sh
- vendor/github.com/jstemmer/go-junit-report/v2/gtr/gtr.go
- vendor/github.com/jstemmer/go-junit-report/v2/junit/junit.go
- vendor/modules.txt
This reverts commit fd80f755de703f7848e2fc3444f840d329602c0e.
Reason for revert: This change appears to have broken the junit report parsing.
> Revert "test: Revert parsing hack for go-junit-report (#1667)"

- .github/dependabot.yml
kind update also requires updating the supported image tags
> ci: skip kind updates in dependabot

- cmd/junit-report/resetfailure/reset_failure.go
- go.mod
- go.sum
- scripts/e2e.sh
- vendor/github.com/jstemmer/go-junit-report/v2/Makefile
- vendor/github.com/jstemmer/go-junit-report/v2/README.md
- vendor/github.com/jstemmer/go-junit-report/v2/gtr/gtr.go
- vendor/github.com/jstemmer/go-junit-report/v2/internal/gojunitreport/go-junit-report.go
- vendor/github.com/jstemmer/go-junit-report/v2/junit/junit.go
- vendor/github.com/jstemmer/go-junit-report/v2/main.go
- vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/event.go
- vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/gotest.go
- vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/internal/collector/collector.go
- vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/internal/reader/reader.go
- vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/json.go
- vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/report_builder.go
- vendor/modules.txt
This release includes fixes for several workarounds that are implemented in our CI tooling.
The go-junit-report binary was changed to be installed at runtime, which addresses the reason this bump failed in the previous attempt.
Related: https://github.com/GoogleContainerTools/kpt-config-sync/pull/1688
> chore: bump github.com/jstemmer/go-junit-report/v2 from 2.0.0 to 2.1.0

- Makefile
The go-junit-report binary needs to be in the local gobin directory so that it can be mounted into the kind-e2e container. As a result the junit report was missing for kind tests.
Related to https://github.com/GoogleContainerTools/kpt-config-sync/pull/1688
> ci: ensure go-junit-report is available in local gobin

- Makefile
- scripts/test-kustomization.sh
This adds a make target to help with updating the expected.yaml file for the kustomization test.
> test: add target to update expect kustomization file

- e2e/testcases/reconciler_manager_test.go
If the number of actual tolerations was greater than the number of expected tolerations, this would cause a segfault.
Caused a panic/segfault on this execution: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-rapid/1925287984836382720
> test: fix hasTolerations segfault

- pkg/metrics/otel.go
- pkg/reconcilermanager/controllers/otel_controller.go
- pkg/reconcilermanager/controllers/otel_controller_test.go
To Use Go Struct and YAML Marshaling
Refactor the generation of the otel-collector Googlecloud ConfigMap to construct the configuration using a Go map and marshal it to YAML, replacing the previous approach of using a static YAML string. This change improves maintainability and reduces the risk of formatting errors in the generated config. Add GooglecloudCollectorConfigYAML() and deprecate the old CollectorConfigGooglecloud string constant. This refactor makes the config generation more robust and easier to extend or validate in the future.
> Refactor Otel Collector Googlecloud ConfigMap Generation

- e2e/nomostest/config_sync.go
- e2e/nomostest/testpredicates/predicates.go
- e2e/nomostest/testwatcher/watch.go
- e2e/nomostest/wait_for_sync.go
- e2e/testcases/basic_test.go
- e2e/testcases/github_test.go
- e2e/testcases/helm_sync_test.go
- e2e/testcases/multi_sync_test.go
- e2e/testcases/oci_sync_test.go
- e2e/testcases/proxy_test.go
- e2e/testcases/reconciler_manager_test.go
This refactors the Stalled condition validation to use the Watcher, similar to the validation for other conditions. This completes the refactoring of moving the condition validation from using the previous polling mechanism to using the watch mechanism. Streamlined error code validation for Stalled errors will be added in a subsequent change.
> test: use Watcher for validating Stalled errors

- Makefile
- cmd/nomos/initialize/init.go
- cmd/nomos/nomos.go
The cherrypick includes essential bug fixes, dependency update for CVE fixes and test updates.
```
841149a8 (HEAD -> v1.21) test: fix workload identity for TestAdoptImplicitNamespace (#1727)
8205e4a7 test: add e2e test for adopting implicit namespace (#1721)
6befc6bc test: use Watcher for validating Stalled errors (#1723)
e281a6ce fix: typo in ManagedResourceInUnmanagedNamespace (#1722)
ff2b8f3a chore: bump base image and git-sync or CVE fix (#1719)
70228240 fix: add completion message to nomos init command only (#1717)
f915b199 test: fix hasTolerations segfault (#1693)
c0807eda test: default to creating clusters for KinD only if -create-clusters=false (#1672)
0e704455 test: add checks for Config Sync sync labels on reconciler metrics (#1666)
cca9bef0 test: wait for GKE cluster readiness …
```
> [cherry-pick] v1.21.2

- pkg/remediator/watch/filteredwatcher.go
This error can occur when the RESTMapper fails to look up the object type, and has been observed to happen semi-frequently for the e2e TestCRDDeleteBeforeRemoveCustomResourceV1.
The e2e test is flaky because depending on the ordering of events, the conflict metric may not be recorded. This should fix the metric flakiness for this edge case.
> [cherry-pick] fix: handle IsNoMatchError for remediator startWatch (#1734)

- pkg/resourcegroup/controllers/runner/run.go
The gcp plugin is deprecated and simply a stub that errors.
> fix: remove deprecated gcp plugin from r-g-ctrllr

- cmd/nomos/nomos.go
- vendor/k8s.io/client-go/plugin/pkg/client/auth/OWNERS
- vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure_stub.go
- vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
- vendor/k8s.io/client-go/plugin/pkg/client/auth/plugins.go
- vendor/k8s.io/client-go/plugin/pkg/client/auth/plugins_providers.go
- vendor/modules.txt
This re-adds the oidc plugin support for the nomos command. The oidc plugin was removed unintentionally when trying to clean up the other deprecated plugins.
Note that this plugin is also supported by kubectl.
> [cherry-pick] fix: register auth plugins for nomos (#1739)

- e2e/testcases/helm_sync_test.go
- pkg/reconcilermanager/controllers/reposync_controller_test.go
- pkg/reconcilermanager/controllers/rootsync_controller_test.go
- pkg/validate/rsync/validate/source_spec_validator.go
- pkg/validate/rsync/validate/source_spec_validator_test.go
This change adds validation to spec.helm.chart to ensure that it contains no slashes. A KNV1061 error is returned to the user if this condition is not met.
E2E tests validate that this error is returned for both charts hosted in OCI-based registries and traditional Helm repos
b/423072233
> fix: add validation to spec.helm.chart

- Makefile
This updates git-sync to the latest patch version. This version includes an important bug fix. For more information see:
https://github.com/kubernetes/git-sync/releases
> chore: bump git-sync to v4.4.2

- Makefile
Fixes [GHSA-fv92-fjc5-jj9h](https://github.com/advisories/GHSA-fv92-fjc5-jj9h)
> chore: bump otelcontribcol to v0.118.0-gke.10

- go.mod
- go.sum
- vendor/k8s.io/kubernetes/pkg/features/kube_features.go
- vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
- vendor/modules.txt
Fixes [CVE-2025-4563](https://security-tracker.debian.org/tracker/CVE-2025-4563)
> chore: bump k8s.io/kubernetes to v1.32.6

- e2e/nomostest/config_sync.go
- e2e/nomostest/testutils/fleet_membership.go
- e2e/nomostest/wait.go
- e2e/testcases/acme_test.go
- e2e/testcases/cluster_selectors_test.go
- e2e/testcases/gatekeeper_test.go
- e2e/testcases/namespace_repo_test.go
- e2e/testcases/reconciler_manager_test.go
- e2e/testcases/stress_test.go
- e2e/testcases/workload_identity_test.go
This refactors the Wait test helper functions to return an error rather than calling Fatal within the test helper. This makes it simpler for the caller to decide how to handle the error and understand the control flow from the test.
Also refactors some of the code to use newer constructs like taskgroup.
> test: refactor Wait to return error

- e2e/nomostest/wait.go
- e2e/testcases/acme_test.go
This refactors the TestAcmeCorpRepo e2e test case
- Replace Wait with WatchObject where appropriate
- Replace checkResource with Validate
- Use canonical constant declarations
> test: refactor TestAcmeCorpRepo

- pkg/declared/resources.go
This function mutates the map in the critical section and therefore should not use a read lock.
> fix: use write lock for DeleteIgnored

- cmd/helm-sync/main.go
- cmd/oci-sync/main.go
- pkg/util/retry.go
- pkg/util/retry_test.go
fix: use intended 1hr backoff cap for oci-sync/helm-sync
Casting the default duration to float64 was resulting in the incorrect
units being used (nanoseconds instead of seconds). This bug resulted in
a much larger backoff cap than intended.
This change properly casts the value to seconds and results in the
intended default backoff cap of 1 hour.
---
refactor: consolidate error backoff for sync containers
This change consolidates the function used to construct the error
backoff for the helm-sync and oci-sync containers. A unit test is added
to verify that the Cap is set as intended.
> fix: use intended 1hr backoff cap for oci-sync/helm-sync

- e2e/testinfra/terraform/common/registries.tf
- e2e/testinfra/terraform/common/service_accounts.tf
- e2e/testinfra/terraform/common/services.tf
- e2e/testinfra/terraform/main.tf
- e2e/testinfra/terraform/modules/service_account/service_account.tf
- e2e/testinfra/terraform/modules/service_account/variables.tf
- e2e/testinfra/terraform/prow/service_accounts.tf
This PR adds the TF configs that are needed to provision the resources needed to test SSM
> ci: Add TF configs for SSM

- e2e/nomostest/gitproviders/repository.go
- e2e/nomostest/gitproviders/secure_source_manager.go
Some versions of git do not support wildcards in the credential helper host name matching. This issue was encountered in the test environment, which was not correctly using the credential helper.
This change fixes the test runner and increases the portability/explicitness of the credential helper.
> test: fix SSM credential helper entry to use explicit hostname

- e2e/testcases/multi_sync_test.go
- e2e/testcases/reconciler_manager_test.go
Since SSM uses 'gcpserviceaccount' for authentication, it doesn't require a Secret to be created. This change fixes some tests that were failing as they validated the existence of a Secret.
> test: fix tests failing with SSM gitprovider

- e2e/nomostest/gitproviders/gitlab.go
The CI tests were occasionally failing with "Project has been already marked for deletion" 
errors during cleanup operations. This likely happens when multiple cleanup processes 
try to delete the same repository or when repository deletion takes time to 
complete.
Change to treat "already marked for deletion" responses as successful cases rather than
errors, since the repository will be deleted regardless.
> Skip delete repo if already marked for deletion

- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
- pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
This commit fixes a bug in the ResourceGroup controller where the ownership condition was occasionally added to the status for objects which were not found.
This happened when the object was cached as NotFound by the FilteredWatcher. The Reconcile loop would then use the cached object and call setResStatus, which incorrectly added the ownershipCondition.
The fix ensures that if the cached status is NotFound, the reconciler skips the call to setResStatus.
A unit test, TestComputeStatus, has been added to verify this behavior.
> fix: Prevent adding ownership condition for NotFound objects

- e2e/testcases/stress_test.go
A recent change intentionally removed the ownership condition from NotFound objects. This change updates the test expectation to be consistent with the new behavior.
Note that this was not caught in presubmits because the stress tests do not run as presubmits.
See https://github.com/GoogleContainerTools/kpt-config-sync/pull/1819
> test: fix TestStressResourceGroup expectation

- e2e/flags.go
- e2e/nomostest/gitproviders/bitbucket.go
This change parametrizes the bitbucket workspace so that it can be set at runtime. The primary motivation of this change is to simplify the management of the workspace, such that it can be updated directly in the prow configuration without requiring cherry picking.
> test: parametrize the bitbucket workspace

- pkg/bugreport/bugreport.go
- pkg/bugreport/bugreport_test.go
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/interceptor/intercept.go
- vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
* Fixes the logic in `nomos bugreport` such that the monorepo notice is printed only if the ConfigManagement object is present and configured for mono repo mode.
* Adds unit tests to validate the new behavior
* b/422835662
> fix: logic of when to print monorepo notice

- e2e/testcases/hydration_test.go
Example of failing test: https://oss.gprow.dev/view/gcs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-kind/1961121217469485056
> test: Add t.Skip to failing test while a fix is worked on

- e2e/testcases/hydration_test.go
- e2e/testdata/hydration/compiled-json/helm-components/wordpress/deployment_my-wordpress.json
- e2e/testdata/hydration/compiled/helm-components/wordpress/deployment_my-wordpress.yaml
- e2e/testdata/hydration/helm-components-remote-values-kustomization.yaml
- e2e/testdata/hydration/helm-components/kustomization.yaml
* Use hermetic helm chart for wordpress
* update test expectation
> v1.22.1: additional cherrypick to restore test coverage

- Makefile
> chore: bump git-sync to v4.4.2-gke.3

- cmd/nomos/status/client.go
- cmd/nomos/status/status_test.go
This change refactors output of `nomos status` to provide a more accurate output when no RootSync and/or RepoSyncs are found on the cluster.
* Removes UNKNOWN status when no RootSync and/or RepoSync is found on the cluster but Config Sync is running
* Removes "No RootSync resources found" error when a RepoSync exists on the cluster and vice versa
* Replaces error messages with concrete errors to improve the overall error handling logic
* Adds additional test cases to validate the error handling and output of `nomos status`
> fix: improve `nomos status` output when no sync objects are found

- e2e/nomostest/testwatcher/watch.go
- e2e/testcases/resource_group_controller_test.go
This change updates TestResourceGroupApplyStatus to always log the diff when an unexpected ResourceGroup update happens. This test has been somewhat flaky and this additional logging is intended to help understand the root cause of the test flake.
> test: log ResourceGroup diff on unexpected updates

- e2e/testcases/helm_sync_test.go
This is no longer required given the new minimal Helm chart that's used
> test: remove helm-sync memory increase

- e2e/testcases/managed_resources_test.go
This change replaces all calls to Validate in managed_resources_test.go with nt.Must(nt.Validate())
> test: add Must to Validate calls
